/*

List of cepheids from Inno et al. (in prep).

*/

CREATE TABLE catalogdb.gaia_assas_sn_cepheids (
    source TEXT,
    ref TEXT,
    star TEXT,
    period DOUBLE PRECISION,
    amp_v DOUBLE PRECISION,
    mean_v DOUBLE PRECISION,
    a1_v DOUBLE PRECISION,
    source_id BIGINT,
    random_index INTEGER,
    ref_epoch REAL,
    ra DOUBLE PRECISION,
    ra_error DOUBLE PRECISION,
    dec DOUBLE PRECISION,
    dec_error DOUBLE PRECISION,
    parallax DOUBLE PRECISION,
    parallax_error DOUBLE PRECISION,
    parallax_over_error DOUBLE PRECISION,
    pmra DOUBLE PRECISION,
    pmra_error DOUBLE PRECISION,
    pmdec DOUBLE PRECISION,
    pmdec_error DOUBLE PRECISION,
    ra_dec_corr DOUBLE PRECISION,
    ra_parallax_corr DOUBLE PRECISION,
    ra_pmra_corr DOUBLE PRECISION,
    ra_pmdec_corr DOUBLE PRECISION,
    dec_parallax_corr DOUBLE PRECISION,
    dec_pmra_corr DOUBLE PRECISION,
    dec_pmdec_corr DOUBLE PRECISION,
    parallax_pmra_corr DOUBLE PRECISION,
    parallax_pmdec_corr DOUBLE PRECISION,
    pmra_pmdec_corr DOUBLE PRECISION,
    phot_g_n_obs SMALLINT,
    phot_g_mean_flux DOUBLE PRECISION,
    phot_g_mean_flux_error DOUBLE PRECISION,
    phot_g_mean_flux_over_error DOUBLE PRECISION,
    phot_g_mean_mag DOUBLE PRECISION,
    phot_bp_n_obs SMALLINT,
    phot_bp_mean_flux DOUBLE PRECISION,
    phot_bp_mean_flux_error DOUBLE PRECISION,
    phot_bp_mean_flux_over_error DOUBLE PRECISION,
    phot_bp_mean_mag DOUBLE PRECISION,
    phot_rp_n_obs SMALLINT,
    phot_rp_mean_flux DOUBLE PRECISION,
    phot_rp_mean_flux_error DOUBLE PRECISION,
    phot_rp_mean_flux_over_error DOUBLE PRECISION,
    phot_rp_mean_mag DOUBLE PRECISION,
    phot_bp_rp_excess_factor DOUBLE PRECISION,
    phot_proc_mode SMALLINT,
    bp_rp DOUBLE PRECISION,
    bp_g DOUBLE PRECISION,
    g_rp DOUBLE PRECISION,
    radial_velocity DOUBLE PRECISION,
    radial_velocity_error DOUBLE PRECISION,
    a_g_val DOUBLE PRECISION,
    a_g_percentile_lower DOUBLE PRECISION,
    a_g_percentile_upper DOUBLE PRECISION,
    e_bp_min_rp_val DOUBLE PRECISION,
    e_bp_min_rp_percentile_lower DOUBLE PRECISION,
    e_bp_min_rp_percentile_upper DOUBLE PRECISION,
    variability DOUBLE PRECISION,
    type TEXT,
    twomass TEXT,
    raj2000 DOUBLE PRECISION,
    dej2000 DOUBLE PRECISION,
    errhalfmaj REAL,
    errhalfmin REAL,
    errposang REAL,
    jmag REAL,
    hmag REAL,
    kmag REAL,
    e_jmag REAL,
    e_hmag REAL,
    e_kmag REAL,
    qfl TEXT,
    rfl SMALLINT,
    x SMALLINT,
    measurejd DOUBLE PRECISION,
    angdist DOUBLE PRECISION
);

\COPY catalogdb.gaia_assas_sn_cepheids FROM '/uufs/chpc.utah.edu/common/home/sdss50/sdsswork/target/catalogs/gaia_assas_sn_cepheids/gaia_assas_sn_cepheids_Jun_2020.csv' WITH CSV HEADER;

ALTER TABLE catalogdb.gaia_assas_sn_cepheids ADD PRIMARY KEY (source_id);
