-- The below "create table" statement is based on the column information
-- in specObj-dr17.fits.
-- The fits file is in /uufs/chpc.utah.edu/common/home/sdss50/dr17/sdss/spectro/redux/
--
-- columns with "array" datatype in the fits file are
-- columns with "text" datatype in the below "create table" statement.
--
-- Note that various ID related columns (e.g. specobjid) have 
-- the data type varchar since the corresponding columns in
-- the file specObj-dr17.fits have the data type character.
--
-- The column specobjid has data type varchar since
-- it has values which do not fit in bigint.
--
-- See the below link for the data model
-- https://data.sdss.org/datamodel/files/SPECTRO_REDUX/specObj.html

create table catalogdb.sdss_dr17_specobj(
SURVEY varchar,  -- format = '6A'
INSTRUMENT varchar,  -- format = '4A'
CHUNK varchar,  -- format = '16A'
PROGRAMNAME varchar,  -- format = '27A'
PLATERUN varchar,  -- format = '16A'
PLATEQUALITY varchar,  -- format = '8A'
PLATESN2 real,  -- format = 'E'
DEREDSN2 real,  -- format = 'E'
 LAMBDA_EFF real,  -- format = 'E'
 BLUEFIBER integer,  -- format = 'J'
 ZOFFSET real,  -- format = 'E'
 SNTURNOFF real,  -- format = 'E'
 NTURNOFF integer,  -- format = 'J'
 SPECPRIMARY smallint,  -- format = 'B'
 SPECSDSS smallint,  -- format = 'B'
 SPECLEGACY smallint,  -- format = 'B'
 SPECSEGUE smallint,  -- format = 'B'
 SPECSEGUE1 smallint,  -- format = 'B'
 SPECSEGUE2 smallint,  -- format = 'B'
 SPECBOSS smallint,  -- format = 'B'
 BOSS_SPECOBJ_ID integer,  -- format = 'J'
 SPECOBJID varchar,  -- format = '22A'
 FLUXOBJID varchar,  -- format = '19A'
 BESTOBJID varchar,  -- format = '19A'
 TARGETOBJID varchar,  -- format = '22A'
 PLATEID varchar,  -- format = '20A'
 NSPECOBS smallint,  -- format = 'I'
 FIRSTRELEASE varchar,  -- format = '4A'
 RUN2D varchar,  -- format = '7A'
 RUN1D varchar,  -- format = '7A'
 DESIGNID integer,  -- format = 'J'
 CX double precision,  -- format = 'D'
 CY double precision,  -- format = 'D'
 CZ double precision,  -- format = 'D'
 XFOCAL real,  -- format = 'E'
 YFOCAL real,  -- format = 'E'
 SOURCETYPE varchar,  -- format = '25A'
 TARGETTYPE varchar,  -- format = '8A'
 THING_ID_TARGETING bigint,  -- format = 'K'
 THING_ID integer,  -- format = 'J'
 PRIMTARGET integer,  -- format = 'J'
 SECTARGET integer,  -- format = 'J'
 LEGACY_TARGET1 integer,  -- format = 'J'
 LEGACY_TARGET2 integer,  -- format = 'J'
 SPECIAL_TARGET1 bigint,  -- format = 'K'
 SPECIAL_TARGET2 bigint,  -- format = 'K'
 SEGUE1_TARGET1 integer,  -- format = 'J'
 SEGUE1_TARGET2 integer,  -- format = 'J'
 SEGUE2_TARGET1 integer,  -- format = 'J'
 SEGUE2_TARGET2 integer,  -- format = 'J'
 MARVELS_TARGET1 integer,  -- format = 'J'
 MARVELS_TARGET2 integer,  -- format = 'J'
 BOSS_TARGET1 bigint,  -- format = 'K'
 BOSS_TARGET2 bigint,  -- format = 'K'
 EBOSS_TARGET0 bigint,  -- format = 'K'
 EBOSS_TARGET1 bigint,  -- format = 'K'
 EBOSS_TARGET2 bigint,  -- format = 'K'
 EBOSS_TARGET_ID bigint,  -- format = 'K'
 ANCILLARY_TARGET1 bigint,  -- format = 'K'
 ANCILLARY_TARGET2 bigint,  -- format = 'K'
 SPECTROGRAPHID smallint,  -- format = 'I'
 PLATE integer,  -- format = 'J'
 TILE integer,  -- format = 'J'
 MJD integer,  -- format = 'J'
 FIBERID integer,  -- format = 'J'
 OBJID text,  -- format = '5J'
 PLUG_RA double precision,  -- format = 'D'
 PLUG_DEC double precision,  -- format = 'D'
 CLASS varchar,  -- format = '6A'
 SUBCLASS varchar,  -- format = '21A'
 Z real,  -- format = 'E'
 Z_ERR real,  -- format = 'E'
 RCHI2 real,  -- format = 'E'
 DOF integer,  -- format = 'J'
 RCHI2DIFF real,  -- format = 'E'
 TFILE varchar,  -- format = '24A'
 TCOLUMN text,  -- format = '10J'
 NPOLY integer,  -- format = 'J'
 THETA text,  -- format = '10E'
 VDISP real,  -- format = 'E'
 VDISP_ERR real,  -- format = 'E'
 VDISPZ real,  -- format = 'E'
 VDISPZ_ERR real,  -- format = 'E'
 VDISPCHI2 real,  -- format = 'E'
 VDISPNPIX real,  -- format = 'E'
 VDISPDOF integer,  -- format = 'J'
 WAVEMIN real,  -- format = 'E'
 WAVEMAX real,  -- format = 'E'
 WCOVERAGE real,  -- format = 'E'
 ZWARNING integer,  -- format = 'J'
 SN_MEDIAN_ALL real,  -- format = 'E'
 SN_MEDIAN text,  -- format = '5E'
 CHI68P real,  -- format = 'E'
 FRACNSIGMA text,  -- format = '10E'
 FRACNSIGHI text,  -- format = '10E'
 FRACNSIGLO text,  -- format = '10E'
 SPECTROFLUX text,  -- format = '5E'
 SPECTROFLUX_IVAR text,  -- format = '5E'
 SPECTROSYNFLUX text,  -- format = '5E'
 SPECTROSYNFLUX_IVAR text,  -- format = '5E'
 SPECTROSKYFLUX text,  -- format = '5E'
 ANYANDMASK integer,  -- format = 'J'
 ANYORMASK integer,  -- format = 'J'
 SPEC1_G real,  -- format = 'E'
 SPEC1_R real,  -- format = 'E'
 SPEC1_I real,  -- format = 'E'
 SPEC2_G real,  -- format = 'E'
 SPEC2_R real,  -- format = 'E'
 SPEC2_I real,  -- format = 'E'
 ELODIE_FILENAME varchar,  -- format = '25A'
 ELODIE_OBJECT varchar,  -- format = '21A'
 ELODIE_SPTYPE varchar,  -- format = '12A'
 ELODIE_BV real,  -- format = 'E'
 ELODIE_TEFF real,  -- format = 'E'
 ELODIE_LOGG real,  -- format = 'E'
 ELODIE_FEH real,  -- format = 'E'
 ELODIE_Z real,  -- format = 'E'
 ELODIE_Z_ERR real,  -- format = 'E'
 ELODIE_Z_MODELERR real,  -- format = 'E'
 ELODIE_RCHI2 real,  -- format = 'E'
 ELODIE_DOF integer,  -- format = 'J'
 Z_NOQSO real,  -- format = 'E'
 Z_ERR_NOQSO real,  -- format = 'E'
 ZWARNING_NOQSO integer,  -- format = 'J'
 CLASS_NOQSO varchar,  -- format = '6A'
 SUBCLASS_NOQSO varchar,  -- format = '21A'
 RCHI2DIFF_NOQSO real,  -- format = 'E'
 Z_PERSON real,  -- format = 'E'
 CLASS_PERSON integer,  -- format = 'J'
 Z_CONF_PERSON integer,  -- format = 'J'
 COMMENTS_PERSON varchar,  -- format = 'A'
 CALIBFLUX text,  -- format = '5E'
 CALIBFLUX_IVAR text  -- format = '5E'
);
