CREATE UNLOGGED TABLE IF NOT EXISTS "catalogdb"."sdss_dr14_qso" (
  "sdss_name" VARCHAR(18),
  "ra" DOUBLE PRECISION,
  "dec" DOUBLE PRECISION,
  "thing_id" INTEGER,
  "plate" SMALLINT,
  "mjd" INTEGER,
  "fiberid" SMALLINT,
  "spectro" VARCHAR(4),
  "z" DOUBLE PRECISION,
  "z_err" DOUBLE PRECISION,
  "source_z" VARCHAR(4),
  "z_vi" DOUBLE PRECISION,
  "z_pipe" DOUBLE PRECISION,
  "z_pipe_err" DOUBLE PRECISION,
  "zwarning" SMALLINT,
  "z_pca" DOUBLE PRECISION,
  "z_pca_er" DOUBLE PRECISION,
  "z_mgii" DOUBLE PRECISION,
  "boss_target1" BIGINT,
  "ancillary_target1" BIGINT,
  "ancillary_target2" BIGINT,
  "eboss_target0" BIGINT,
  "eboss_target1" BIGINT,
  "eboss_target2" BIGINT,
  "n_spec_sdss" SMALLINT,
  "n_spec_boss" SMALLINT,
  "n_spec" SMALLINT,
  "plate_duplicate" INTEGER[],
  "mjd_duplicate" INTEGER[],
  "fiberid_duplicate" INTEGER[],
  "spectro_duplicate" VARCHAR(1)[],
  "bi_civ" DOUBLE PRECISION,
  "err_bi_civ" DOUBLE PRECISION,
  "run_number" SMALLINT,
  "rerun_number" VARCHAR(1),
  "col_number" SMALLINT,
  "field_number" SMALLINT,
  "obj_id" VARCHAR(1),
  "psfflux" DOUBLE PRECISION[],
  "ivar_psfflux" DOUBLE PRECISION[],
  "psfmag" DOUBLE PRECISION[],
  "err_psfmag" DOUBLE PRECISION[],
  "mi" DOUBLE PRECISION,
  "gal_ext" DOUBLE PRECISION[],
  "rass_counts" DOUBLE PRECISION,
  "rass_counts_snr" DOUBLE PRECISION,
  "sdss2rosat_sep" DOUBLE PRECISION,
  "flux_0.2_2.0kev" DOUBLE PRECISION,
  "flux_0.2_2.0kev_err" DOUBLE PRECISION,
  "flux_2.0_12.0kev" DOUBLE PRECISION,
  "flux_2.0_12.0kev_err" DOUBLE PRECISION,
  "flux_0.2_12.0kev" DOUBLE PRECISION,
  "flux_0.2_12.0kev_err" DOUBLE PRECISION,
  "lum_0.2_12.0kev" DOUBLE PRECISION,
  "sdss2xmm_sep" DOUBLE PRECISION,
  "galex_matched" REAL,
  "fuv" DOUBLE PRECISION,
  "fuv_ivar" DOUBLE PRECISION,
  "nuv" DOUBLE PRECISION,
  "nuv_ivar" DOUBLE PRECISION,
  "jmag" DOUBLE PRECISION,
  "err_jmag" DOUBLE PRECISION,
  "jsnr" REAL,
  "jrdflag" SMALLINT,
  "hmag" DOUBLE PRECISION,
  "err_hmag" DOUBLE PRECISION,
  "hsnr" REAL,
  "hrdflag" SMALLINT,
  "kmag" DOUBLE PRECISION,
  "err_kmag" DOUBLE PRECISION,
  "ksnr" REAL,
  "krdflag" SMALLINT,
  "sdss2mass_sep" DOUBLE PRECISION,
  "w1mag" DOUBLE PRECISION,
  "err_w1mag" DOUBLE PRECISION,
  "w1snr" DOUBLE PRECISION,
  "w1chi2" DOUBLE PRECISION,
  "w2mag" DOUBLE PRECISION,
  "err_w2mag" DOUBLE PRECISION,
  "w2snr" DOUBLE PRECISION,
  "w2chi2" DOUBLE PRECISION,
  "w3mag" DOUBLE PRECISION,
  "err_w3mag" DOUBLE PRECISION,
  "w3snr" DOUBLE PRECISION,
  "w3chi2" DOUBLE PRECISION,
  "w4mag" DOUBLE PRECISION,
  "err_w4mag" DOUBLE PRECISION,
  "w4snr" DOUBLE PRECISION,
  "w4chi2" DOUBLE PRECISION,
  "cc_flags" VARCHAR(4),
  "ph_flags" VARCHAR(4),
  "sdss2wise_sep" DOUBLE PRECISION,
  "ukidss_matched" REAL,
  "yflux" DOUBLE PRECISION,
  "yflux_err" DOUBLE PRECISION,
  "jflux" DOUBLE PRECISION,
  "jflux_err" DOUBLE PRECISION,
  "hflux" DOUBLE PRECISION,
  "hflux_err" DOUBLE PRECISION,
  "kflux" DOUBLE PRECISION,
  "kflux_err" DOUBLE PRECISION,
  "first_matched" SMALLINT,
  "first_flux" DOUBLE PRECISION,
  "first_snr" DOUBLE PRECISION,
  "sdss2first_sep" DOUBLE PRECISION
)
