-- The create table statement is based on the information
-- in the HECATE_v1.1.fits file.  

create table catalogdb.hecate_1_1 (
PGC integer,  --  format = 'J ,  --  null = -2147483648
OBJNAME text,  --  format = '30A'
ID_NED text,  --  format = '30A'
ID_NEDD text,  --  format = '29A'
ID_IRAS text,  --  format = '17A'
ID_2MASS text,  --  format = '17A'
SDSS_PHOTID text,  --  format = '19A'
SDSS_SPECID text,  --  format = '19A'
RA double precision,  --  format = 'D ,  --  unit = 'deg'
DEC double precision,  --  format = 'D ,  --  unit = 'deg'
F_ASTROM smallint,  --  format = 'I ,  --  null = -32768
R1 real,  --  format = 'E ,  --  unit = 'arcmin'
R2 real,  --  format = 'E ,  --  unit = 'arcmin'
PA real,  --  format = 'E ,  --  unit = 'deg'
RSOURCE text,  --  format = 'A'
RFLAG smallint,  --  format = 'I ,  --  null = -32768
T real,  --  format = 'E'
E_T real,  --  format = 'E'
INCL real,  --  format = 'E ,  --  unit = 'deg'
V real,  --  format = 'E ,  --  unit = 'km/s'
E_V real,  --  format = 'E ,  --  unit = 'km/s'
V_VIR real,  --  format = 'E ,  --  unit = 'km/s'
E_V_VIR real,  --  format = 'E ,  --  unit = 'km/s'
NDIST smallint,  --  format = 'I ,  --  null = -32768
EDIST smallint,  --  format = 'I ,  --  null = -32768
D double precision,  --  format = 'D ,  --  unit = 'Mpc'
E_D real,  --  format = 'E ,  --  unit = 'Mpc'
D_LO68 double precision,  --  format = 'D ,  --  unit = 'Mpc'
D_HI68 double precision,  --  format = 'D ,  --  unit = 'Mpc'
D_LO95 double precision,  --  format = 'D ,  --  unit = 'Mpc'
D_HI95 double precision,  --  format = 'D ,  --  unit = 'Mpc'
DMETHOD text,  --  format = '2A'
UT real,  --  format = 'E ,  --  unit = 'mag'
BT real,  --  format = 'E ,  --  unit = 'mag'
VT real,  --  format = 'E ,  --  unit = 'mag'
IT real,  --  format = 'E ,  --  unit = 'mag'
E_UT real,  --  format = 'E ,  --  unit = 'mag'
E_BT real,  --  format = 'E ,  --  unit = 'mag'
E_VT real,  --  format = 'E ,  --  unit = 'mag'
E_IT real,  --  format = 'E ,  --  unit = 'mag'
AG real,  --  format = 'E ,  --  unit = 'mag'
AI real,  --  format = 'E ,  --  unit = 'mag'
S12 double precision,  --  format = 'D ,  --  unit = 'Jy'
S25 double precision,  --  format = 'D ,  --  unit = 'Jy'
S60 real,  --  format = 'E ,  --  unit = 'Jy'
S100 real,  --  format = 'E ,  --  unit = 'Jy'
Q12 smallint,  --  format = 'I ,  --  null = -32768
Q25 smallint,  --  format = 'I ,  --  null = -32768
Q60 smallint,  --  format = 'I ,  --  null = -32768
Q100 smallint,  --  format = 'I ,  --  null = -32768
WF1 double precision,  --  format = 'D ,  --  unit = 'mag'
WF2 double precision,  --  format = 'D ,  --  unit = 'mag'
WF3 double precision,  --  format = 'D ,  --  unit = 'mag'
WF4 double precision,  --  format = 'D ,  --  unit = 'mag'
E_WF1 double precision,  --  format = 'D ,  --  unit = 'mag'
E_WF2 double precision,  --  format = 'D ,  --  unit = 'mag'
E_WF3 double precision,  --  format = 'D ,  --  unit = 'mag'
E_WF4 double precision,  --  format = 'D ,  --  unit = 'mag'
WFPOINT smallint,  --  format = 'I ,  --  null = -32768
WFTREAT smallint,  --  format = 'I ,  --  null = -32768
J real,  --  format = 'E ,  --  unit = 'mag'
H real,  --  format = 'E ,  --  unit = 'mag'
K real,  --  format = 'E ,  --  unit = 'mag'
E_J real,  --  format = 'E ,  --  unit = 'mag'
E_H real,  --  format = 'E ,  --  unit = 'mag'
E_K real,  --  format = 'E ,  --  unit = 'mag'
FLAG_2MASS smallint,  --  format = 'I ,  --  null = -32768
U real,  --  format = 'E ,  --  unit = 'mag'
G real,  --  format = 'E ,  --  unit = 'mag'
R real,  --  format = 'E ,  --  unit = 'mag'
I real,  --  format = 'E ,  --  unit = 'mag'
Z real,  --  format = 'E ,  --  unit = 'mag'
E_U real,  --  format = 'E ,  --  unit = 'mag'
E_G real,  --  format = 'E ,  --  unit = 'mag'
E_R real,  --  format = 'E ,  --  unit = 'mag'
E_I real,  --  format = 'E ,  --  unit = 'mag'
E_Z real,  --  format = 'E ,  --  unit = 'mag'
logL_TIR real,  --  format = 'E ,  --  unit = 'log(Lsol)'
logL_FIR real,  --  format = 'E ,  --  unit = 'log(Lsol)'
logL_60u real,  --  format = 'E ,  --  unit = 'log(Lsol)'
logL_12u real,  --  format = 'E ,  --  unit = 'log(Lsol)'
logL_22u real,  --  format = 'E ,  --  unit = 'log(Lsol)'
logL_K real,  --  format = 'E ,  --  unit = 'log(Lsol)'
ML_RATIO real,  --  format = 'E'
logSFR_TIR real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logSFR_FIR real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logSFR_60u real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logSFR_12u real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logSFR_22u real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logSFR_HEC real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
FLAG_SFR_HEC text,  --  format = '2A'
logM_HEC real,  --  format = 'E ,  --  unit = 'log(Msol)'
logSFR_GSW real,  --  format = 'E ,  --  unit = 'log(Msol/yr)'
logM_GSW real,  --  format = 'E ,  --  unit = 'log(Msol)'
MIN_SNR real,  --  format = 'E'
METAL real,  --  format = 'E'
FLAG_METAL smallint,  --  format = 'I ,  --  null = -32768
CLASS_SP smallint,  --  format = 'I ,  --  null = -32768
AGN_S17 text,  --  format = 'A'
AGN_HEC text  --  format = 'A'
);
