/*

APOGEE DRP Visit information

*/

CREATE TABLE apogee_drp.visit (
    PK SERIAL NOT NULL PRIMARY KEY,
    APOGEE_ID	text,
    TARGET_ID	text,
    FILE	text,
    URI         text,
    FIBERID	smallint,
    PLATE	text,
    MJD	integer,
    TELESCOPE	text,
    APRED_VERS  text,
    V_APRED     text,
    SURVEY	text,
    FIELD	text,
    PROGRAMNAME	text,
    OBJTYPE	text,
    ASSIGNED	smallint,
    ON_TARGET	smallint,
    VALID	smallint,
    RA	double precision,
    DEC	double precision,
    GLON	double precision,
    GLAT	double precision,
    JMAG	real,
    JERR	real,
    HMAG	real,
    HERR	real,
    KMAG	real,
    KERR	real,
    SRC_H	text,
    PMRA	real,
    PMDEC	real,
    PM_SRC	text,
    APOGEE_TARGET1	integer,
    APOGEE_TARGET2	integer,
    APOGEE_TARGET3	integer,
    APOGEE_TARGET4	integer,
    CATALOGID		bigint,
    GAIADR2_SOURCEID	bigint,
    GAIADR2_PLX		real,
    GAIADR2_PLX_ERROR	real,
    GAIADR2_PMRA	real,
    GAIADR2_PMRA_ERROR	real,
    GAIADR2_PMDEC	real,
    GAIADR2_PMDEC_ERROR	real,
    GAIADR2_GMAG	real,
    GAIADR2_GERR	real,
    GAIADR2_BPMAG	real,
    GAIADR2_BPERR	real,
    GAIADR2_RPMAG	real,
    GAIADR2_RPERR	real,
    SDSSV_APOGEE_TARGET0	integer,
    FIRSTCARTON			text,
    TARGFLAGS	text,
    SNR	real,
    STARFLAG	integer,
    STARFLAGS	text,
    DATEOBS	text,
    JD	double precision,
    CREATED timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(APRED_VERS,TELESCOPE,PLATE,MJD,FIBERID)
);
