/*

APOGEE DRP Visit information

*/

CREATE TABLE apogee_drp.visit (
    PK SERIAL NOT NULL PRIMARY KEY,
    APOGEE_ID	text,
    TARGET_ID	text,
    FILE	text,
    URI         text,
    FIBERID	smallint,
    PLATE	text,
    EXPTIME	real,
    NFRAMES	integer,
    MJD		integer,
    TELESCOPE	text,
    APRED_VERS  text,
    V_APRED     text,
    SURVEY	text,
    FIELD	text,
    DESIGN      text,
    PROGRAMNAME	text,
    OBJTYPE	text,
    ASSIGNED	smallint,
    ON_TARGET	smallint,
    VALID	smallint,
    RA	double precision,
    DEC	double precision,
    GLON	double precision,
    GLAT	double precision,
    JMAG	real,
    JERR	real,
    HMAG	real,
    HERR	real,
    KMAG	real,
    KERR	real,
    SRC_H	text,
    PMRA	real,
    PMDEC	real,
    PM_SRC	text,
    APOGEE_TARGET1	integer,
    APOGEE_TARGET2	integer,
    APOGEE_TARGET3	integer,
    APOGEE_TARGET4	integer,
    SDSS5_TARGET_CARTON_PKS  text,
    SDSS5_TARGET_CARTONS  text,
    SDSS5_TARGET_FLGAS	  bytea,
    CATALOGID		bigint,
    VERSION_ID          text,
    SDSS_ID		bigint,
    GAIA_RELEASE        text,
    GAIA_SOURCEID	bigint,
    GAIA_PLX		real,
    GAIA_PLX_ERROR	real,
    GAIA_PMRA	        real,
    GAIA_PMRA_ERROR	real,
    GAIA_PMDEC	        real,
    GAIA_PMDEC_ERROR	real,
    GAIA_GMAG	        real,
    GAIA_GERR	        real,
    GAIA_BPMAG	        real,
    GAIA_BPERR	        real,
    GAIA_RPMAG	        real,
    GAIA_RPERR	        real,
    SDSSV_APOGEE_TARGET0	integer,
    FIRSTCARTON			text,
    CADENCE			text,
    PROGRAM			text,
    CATEGORY			text,
    TARGFLAGS	text,
    SNR	real,
    STARFLAG	integer,
    STARFLAGS	text,
    DATEOBS	text,
    JD	double precision,
    CREATED timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(APRED_VERS,TELESCOPE,PLATE,MJD,FIBERID)
);
