/*

APOGEE DRP Visit information

*/

CREATE TABLE apogee_drp.visit (
    PK SERIAL NOT NULL PRIMARY KEY,
    APOGEE_ID	text,
    TARGET_ID	text,
    FILE	text,
    URI         text,
    FIBERID	smallint,
    PLATE	text,
    MJD	integer,
    TELESCOPE	text,
    SURVEY	text,
    FIELD	text,
    PROGRAMNAME	text,
    ALT_ID	text,
    LOCATION_ID	smallint,
    RA	double precision,
    DEC	double precision,
    GLON	double precision,
    GLAT	double precision,
    J	real,
    J_ERR	real,
    H	real,
    H_ERR	real,
    K	real,
    K_ERR	real,
    SRC_H	text,
    WASH_M	real,
    WASH_M_ERR	real,
    WASH_T2	real,
    WASH_T2_ERR	real,
    DDO51	real,
    DDO51_ERR	real,
    IRAC_3_6	real,
    IRAC_3_6_ERR	real,
    IRAC_4_5	real,
    IRAC_4_5_ERR	real,
    IRAC_5_8	real,
    IRAC_5_8_ERR	real,
    IRAC_8_0	real,
    IRAC_8_0_ERR	real,
    WISE_4_5	real,
    WISE_4_5_ERR	real,
    TARG_4_5	real,
    TARG_4_5_ERR	real,
    WASH_DDO51_GIANT_FLAG	smallint,
    WASH_DDO51_STAR_FLAG	smallint,
    PMRA	real,
    PMDEC	real,
    PM_SRC	text,
    AK_TARG	real,
    AK_TARG_METHOD	text,
    AK_WISE	real,
    SFD_EBV	real,
    APOGEE_TARGET1	integer,
    APOGEE_TARGET2	integer,
    APOGEE_TARGET3	integer,
    APOGEE_TARGET4	integer,
    TARGFLAGS	text,
    SNR	real,
    STARFLAG	integer,
    STARFLAGS	text,
    DATEOBS	text,
    JD	double precision,
    BC	real,
    VTYPE	smallint,
    VREL	real,
    VRELERR	real,
    VHELIO	real,
    VLSR	real,
    VGSR	real,
    CHISQ	real,
    RV_TEFF	real,
    RV_FEH	real,
    RV_LOGG	real,
    RV_ALPHA	real,
    RV_CARB	real,
    SYNTHFILE	text,
    APRED_VERS  text,
    MODIFIED timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(APRED_VERS,TELESCOPE,PLATE,MJD,FIBERID)
);
