/*

XMM-Newton Optical Monitor SUSS Catalog, v4.1
https://heasarc.gsfc.nasa.gov/W3Browse/all/xmmomsuob.html

*/

CREATE TABLE catalogdb.xmm_om_suss_4_1 (
    iauname VARCHAR(22),
    n_summary INTEGER,
    obsid VARCHAR(10),
    srcnum INTEGER,
    uvw2_srcdist REAL,
    uvm2_srcdist REAL,
    uvw1_srcdist REAL,
    u_srcdist REAL,
    b_srcdist REAL,
    v_srcdist REAL,
    ra DOUBLE PRECISION,
    dec DOUBLE PRECISION,
    ra_hms VARCHAR(13),
    dec_dms VARCHAR(14),
    poserr REAL,
    lii DOUBLE PRECISION,
    bii DOUBLE PRECISION,
    n_obsid INTEGER,
    uvw2_signif REAL,
    uvm2_signif REAL,
    uvw1_signif REAL,
    u_signif REAL,
    b_signif REAL,
    v_signif REAL,
    uvw2_rate REAL,
    uvw2_rate_err REAL,
    uvm2_rate REAL,
    uvm2_rate_err REAL,
    uvw1_rate REAL,
    uvw1_rate_err REAL,
    u_rate REAL,
    u_rate_err REAL,
    b_rate REAL,
    b_rate_err REAL,
    v_rate REAL,
    v_rate_err REAL,
    uvw2_ab_flux REAL,
    uvw2_ab_flux_err REAL,
    uvm2_ab_flux REAL,
    uvm2_ab_flux_err REAL,
    uvw1_ab_flux REAL,
    uvw1_ab_flux_err REAL,
    u_ab_flux REAL,
    u_ab_flux_err REAL,
    b_ab_flux REAL,
    b_ab_flux_err REAL,
    v_ab_flux REAL,
    v_ab_flux_err REAL,
    uvw2_ab_mag REAL,
    uvw2_ab_mag_err REAL,
    uvm2_ab_mag REAL,
    uvm2_ab_mag_err REAL,
    uvw1_ab_mag REAL,
    uvw1_ab_mag_err REAL,
    u_ab_mag REAL,
    u_ab_mag_err REAL,
    b_ab_mag REAL,
    b_ab_mag_err REAL,
    v_ab_mag REAL,
    v_ab_mag_err REAL,
    uvw2_vega_mag REAL,
    uvw2_vega_mag_err REAL,
    uvm2_vega_mag REAL,
    uvm2_vega_mag_err REAL,
    uvw1_vega_mag REAL,
    uvw1_vega_mag_err REAL,
    u_vega_mag REAL,
    u_vega_mag_err REAL,
    b_vega_mag REAL,
    b_vega_mag_err REAL,
    v_vega_mag REAL,
    v_vega_mag_err REAL,
    uvw2_major_axis REAL,
    uvm2_major_axis REAL,
    uvw1_major_axis REAL,
    u_major_axis REAL,
    b_major_axis REAL,
    v_major_axis REAL,
    uvw2_minor_axis REAL,
    uvm2_minor_axis REAL,
    uvw1_minor_axis REAL,
    u_minor_axis REAL,
    b_minor_axis REAL,
    v_minor_axis REAL,
    uvw2_posang REAL,
    uvm2_posang REAL,
    uvw1_posang REAL,
    u_posang REAL,
    b_posang REAL,
    v_posang REAL,
    uvw2_quality_flag SMALLINT,
    uvm2_quality_flag SMALLINT,
    uvw1_quality_flag SMALLINT,
    u_quality_flag SMALLINT,
    b_quality_flag SMALLINT,
    v_quality_flag SMALLINT,
    uvw2_quality_flag_st VARCHAR(12),
    uvm2_quality_flag_st VARCHAR(12),
    uvw1_quality_flag_st VARCHAR(12),
    u_quality_flag_st VARCHAR(12),
    b_quality_flag_st VARCHAR(12),
    v_quality_flag_st VARCHAR(12),
    uvw2_extended_flag BIGINT,
    uvm2_extended_flag BIGINT,
    uvw1_extended_flag BIGINT,
    u_extended_flag BIGINT,
    b_extended_flag BIGINT,
    v_extended_flag BIGINT,
    uvw2_sky_image VARCHAR(4),
    uvm2_sky_image VARCHAR(4),
    uvw1_sky_image VARCHAR(4),
    u_sky_image VARCHAR(4),
    b_sky_image VARCHAR(4),
    v_sky_image VARCHAR(4)
) WITHOUT OIDS;


\COPY catalogdb.xmm_om_suss_4_1 FROM PROGRAM 'zcat /uufs/chpc.utah.edu/common/home/sdss50/sdsswork/target/catalogs/XMMOMSUOB/XMM-OM-SUSS4.1.csv.gz' WITH CSV HEADER DELIMITER ',';

ALTER TABLE catalogdb.xmm_om_suss_4_1 ADD COLUMN pk BIGSERIAL PRIMARY KEY;

CREATE INDEX CONCURRENTLY ON catalogdb.xmm_om_suss_4_1 (q3c_ang2ipix(ra, dec));
CLUSTER xmm_om_suss_4_1_q3c_ang2ipix_idx on catalogdb.xmm_om_suss_4_1;
VACUUM ANALYZE catalogdb.xmm_om_suss_4_1;
