# -*- coding: utf-8 -*-
#
# BMO documentation build configuration file, created by
# sphinx-quickstart on Fri May  5 01:30:21 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import importlib
import os
import shutil
import warnings

from sdssdb import __version__
from sdssdb.utils.schemadisplay import create_schema_graph


try:
    import peewee
except ImportError:
    peewee = None


# Importing matplotlib here with agg to prevent tkinter error in readthedocs
# import matplotlib
# matplotlib.use('agg')

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.

# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.napoleon",
    "sphinx.ext.autosummary",
    "sphinx.ext.todo",
    "sphinx.ext.viewcode",
    "sphinx.ext.mathjax",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "myst_parser",
    "sphinx_copybutton",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = [".rst", ".md"]
# source_suffix = '.rst'

# source_parsers = {
#     '.md': 'recommonmark.parser.CommonMarkParser',
# }

# The master toctree document.
master_doc = "index"

# General information about the project.
project = "sdssdb"
copyright = "{0}, {1}".format("2018", "SDSS")
author = "José Sánchez-Gallego, Brian Cherinka, et al."

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.

# The full version, including alpha/beta/rc tags.
release = __version__

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The reST default role (used for this markup: `text`) to use for all
# documents.
default_role = "py:obj"

# If true, '()' will be appended to :func: etc. cross-reference text.
# add_function_parentheses = True

# If true, the current module name will be prepended to all description
# unit titles (such as .. function::).
add_module_names = True

# If true, sectionauthor and moduleauthor directives will be shown in the
# output. They are ignored by default.
# show_authors = False

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "lovelace"
pygments_dark_style = "one-dark"

# A list of ignored prefixes for module index sorting.
# modindex_common_prefix = []

# If true, keep warnings as "system message" paragraphs in the built documents.
# keep_warnings = False

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False

# Intersphinx mappings
intersphinx_mapping = {
    "python": ("https://docs.python.org", None),
    "astropy": ("http://docs.astropy.org/en/latest", None),
    "numpy": ("http://docs.scipy.org/doc/numpy/", None),
    "peewee": ("http://docs.peewee-orm.com/en/latest/", None),
    "sqlalchemy": ("https://docs.sqlalchemy.org/en/latest/", None),
}

autodoc_mock_imports = ["_tkinter"]
autodoc_member_order = "groupwise"
autodoc_default_options = {"members": None, "show-inheritance": None}

# napoleon_use_rtype = False
# napoleon_use_ivar = True

simplify_optional_unions = True
typehints_use_signature_return = True

copybutton_prompt_text = r">>> |\$ "
copybutton_prompt_is_regexp = True

rst_epilog = f"""
.. |sdssdb_version| replace:: {__version__}
.. |numpy_array| replace:: Numpy array
"""

releases_github_path = "sdss/sdssdb"
releases_document_name = ["CHANGELOG"]
releases_unstable_prehistory = True


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "furo"
html_title = "GORT's documentation"
html_logo = "_static/sdssv_logo.png"
html_favicon = "./_static/favicon_sdssv.ico"
html_theme_options = {
    "source_repository": "https://github.com/sdss/sdssdb/",
    "source_branch": "main",
    "source_directory": "docs/sphinx",
}

html_sidebars = {}


def generate_schema_graphs():
    """Generates schema graphs for a series of schemas."""

    if not peewee:
        warnings.warn("peewee is not installed. Cannot generate schema graphs.", UserWarning)
        return

    schemas = ["operationsdb.platedb", "operationsdb.mangadb", "operationsdb.apogeeqldb"]

    output_dir = os.path.join(os.path.dirname(__file__), "_static/schema_graphs/auto")

    if os.path.exists(output_dir):
        shutil.rmtree(output_dir)

    os.makedirs(output_dir)

    for schema in schemas:
        __, schema_name = schema.split(".")

        module = importlib.import_module("sdssdb.peewee." + schema)

        models = []
        for attr in dir(module):
            obj = getattr(module, attr)

            if not isinstance(obj, peewee.ModelBase):
                continue

            models.append(obj)

        if len(models) > 0:
            graph = create_schema_graph(models, schema=schema_name)
            graph.write_pdf(os.path.join(output_dir, schema + ".pdf"))


def setup(app):
    # generate_schema_graphs()
    pass
