import psycopg2

# input_dir and output_dir must end with /
input_dir = '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/cadence/'  # noqa: E501

output_dir = '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/cadence/'  # noqa: E501

# csv_file = 'DefaultCadences_v0.5.csv'
csv_file = 'defaultCadences_v1.csv'

f = open(output_dir + csv_file, "r")
num_lines = 0
for line in f:
    num_lines = num_lines + 1
f.close()

print("loading targetdb.cadence from " + output_dir + csv_file)
print("loading " + str(num_lines) + " rows")

label = [""] * num_lines
nepochs = [""] * num_lines
delta = [""] * num_lines
skybrightness = [""] * num_lines
delta_max = [""] * num_lines
delta_min = [""] * num_lines
nexp = [""] * num_lines
max_length = [""] * num_lines
obsmode_pk = [""] * num_lines
label_root = [""] * num_lines
label_version = [""] * num_lines

f = open(output_dir + csv_file, "r")

for i in range(num_lines):
    line = f.readline()
    tags = line.split(";")
    label[i] = tags[0].strip()
    nepochs[i] = tags[1].strip()  # we leave integer nepochs in string form
    delta[i] = tags[2].strip()
    skybrightness[i] = tags[3].strip()
    delta_max[i] = tags[4].strip()
    delta_min[i] = tags[5].strip()
    nexp[i] = tags[6].strip()
    max_length[i] = tags[7].strip()
    obsmode_pk[i] = tags[8].strip()
    label_root[i] = tags[9].strip()
    label_version[i] = tags[10].strip()

f.close()

conn = psycopg2.connect("dbname='sdss5db' user='postgres'")
cursor = conn.cursor()

# label, nepochs, pk, label_root, label_version are not array columns.
# label, label_root, label_version are text, nepochs is integer, pk is bigint.
# Rest of the columns are array columns.
# There are quotes around the data for text columns and for array columns.
# We use upsert below.
# Note we do not insert pk since it is generated by PostgreSQL

for i in range(num_lines):
    label_new = "'" + label[i] + "'"
    nepochs_new = nepochs[i]  # string form of integer so no quotes around it
    delta_new = "'" + delta[i] + "'"
    skybrightness_new = "'" + skybrightness[i] + "'"
    delta_max_new = "'" + delta_max[i] + "'"
    delta_min_new = "'" + delta_min[i] + "'"
    nexp_new = "'" + nexp[i] + "'"
    max_length_new = "'" + max_length[i] + "'"
    obsmode_pk_new = "'" + obsmode_pk[i] + "'"
    label_root_new = "'" + label_root[i] + "'"
    label_version_new = "'" + label_version[i] + "'"

    upsert_statement = "insert into targetdb.cadence " +\
        "(label, nepochs, delta, skybrightness, " +\
        "delta_max, delta_min, nexp, max_length, " +\
        "obsmode_pk, label_root, label_version)" +\
        "values(" +\
        label_new + ", " +\
        nepochs_new + ", " +\
        delta_new + ", " +\
        skybrightness_new + ", " +\
        delta_max_new + ", " +\
        delta_min_new + ", " +\
        nexp_new + ", " +\
        max_length_new + ", " +\
        obsmode_pk_new + ", " +\
        label_root_new + ", " +\
        label_version_new + ") " +\
        "on conflict (label) " +\
        "do update set " +\
        "nepochs = " + nepochs_new + ", " +\
        "delta = " + delta_new + ", " +\
        "skybrightness = " + skybrightness_new + ", " +\
        "delta_max = " + delta_max_new + ", " +\
        "delta_min = " + delta_min_new + ", " +\
        "nexp = " + nexp_new + ", " +\
        "max_length = " + max_length_new + ", " +\
        "obsmode_pk = " + obsmode_pk_new + ", " +\
        "label_root = " + label_root_new + ", " +\
        "label_version = " + label_version_new

    # print("executing " + upsert_statement)
    cursor.execute(upsert_statement)

conn.commit()
conn.close()
