\o sdss_dr19p_speclite_create_table.out

CREATE TABLE catalogdb.sdss_dr19p_speclite (
  plate INTEGER,
  mjd INTEGER,
  fiberid INTEGER,
  field INTEGER,
  catalogid BIGINT,
  specobjid numeric(20,0),
  bestobjid BIGINT,
  targetobjid BIGINT,
  run2d TEXT,
  run1d TEXT,
  firstrelease TEXT,
  plug_ra double precision,
  plug_dec double precision,
  sourcetype TEXT,
  objtype TEXT,
  targettype TEXT,
  lambda_eff REAL,
  sn_median_all REAL,
  sn_median_u REAL,
  sn_median_g REAL, 
  sn_median_r REAL, 
  sn_median_i REAL, 
  sn_median_z REAL,
  platesn2 REAL,
  platequality TEXT,
  z REAL,
  z_err REAL,
  zwarning INTEGER,
  zwarning_noqso INTEGER,
  class TEXT,
  subclass TEXT,
  tfile TEXT,
  specprimary INTEGER,
  nspecobs INTEGER
);
