-- The create table statement is based on 
-- the column names in the SuperCOSMOS README and 
-- the column types in readSSABinary.py
--
-- The below link has more details
-- http://ssa.roe.ac.uk/www/SSA_TABLE_SourceSchema.html#Source

create table catalogdb.supercosmos(
objID bigint,
objIDB bigint,
objIDR1 bigint,
objIDR2 bigint,
objIDI bigint,
htmId bigint,
epoch real,
ra double precision,
dec double precision,
sigRA double precision,
sigDec double precision,
cx double precision,
cy double precision,
cz double precision,
muAcosD real,
muD real,
sigMuAcosD real,
sigMuD real,
chi2 real,
Nplates smallint,
classMagB real,
classMagR1 real,
classMagR2 real,
classMagI real,
gCorMagB real,
gCorMagR1 real,
gCorMagR2 real,
gCorMagI real,
sCorMagB real,
sCorMagR1 real,
sCorMagR2 real,
sCorMagI real,
meanClass smallint,
classB smallint,
classR1 smallint,
classR2 smallint,
classI smallint,
ellipB real,
ellipR1 real,
ellipR2 real,
ellipI real,
qualB integer,
qualR1 integer,
qualR2 integer,
qualI integer,
blendB integer,
blendR1 integer,
blendR2 integer,
blendI integer,
prfStatB real,
prfStatR1 real,
prfStatR2 real,
prfStatI real,
l real,
b real,
d real,
Ebmv real
);
