CREATE ROLE sdss LOGIN;
CREATE ROLE sdssuser WITH CREATEDB CREATEROLE LOGIN REPLICATION;
CREATE USER u0707758 IN ROLE sdssuser; --- Joel
CREATE USER u0449727 IN ROLE sdssuser; --- Conor
CREATE USER u0931042 IN ROLE sdssuser; --- Jose

CREATE DATABASE sdss5db OWNER sdss ENCODING 'UTF8' LC_COLLATE='en_US.UTF-8' LC_CTYPE='en_US.UTF-8' TEMPLATE template0;
CREATE SCHEMA catalogdb AUTHORIZATION sdss;
CREATE SCHEMA targetdb AUTHORIZATION sdss;

