-- The create table statement is based on the information in the below link:
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_main_source_catalogue/ssec_dm_gaia_source.html

create table catalogdb.gaia_dr3_source (
solution_id bigint, -- Solution Identifier (long)
designation text, -- Unique source designation (unique across all Data Releases) (string)
source_id bigint, -- Unique source identifier (unique within a particular Data Release) (long)
random_index bigint, -- Random index for use when selecting subsets (long)
ref_epoch double precision, -- Reference epoch (double, Time[Julian Years])
ra double precision, -- Right ascension (double, Angle[deg])
ra_error real, -- Standard error of right ascension (float, Angle[mas])
dec double precision, -- Declination (double, Angle[deg])
dec_error real, -- Standard error of declination (float, Angle[mas])
parallax double precision, -- Parallax (double, Angle[mas] )
parallax_error real, -- Standard error of parallax (float, Angle[mas] )
parallax_over_error real, -- Parallax divided by its standard error (float)
pm real, -- Total proper motion (float, Angular Velocity[mas yr−1
pmra double precision, -- Proper motion in right ascension direction (double, Angular Velocity[mas yr−1
pmra_error real, -- Standard error of proper motion in right ascension direction (float, Angular Velocity[mas yr−1
pmdec double precision, -- Proper motion in declination direction (double, Angular Velocity[mas yr−1
pmdec_error real, -- Standard error of proper motion in declination direction (float, Angular Velocity[mas yr−1
ra_dec_corr real, -- Correlation between right ascension and declination (float)
ra_parallax_corr real, -- Correlation between right ascension and parallax (float)
ra_pmra_corr real, -- Correlation between right ascension and proper motion in right ascension (float)
ra_pmdec_corr real, -- Correlation between right ascension and proper motion in declination (float)
dec_parallax_corr real, -- Correlation between declination and parallax (float)
dec_pmra_corr real, -- Correlation between declination and proper motion in right ascension (float)
dec_pmdec_corr real, -- Correlation between declination and proper motion in declination (float)
parallax_pmra_corr real, -- Correlation between parallax and proper motion in right ascension (float)
parallax_pmdec_corr real, -- Correlation between parallax and proper motion in declination (float)
pmra_pmdec_corr real, -- Correlation between proper motion in right ascension and proper motion in declination (float)
astrometric_n_obs_al smallint, -- Total number of observations in the along-scan (AL) direction (short)
astrometric_n_obs_ac smallint, -- Total number of observations in the across-scan (AC) direction (short)
astrometric_n_good_obs_al smallint, -- Number of good observations in the along-scan (AL) direction (short)
astrometric_n_bad_obs_al smallint, -- Number of bad observations in the along-scan (AL) direction (short)
astrometric_gof_al real, -- Goodness of fit statistic of model wrt along-scan observations (float)
astrometric_chi2_al real, -- AL chi-square value (float)
astrometric_excess_noise real, -- Excess noise of the source (float, Angle[mas])
astrometric_excess_noise_sig real, -- Significance of excess noise (float)
astrometric_params_solved smallint, -- Which parameters have been solved for? (byte)
astrometric_primary_flag boolean, -- Primary or seconday (boolean)
nu_eff_used_in_astrometry real, -- Effective wavenumber of the source used in the astrometric solution (float, Misc[𝜇𝑚−1
pseudocolour real, -- Astrometrically estimated pseudocolour of the source (float, Misc[𝜇𝑚−1
pseudocolour_error real, -- Standard error of the pseudocolour of the source (float, Misc[𝜇𝑚−1
ra_pseudocolour_corr real, -- Correlation between right ascension and pseudocolour (float)
dec_pseudocolour_corr real, -- Correlation between declination and pseudocolour (float)
parallax_pseudocolour_corr real, -- Correlation between parallax and pseudocolour (float)
pmra_pseudocolour_corr real, -- Correlation between proper motion in right asension and pseudocolour (float)
pmdec_pseudocolour_corr real, -- Correlation between proper motion in declination and pseudocolour (float)
astrometric_matched_transits smallint, -- Matched FOV transits used in the AGIS solution (short)
visibility_periods_used smallint, -- Number of visibility periods used in Astrometric solution (short)
astrometric_sigma5d_max real, -- The longest semi-major axis of the 5-d error ellipsoid (float, Angle[mas])
matched_transits smallint, -- The number of transits matched to this source (short)
new_matched_transits smallint, -- The number of transits newly incorporated into an existing source in the current cycle (short)
matched_transits_removed smallint, -- The number of transits removed from an existing source in the current cycle (short)
ipd_gof_harmonic_amplitude real, -- Amplitude of the IPD GoF versus position angle of scan (float)
ipd_gof_harmonic_phase real, -- Phase of the IPD GoF versus position angle of scan (float, Angle[deg])
ipd_frac_multi_peak smallint, -- Percent of successful-IPD windows with more than one peak (byte)
ipd_frac_odd_win smallint, -- Percent of transits with truncated windows or multiple gate (byte)
ruwe real, -- Renormalised unit weight error (float)
scan_direction_strength_k1 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k2 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k3 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k4 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_mean_k1 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k2 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k3 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k4 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
duplicated_source boolean, -- Source with multiple source identifiers (boolean)
phot_g_n_obs smallint, -- Number of observations contributing to G photometry (short)
phot_g_mean_flux double precision, -- G-band mean flux (double, Flux[e−
phot_g_mean_flux_error real, -- Error on G-band mean flux (float, Flux[e−
phot_g_mean_flux_over_error real, -- G-band mean flux divided by its error (float)
phot_g_mean_mag real, -- G-band mean magnitude (float, Magnitude[mag])
phot_bp_n_obs smallint, -- Number of observations contributing to BP photometry (short)
phot_bp_mean_flux double precision, -- Integrated BP mean flux (double, Flux[e−
phot_bp_mean_flux_error real, -- Error on the integrated BP mean flux (float, Flux[e−
phot_bp_mean_flux_over_error real, -- Integrated BP mean flux divided by its error (float)
phot_bp_mean_mag real, -- Integrated BP mean magnitude (float, Magnitude[mag])
phot_rp_n_obs smallint, -- Number of observations contributing to RP photometry (short)
phot_rp_mean_flux double precision, -- Integrated RP mean flux (double, Flux[e−
phot_rp_mean_flux_error real, -- Error on the integrated RP mean flux (float, Flux[e−
phot_rp_mean_flux_over_error real, -- Integrated RP mean flux divided by its error (float)
phot_rp_mean_mag real, -- Integrated RP mean magnitude (float, Magnitude[mag])
phot_bp_rp_excess_factor real, -- BP/RP excess factor (float)
phot_bp_n_contaminated_transits smallint, -- Number of BP contaminated transits (short)
phot_bp_n_blended_transits smallint, -- Number of BP blended transits (short)
phot_rp_n_contaminated_transits smallint, -- Number of RP contaminated transits (short)
phot_rp_n_blended_transits smallint, -- Number of RP blended transits (short)
phot_proc_mode smallint, -- Photometry processing mode (byte)
bp_rp real, -- BP - RP colour (float, Magnitude[mag])
bp_g real, -- BP - G colour (float, Magnitude[mag])
g_rp real, -- G - RP colour (float, Magnitude[mag])
radial_velocity real, -- Radial velocity (float, Velocity[km s−1
radial_velocity_error real, -- Radial velocity error (float, Velocity[km s−1
rv_method_used smallint, -- Method used to obtain the radial velocity (byte)
rv_nb_transits smallint, -- Number of transits used to compute the radial velocity (short)
rv_nb_deblended_transits smallint, -- Number of valid transits that have undergone deblending (short)
rv_visibility_periods_used smallint, -- Number of visibility periods used to estimate the radial velocity (short)
rv_expected_sig_to_noise real, -- Expected signal to noise ratio in the combination of the spectra used to obtain the radial velocity (float)
rv_renormalised_gof real, -- Radial velocity renormalised goodness of fit (float)
rv_chisq_pvalue real, -- P-value for constancy based on a chi-squared criterion (float)
rv_time_duration real, -- Time coverage of the radial velocity time series (float, Time[day])
rv_amplitude_robust real, -- Total amplitude in the radial velocity time series after outlier removal (float, Velocity[km s−1
rv_template_teff real, -- Teff of the template used to compute the radial velocity (float, Temperature[K])
rv_template_logg real, -- Logg of the template used to compute the radial velocity (float, GravitySurface[log cgs])
rv_template_fe_h real, -- [Fe/H] of the template used to compute the radial velocityy (float, Abundances[dex])
rv_atm_param_origin smallint, -- Origin of the atmospheric parameters associated to the template (short)
vbroad real, -- Spectral line broadening parameter (float, Velocity[km s−1
vbroad_error real, -- Uncertainty on the spectral line broadening (float, Velocity[km s−1
vbroad_nb_transits smallint, -- Number of transits used to compute vbroad (short)
grvs_mag real, -- Integrated Grvs magnitude (float, Magnitude[mag])
grvs_mag_error real, -- Grvs magnitude uncertainty (float, Magnitude[mag])
grvs_mag_nb_transits smallint, -- Number of transits used to compute Grvs (short)
rvs_spec_sig_to_noise real, -- Signal to noise ratio in the mean RVS spectrum (float)
phot_variable_flag text, -- Photometric variability flag (string)
l double precision, -- Galactic longitude (double, Angle[deg])
b double precision, -- Galactic latitude (double, Angle[deg])
ecl_lon double precision, -- Ecliptic longitude (double, Angle[deg])
ecl_lat double precision, -- Ecliptic latitude (double, Angle[deg])
in_qso_candidates boolean, -- Flag indicating the availability of additional information in the QSO candidates table (boolean)
in_galaxy_candidates boolean, -- Flag indicating the availability of additional information in the galaxy candidates table (boolean)
non_single_star smallint, -- Flag indicating the availability of additional information in the various Non-Single Star tables (short)
has_xp_continuous boolean, -- Flag indicating the availability of mean BP/RP spectrum in continuous representation for this source (boolean)
has_xp_sampled boolean, -- Flag indicating the availability of mean BP/RP spectrum in sampled form for this source (boolean)
has_rvs boolean, -- Flag indicating the availability of mean RVS spectrum for this source (boolean)
has_epoch_photometry boolean, -- Flag indicating the availability of epoch photometry for this source (boolean)
has_epoch_rv boolean, -- Flag indicating the availability of epoch radial velocity for this source (boolean)
has_mcmc_gspphot boolean, -- Flag indicating the availability of GSP-Phot MCMC samples for this source (boolean)
has_mcmc_msc boolean, -- Flag indicating the availability of MSC MCMC samples for this source (boolean)
in_andromeda_survey boolean, -- Flag indicating that the source is present in the Gaia Andromeda Photometric Survey (GAPS) (boolean)
classprob_dsc_combmod_quasar float, -- Probability from DSC-Combmod of being a quasar (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_galaxy float, -- Probability from DSC-Combmod of being a galaxy (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_star float, -- Probability from DSC-Combmod of being a single star (but not a white dwarf) (data used: BP/RP spectrum, photometry, astrometry) (float)
teff_gspphot float, -- Effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
teff_gspphot_lower float, -- Lower confidence level (16%) of effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
teff_gspphot_upper float, -- Upper confidence level (84%) of effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
logg_gspphot float, -- Surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
logg_gspphot_lower float, -- Lower confidence level (16%) of surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
logg_gspphot_upper float, -- Upper confidence level (84%) of surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
mh_gspphot float, -- Iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
mh_gspphot_lower float, -- Lower confidence level (16%) of iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
mh_gspphot_upper float, -- Upper confidence level (84%) of iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
distance_gspphot float, -- Distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
distance_gspphot_lower float, -- Lower confidence level (16%) of distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
distance_gspphot_upper float, -- Upper confidence level (84%) of distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
azero_gspphot float, -- Monochromatic extinction 𝐴0
azero_gspphot_lower float, -- Lower confidence level (16%) of monochromatic extinction 𝐴0
azero_gspphot_upper float, -- Upper confidence level (84%) of monochromatic extinction 𝐴0
ag_gspphot float, -- Extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ag_gspphot_lower float, -- Lower confidence level (16%) of extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ag_gspphot_upper float, -- Upper confidence level (84%) of extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ebpminrp_gspphot float, -- Reddening 𝐸(𝐺BP−𝐺RP)
ebpminrp_gspphot_lower float, -- Lower confidence level (16%) of reddening 𝐸(𝐺BP−𝐺RP)
ebpminrp_gspphot_upper float, -- Upper confidence level (84%) of reddening 𝐸(𝐺BP−𝐺RP)
libname_gspphot text -- Name of library that achieves the highest mean log-posterior in MCMC samples and was used to derive GSP-Phot parameters in this table (string)
);