create table catalogdb.mwsall_fibermap(
targetid bigint,
coadd_fiberstatus integer,
target_ra double precision,
target_dec double precision,
pmra real,
pmdec real,
ref_epoch real,
fa_target bigint,
fa_type smallint,
objtype text,
subpriority double precision,
obsconditions integer,
release smallint,
brickname text,
brickid integer,
brick_objid integer,
morphtype text,
ebv real,
flux_g real,
flux_r real,
flux_z real,
flux_w1 real,
flux_w2 real,
flux_ivar_g real,
flux_ivar_r real,
flux_ivar_z real,
flux_ivar_w1 real,
flux_ivar_w2 real,
fiberflux_g real,
fiberflux_r real,
fiberflux_z real,
fibertotflux_g real,
fibertotflux_r real,
fibertotflux_z real,
maskbits smallint,
sersic real,
shape_r real,
shape_e1 real,
shape_e2 real,
ref_id bigint,
ref_cat text,
gaia_phot_g_mean_mag real,
gaia_phot_bp_mean_mag real,
gaia_phot_rp_mean_mag real,
parallax real,
photsys text,
priority_init bigint,
numobs_init bigint,
cmx_target bigint,
desi_target bigint,
bgs_target bigint,
mws_target bigint,
plate_ra double precision,
plate_dec double precision,
coadd_numexp smallint,
coadd_exptime real,
coadd_numnight smallint,
coadd_numtile smallint,
mean_delta_x real,
rms_delta_x real,
mean_delta_y real,
rms_delta_y real,
mean_fiber_ra double precision,
std_fiber_ra real,
mean_fiber_dec double precision,
std_fiber_dec real,
mean_psf_to_fiber_specflux real,
scnd_target bigint,
sv1_desi_target bigint,
sv1_bgs_target bigint,
sv1_mws_target bigint,
sv1_scnd_target bigint,
sv2_desi_target bigint,
sv2_bgs_target bigint,
sv2_mws_target bigint,
sv2_scnd_target bigint,
sv3_desi_target bigint,
sv3_bgs_target bigint,
sv3_mws_target bigint,
sv3_scnd_target bigint
);
