create table catalogdb.mwsall_rvtab(
vrad double precision,
vrad_err double precision,
vrad_skew double precision,
vrad_kurt double precision,
logg double precision,
teff double precision,
alphafe double precision,
feh double precision,
logg_err double precision,
teff_err double precision,
alphafe_err double precision,
feh_err double precision,
vsini double precision,
chisq_tot double precision,
chisq_c_tot double precision,
chisq_b double precision,
chisq_c_b double precision,
chisq_r double precision,
chisq_c_r double precision,
chisq_z double precision,
chisq_c_z double precision,
rvs_warn bigint,
ref_id bigint,
ref_cat text,
target_ra double precision,
target_dec double precision,
targetid bigint,
sn_b real,
sn_r real,
sn_z real,
success boolean,
rr_z double precision,
rr_spectype text,
healpix bigint,
survey text,
program text,
is_primary boolean 
);
-- For the last column, we use the name "is_primary"
-- instead of "primary" since "primary" is a SQL keyword
