/*

schema for tess:

https://archive.stsci.edu/missions/tess/catalogs/tic_v6/tic_column_description.txt

*/

CREATE TABLE catalogdb.tess_input_v6 (
    ID bigint,
    version text,
    HIP integer,
    TYC text,
    UCAC text,
    TWOMASS text,
    SDSS bigint,
    ALLWISE text,
    GAIA text,
    APASS text,
    KIC integer,
    objType text,
    typeSrc text,
    ra double precision,
    dec double precision,
    POSflag text,
    pmRA real,
    e_pmRA real,
    pmDEC real,
    e_pmDEC real,
    PMflag text,
    plx real,
    e_plx real,
    PARflag text,
    gallong double precision,
    gallat double precision,
    eclong double precision,
    eclat double precision,
    Bmag real,
    e_Bmag real,
    Vmag real,
    e_Vmag real,
    umag real,
    e_umag real,
    gmag real,
    e_gmag real,
    rmag real,
    e_rmag real,
    imag real,
    e_imag real,
    zmag real,
    e_zmag real,
    Jmag real,
    e_Jmag real,
    Hmag real,
    e_Hmag real,
    Kmag real,
    e_Kmag real,
    TWOMflag text,
    prox real,
    w1mag real,
    e_w1mag real,
    w2mag real,
    e_w2mag real,
    w3mag real,
    e_w3mag real,
    w4mag real,
    e_w4mag real,
    GAIAmag real,
    e_GAIAmag real,
    Tmag real,
    e_Tmag real,
    TESSflag text,
    SPFlag text,
    Teff real,
    e_Teff real,
    logg real,
    e_logg real,
    MH real,
    e_MH real,
    rad real,
    e_rad real,
    mass real,
    e_mass real,
    rho real,
    e_rho real,
    lumclass text,
    lum real,
    e_lum real,
    d real,
    e_d real,
    ebv real,
    e_ebv real,
    numcont integer,
    contratio real,
    disposition text,
    duplicate_i bigint,
    priority real,
    objID bigint
);
