/*

APOGEE DRP Star information

*/

CREATE TABLE apogee_drp.star (
    PK SERIAL NOT NULL PRIMARY KEY,
    APOGEE_ID	text,
    FILE	text,
    URI         text,
    STARVER     text,
    MJDBEG      integer,
    MJDEND	integer,
    TELESCOPE	text,
    APRED_VERS  text,
    V_APRED     text,
    HEALPIX	integer,
    SNR	real,
    RA	double precision,
    DEC	double precision,
    GLON	double precision,
    GLAT	double precision,
    JMAG	real,
    JERR	real,
    HMAG	real,
    HERR	real,
    KMAG	real,
    KERR	real,
    SRC_H	text,
    TARG_PMRA	real,
    TARG_PMDEC	real,
    TARG_PM_SRC	text,
    APOGEE_TARGET1	integer,
    APOGEE_TARGET2	integer,
    APOGEE2_TARGET1	integer,
    APOGEE2_TARGET2	integer,
    APOGEE2_TARGET3	integer,
    APOGEE2_TARGET4	integer,
    SDSS5_TARGET_CARTON_PKS  text,
    SDSS5_TARGET_CARTONS  text,
    SDSS5_TARGET_FLAGSHEX  text,
    CATALOGID		bigint,
    VERSION_ID          text,
    SDSS_ID             bigint,
    RA_SDSS_ID          double precision,
    DEC_SDSS_ID         double precision,
    GAIA_RELEASE        text,
    GAIA_SOURCEID	bigint,
    GAIA_PLX		real,
    GAIA_PLX_ERROR	real,
    GAIA_PMRA	real,
    GAIA_PMRA_ERROR	real,
    GAIA_PMDEC	real,
    GAIA_PMDEC_ERROR	real,
    GAIA_GMAG	real,
    GAIA_GERR	real,
    GAIA_BPMAG	real,
    GAIA_BPERR	real,
    GAIA_RPMAG	real,
    GAIA_RPERR	real,
    SDSSV_APOGEE_TARGET0	integer,
    FIRSTCARTON		text,
    CADENCE		text,
    PROGRAM		text,
    CATEGORY		text,
    TARGFLAGS		text,
    NVISITS		integer,
    NGOODVISITS		integer,
    NGOODRVS		integer,
    STARFLAG	integer,
    STARFLAGS	text,
    ANDFLAG	integer,
    ANDFLAGS	text,
    VRAD	real,
    VSCATTER	real,
    VERR	real,
    VMEDERR	real,
    CHISQ	real,
    RV_TEFF	real,
    RV_TEFFERR	real,
    RV_LOGG	real,
    RV_LOGGERR	real,
    RV_FEH	real,
    RV_FEHERR	real,
    RV_CCPFWHM	real,
    RV_AUTOFWHM	real,
    N_COMPONENTS	integer,
    MEANFIB	real,
    SIGFIB	real,
    NRES	text,
    CREATED timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(APRED_VERS,TELESCOPE,APOGEE_ID,STARVER)
);
