/*

APOGEE DRP Star information

*/

CREATE TABLE apogee_drp.star (
    PK SERIAL NOT NULL PRIMARY KEY,
    APOGEE_ID	text,
    FILE	text,
    URI         text,
    STARVER     text,
    MJDBEG      integer,
    MJDEND	integer,
    TELESCOPE	text,
    APRED_VERS  text,
    HEALPIX	integer,
    SNR	real,
    RA	double precision,
    DEC	double precision,
    GLON	double precision,
    GLAT	double precision,
    JMAG	real,
    JERR	real,
    HMAG	real,
    HERR	real,
    KMAG	real,
    KERR	real,
    SRC_H	text,
    APOGEE_TARGET1	integer,
    APOGEE_TARGET2	integer,
    APOGEE_TARGET3	integer,
    APOGEE2_TARGET1	integer,
    APOGEE2_TARGET2	integer,
    APOGEE2_TARGET3	integer,
    APOGEE2_TARGET4	integer,
    CATALOGID		bigint,
    GAIADR2_PLX		real,
    GAIADR2_PLX_ERROR	real,
    GAIADR2_PMRA	real,
    GAIADR2_PMRA_ERROR	real,
    GAIADR2_PMDEC	real,
    GAIADR2_PMDEC_ERROR	real,
    GAIADR2_GMAG	real,
    GAIADR2_GERR	real,
    GAIADR2_BPMAG	real,
    GAIADR2_BPERR	real,
    GAIADR2_RPMAG	real,
    GAIADR2_RPERR	real,
    SDSSV_APOGEE_TARGET0	integer,
    FIRSTCARTON		text,
    NVISITS		integer,
    STARFLAG	integer,
    ANDFLAG	integer,
    N_COMPONENTS	integer,
    VHELIOBARY	real,
    VSCATTER	real,
    VERR	real,
    RV_TEFF	real,
    RV_FEH	real,
    RV_LOGG	real,
    MEANFIB	real,
    SIGFIB	real,
    NRES	text,
    CREATED timestamp with time zone DEFAULT now() NOT NULL,
    UNIQUE(APRED_VERS,TELESCOPE,APOGEE_ID,STARVER)
);
