CREATE INDEX CONCURRENTLY ON apogee_drp.ap3d USING BTREE (instrument);
CREATE INDEX CONCURRENTLY ON apogee_drp.ap3d USING BTREE (telescope);
CREATE INDEX CONCURRENTLY ON apogee_drp.ap3d USING BTREE (mjd);
CREATE INDEX CONCURRENTLY ON apogee_drp.ap3d USING BTREE (plate);
CREATE INDEX CONCURRENTLY ON apogee_drp.ap3d USING BTREE (num);


