-- The create table statement is based on the below link.
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_non--single_stars_tables/ssec_dm_nss_two_body_orbit.html

create table catalogdb.gaia_dr3_nss_two_body_orbit (
solution_id bigint,  -- Solution Identifier (long)       
source_id bigint,  -- Source Identifier (long)
nss_solution_type text,  -- NSS model adopted (string)
ra double precision,  -- Right ascension (double, Angle[deg])
ra_error real,  -- Standard error of right ascension (float, Angle[mas])
dec double precision,  -- Declination (double, Angle[deg])
dec_error real,  -- Standard error of declination (float, Angle[mas])
parallax double precision,  -- Parallax (double, Angle[mas] )
parallax_error real,  -- Standard error of parallax (float, Angle[mas] )
pmra double precision,  -- Proper motion in right ascension direction (double, Angular Velocity[mas yr−1])
pmra_error real,  -- Standard error of proper motion in right ascension direction (float, Angular Velocity[mas yr−1] )
pmdec double precision,  -- Proper motion in declination direction (double, Angular Velocity[mas yr−1] )
pmdec_error real,  -- Standard error of proper motion in declination direction (float, Angular Velocity[mas yr−1] )
a_thiele_innes double precision,  -- Thiele-Innes element A (double, Angle[mas] )
a_thiele_innes_error real,  -- Standard error of Thiele-Innes element A (float, Angle[mas] )
b_thiele_innes double precision,  -- Thiele-Innes element B (double, Angle[mas] )
b_thiele_innes_error real,  -- Standard error of Thiele-Innes element B (float, Angle[mas] )
f_thiele_innes double precision,  -- Thiele-Innes element F (double, Angle[mas] )
f_thiele_innes_error real,  -- Standard error of Thiele-Innes element F (float, Angle[mas] )
g_thiele_innes double precision,  -- Thiele-Innes element G (double, Angle[mas] )
g_thiele_innes_error real,  -- Standard error of Thiele-Innes element G (float, Angle[mas])
c_thiele_innes double precision,  -- C element of Thiele-Innes (double, Length & Distance[AU])
c_thiele_innes_error real,  -- Standard error of C element of Thiele-Innes (float, Length & Distance[AU])
h_thiele_innes double precision,  -- H element of Thiele-Innes (double, Length & Distance[AU])
h_thiele_innes_error real,  -- Standard error of H element of Thiele-Innes (float, Length & Distance[AU])
period double precision,  -- Orbital Period (double, Time[day])
period_error real,  -- Standard error of Orbital Period (float, Time[day])
t_periastron double precision,  -- Periastron epoch (double, Time[day])
t_periastron_error real,  -- Standard error of Periastron epoch (float, Time[day])
eccentricity double precision,  -- eccentricity (double)
eccentricity_error real,  -- Standard error of eccentricity (float)
center_of_mass_velocity double precision,  -- The velocity of the centre of mass (double, Velocity[km s−1])
center_of_mass_velocity_error real,  -- Standard error of The velocity of the centre of mass (float, Velocity[km s−1])
semi_amplitude_primary double precision,  -- Semi-amplitude of the centre of mass (double, Velocity[km s−1])
semi_amplitude_primary_error real,  -- Standard error of Semi-amplitude of the centre of mass (float, Velocity[km s−1])
semi_amplitude_secondary double precision,  -- The semiamplitude of the radial velocity curve for second component (double, Velocity[km s−1] )
semi_amplitude_secondary_error real,  -- Standard error of The semiamplitude of the radial velocity curve for second component (float, Velocity[km s−1] )
mass_ratio double precision,  -- Mass ratio (double)
mass_ratio_error real,  -- Standard error of Mass ratio (float)
fill_factor_primary double precision,  -- Fill factor of primary (double)
fill_factor_primary_error real,  -- Standard error of Fill factor of primary (float)
fill_factor_secondary double precision,  -- Fill factor of secondary (double)
fill_factor_secondary_error real,  -- Standard error of Fill factor of secondary (float)
inclination double precision,  -- Orbital inclination (double, Angle[deg])
inclination_error real,  -- Standard error of Orbital inclination (float, Angle[deg])
arg_periastron double precision,  -- Argument of periastron (double, Angle[deg])
arg_periastron_error real,  -- Standard error of Argument of periastron (float, Angle[deg])
temperature_ratio double precision,  -- Ratio of the effective temperatures (double)
temperature_ratio_error real,  -- Standard error of the ratio of the effective temperatures (double)
temperature_ratio_definition smallint,  -- Code defining which fitting scenario did apply to the effective temperature (byte)
astrometric_n_obs_al integer,  -- Total astrometric CCD observations in AL considered (int)
astrometric_n_good_obs_al integer,  -- Total astrometric CCD observations in AL actually used (int)
rv_n_obs_primary integer,  -- Total number of radial velocities considered for the primary (int)
rv_n_good_obs_primary integer,  -- Total number of radial velocities actually used for the primary (int)
rv_n_obs_secondary integer,  -- Total number of radial velocities considered for the secondary in the case of SB2 (int)
rv_n_good_obs_secondary integer,  -- Total number of radial velocities actually used for the secondary in the case of SB2 (int)
phot_g_n_obs integer,  -- Total number of G photometry measurements considered (int)
phot_g_n_good_obs integer,  -- Total number of G photometry measurements actually used (int)
bit_index bigint,  -- boolean mask for the fields above in the corr_vec matrix (long) 
corr_vec text,  -- Vector form of the upper triangle of the correlation matrix (column-major ordered) (float[231] array) array corresponds to text
obj_func real,  -- value of the objective function at the solution (float)
goodness_of_fit real,  -- goodness of fit in the Hipparcos sense (float)
efficiency real,  -- Efficiency of the solution (float)
significance real,  -- The significance of the solution (i.e. how worth keeping a model is) (float)
flags bigint,  -- Quality flag for the achieved NSS solution (long)
conf_spectro_period real,  -- The probability of the period for not being due to (gaussian white) noise. Relevant for SB1, SB1C, SB2 and SB2C models. To be ignored otherwise. (float)
r_pole_sum double precision,  -- Sum of the polar radii of primary and secondary (in units of the semi-major axis) (double)
r_l1_point_sum double precision,  -- L1-pointing radii of primary and secondary (in units of the semi-major axis) (double)
r_spher_sum double precision,  -- Sum of the radii of sphere having the same volume as the primary and secondary (in units of the semi-major axis (double)
ecl_time_primary double precision,  -- Time of mid-eclipse of the primary by the secondary (double, Time[Julian Date (day)])
ecl_time_secondary double precision,  -- Time of mid-eclipse of the secondary by the primary (double, Time[Julian Date (day)])
ecl_dur_primary double precision,  -- Duration of primary eclipse assuming spherical components (double, Time[day])
ecl_dur_secondary double precision,  -- Duration of secondary eclipse assuming spherical components (double, Time[day])
g_luminosity_ratio double precision,  -- Ratio of the G-band luminosity of the secondary over the primary (double)
input_period_error real,  -- Standard error of the period taken from vari_eclipsing_binary.frequency_error (float, Time[day])
g_rank double precision,  -- Rank of the G-band solution (double)
astrometric_jitter double precision  -- Uncorrelated astrometric jitter term (double, Angle[mas])
);
