-- This create table statements is based on the below link.
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_extra--galactic_tables/ssec_dm_qso_candidates.html

create table catalogdb.gaia_dr3_qso_candidates(
solution_id bigint,  -- Solution Identifier (long)
source_id bigint,  -- Unique source identifier (unique within a particular Data Release) (long)
astrometric_selection_flag boolean,  -- Flag indicating if the source is part of the astrometric selection (boolean)
gaia_crf_source boolean,  -- Flag indicative of whether the source was used define the Gaia-CRF3 (boolean)
vari_best_class_name text,  -- Name of best class, see table vari_classifier_class_definition for details of the class (string)
vari_best_class_score real,  -- Score of the best class (float)
fractional_variability_g real,  -- Fractional variability in the G band (float)
structure_function_index real,  -- Index of the first-order structure function in the G band (float)
structure_function_index_scatter double precision,  -- Standard deviation of the index of the structure function (double)
qso_variability real,  -- Quasar variability metric in the G band (float)
non_qso_variability real,  -- Non-quasar variability metric in the G band (float)
vari_agn_membership_score double precision,  -- Membership score (0=lowest,1=highest) of source to be of AGN type (double)
classprob_dsc_combmod_quasar real,  -- Probability from DSC-Combmod of being a quasar (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_galaxy real,  -- Probability from DSC-Combmod of being a galaxy (data used: BP/RP spectrum, photometry, astrometry) (float)
classlabel_dsc text,  -- Class assigned by DSC based on the probability from its Combmod classifier (string)
classlabel_dsc_joint text,  -- Class assigned by DSC based on the probability from its Specmod and Allosmod classifiers (string)
classlabel_oa text,  -- Class assigned by OA the neuron that represents the source (string)
redshift_qsoc real,  -- Redshift from QSOC (float)
redshift_qsoc_lower real,  -- Redshift lower confidence level from QSOC (float)
redshift_qsoc_upper real,  -- Redshift upper confidence level from QSOC (float)
ccfratio_qsoc real,  -- Value of the cross-correlation function used to derive the redshift from QSOC, relative to the maximum value (float)
zscore_qsoc real,  -- Redshift zscore from QSOC (float)
flags_qsoc bigint,  -- Processing flags for the analysis based on BP/RP Spectra from QSOC (long)
n_transits integer,  -- Number of transits used for the morphological analysis (int)
intensity_quasar double precision,  -- Fitted intensity of the quasar at its centre (double, Flux[e− s−1])
intensity_quasar_error double precision,  -- Error on the fitted intensity of the quasar at its centre (double, Flux[e− s−1])
intensity_hostgalaxy double precision,  -- Fitted intensity of the host galaxy at the effective radius (double, Flux[e− s−1])
intensity_hostgalaxy_error double precision,  -- Error on the fitted intensity of the host galaxy at effective radius (double, Flux[e− s−1])
radius_hostgalaxy double precision,  -- Fitted effective radius of the host galaxy (double, Angle[mas])
radius_hostgalaxy_error double precision,  -- Error on the fitted effective radius of the host galaxy (double, Angle[mas])
sersic_index real,  -- Fitted sersic Index (float)
sersic_index_error real,  -- Error on the fitted sersic Index (float)
ellipticity_hostgalaxy double precision,  -- Fitted ellipticity of the host galaxy (double)
ellipticity_hostgalaxy_error double precision,  -- Error on the fitted ellipticity of the host galaxy (double)
posangle_hostgalaxy double precision,  -- Fitted position angle of the host galaxy (double, Angle[deg])
posangle_hostgalaxy_error double precision,  -- Error on the fitted position angle of the host galaxy (double, Angle[deg])
host_galaxy_detected boolean,  -- Flag indicating whether a host galaxy has been detected (boolean)
l2_norm double precision,  -- L2 norm for the fitted Sersic profile (double)
morph_params_corr_vec text,  -- Vector form of the upper triangle of the correlation matrix for the fitted morphological parameters (double[15] array)
host_galaxy_flag smallint,  -- Flag indicative of processing or scientific quality for the morphological parameters fitting (byte)
source_selection_flags integer  -- Bit indicative of whether the input data from a given module met the source list eligibility criteria for the source of interest (int)
);
