-- The create table statement is based on the information
-- in the XMM-OM-SUSS5.0.fits file.  

create table catalogdb.xmm_om_suss_5_0 (
IAUNAME text,  --  format = '22A'
N_SUMMARY bigint,  --  format = 'K ,  --  null = -9223372036854775808
OBSID text,  --  format = '10A'
SRCNUM bigint,  --  format = 'K ,  --  null = -9223372036854775808
UVW2_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
UVM2_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
UVW1_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
U_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
B_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
V_SRCDIST real,  --  format = 'E ,  --  unit = 'arcsec'
RA double precision,  --  format = 'D ,  --  unit = 'degrees'
DEC double precision,  --  format = 'D ,  --  unit = 'degrees'
RA_HMS text,  --  format = '13A'
DEC_DMS text,  --  format = '14A'
POSERR real,  --  format = 'E ,  --  unit = 'arcsec'
LII double precision,  --  format = 'D ,  --  unit = 'degrees'
BII double precision,  --  format = 'D ,  --  unit = 'degrees'
N_OBSID integer,  --  format = 'J ,  --  null = -2147483648
UVW2_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
UVM2_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
UVW1_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
U_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
B_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
V_SIGNIF real,  --  format = 'E ,  --  unit = 'sigma'
UVW2_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
UVW2_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
UVM2_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
UVM2_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
UVW1_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
UVW1_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
U_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
U_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
B_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
B_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
V_RATE real,  --  format = 'E ,  --  unit = 'count/sec'
V_RATE_ERR real,  --  format = 'E ,  --  unit = 'count/sec'
UVW2_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVW2_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVM2_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVM2_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVW1_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVW1_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
U_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
U_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
B_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
B_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
V_AB_FLUX real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
V_AB_FLUX_ERR real,  --  format = 'E ,  --  unit = 'erg/s/cm**2/A'
UVW2_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVW2_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVM2_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVM2_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVW1_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVW1_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
U_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
U_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
B_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
B_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
V_AB_MAG real,  --  format = 'E ,  --  unit = 'mag'
V_AB_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVW2_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVW2_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVM2_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVM2_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVW1_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
UVW1_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
U_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
U_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
B_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
B_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
V_VEGA_MAG real,  --  format = 'E ,  --  unit = 'mag'
V_VEGA_MAG_ERR real,  --  format = 'E ,  --  unit = 'mag'
UVW2_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVM2_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVW1_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
U_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
B_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
V_MAJOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVW2_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVM2_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVW1_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
U_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
B_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
V_MINOR_AXIS real,  --  format = 'E ,  --  unit = 'arcsec'
UVW2_POSANG real,  --  format = 'E ,  --  unit = 'degree'
UVM2_POSANG real,  --  format = 'E ,  --  unit = 'degree'
UVW1_POSANG real,  --  format = 'E ,  --  unit = 'degree'
U_POSANG real,  --  format = 'E ,  --  unit = 'degree'
B_POSANG real,  --  format = 'E ,  --  unit = 'degree'
V_POSANG real,  --  format = 'E ,  --  unit = 'degree'
UVW2_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
UVM2_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
UVW1_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
U_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
B_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
V_QUALITY_FLAG integer,  --  format = 'J ,  --  null = -2147483648
UVW2_QUALITY_FLAG_ST text,  --  format = '12A'
UVM2_QUALITY_FLAG_ST text,  --  format = '12A'
UVW1_QUALITY_FLAG_ST text,  --  format = '12A'
U_QUALITY_FLAG_ST text,  --  format = '12A'
B_QUALITY_FLAG_ST text,  --  format = '12A'
V_QUALITY_FLAG_ST text,  --  format = '12A'
UVW2_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
UVM2_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
UVW1_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
U_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
B_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
V_EXTENDED_FLAG smallint,  --  format = 'B ,  --  null = 255
UVW2_SKY_IMAGE text,  --  format = '3A'
UVM2_SKY_IMAGE text,  --  format = '3A'
UVW1_SKY_IMAGE text,  --  format = '3A'
U_SKY_IMAGE text,  --  format = '3A'
B_SKY_IMAGE text,  --  format = '3A'
V_SKY_IMAGE text  --  format = '3A'
);
