-- Based on the information in the below fits file
-- plateholes_meta.fits

create table catalogdb.sdssv_plateholes_meta (
plateId integer, --  format = 'J'
ha real[6], --  format = '6E, --  dim = '(6)'
ha_observable_min real[6], --  format = '6E, --  dim = '(6)'
ha_observable_max real[6], --  format = '6E, --  dim = '(6)'
programname text, --  format = '12A'
temp real, --  format = 'e'
design_platescale_alt real, --  format = 'e'
design_platescale_az real, --  format = 'e'
design_parallactic_angle real, --  format = 'e'
guider_coeff_0 real, --  format = 'e'
guider_coeff_1 real, --  format = 'e'
guider_coeff_2 real, --  format = 'e'
guider_coeff_3 real, --  format = 'e'
guider_coeff_4 real, --  format = 'e'
guider_coeff_5 real, --  format = 'e'
guider_coeff_6 real, --  format = 'e'
guider_coeff_7 real, --  format = 'e'
guider_coeff_8 real, --  format = 'e'
guider_coeff_9 real, --  format = 'e'
locationId integer, --  format = 'J'
instruments text, --  format = '25A'
npointings integer, --  format = 'J'
noffsets integer, --  format = 'J'
minstdinblockboss_shared text, --  format = '1A'
maxskyinblockboss_shared integer, --  format = 'J'
gfibertype text, --  format = '7A'
guidetype text, --  format = '4A'
guidenums1 integer[16], --  format = '16J, --  dim = '(16)'
guidemag_minmax real[2], --  format = '2E, --  dim = '(2)'
guide_lambda_eff real, --  format = 'e'
nguidemax integer, --  format = 'J'
ferrulesizeboss_shared real, --  format = 'e'
buffersizeboss_shared real, --  format = 'e'
ferrulesizeapogee_shared real, --  format = 'e'
buffersizeapogee_shared real, --  format = 'e'
ferrulesizeguide real, --  format = 'e'
buffersizeguide real, --  format = 'e'
platedesignstandards text, --  format = '11A'
standardtype text, --  format = '4A'
platedesignskies text, --  format = '11A'
skytype text, --  format = '4A'
plugmapstyle text, --  format = '21A'
bossmagtype text, --  format = '9A'
pointing_name text, --  format = '11A'
max_off_fiber_for_ha real, --  format = 'e'
collectfactor integer, --  format = 'J'
designid integer, --  format = 'J'
platedesignversion text, --  format = '2A'
platetype text, --  format = '11A'
raCen real, --  format = 'e'
decCen real, --  format = 'e'
ninputs integer, --  format = 'J'
plateinput1 text, --  format = '94A'
plateinput2 text, --  format = '87A'
plateinput3 text, --  format = '84A'
plateinput4 text, --  format = '87A'
plateinput5 text, --  format = '90A'
plateinput6 text, --  format = '87A'
plateinput7 text, --  format = '84A'
priority text, --  format = '62A'
relaxed_fiber_classes integer, --  format = 'J'
targettypes text, --  format = '20A'
napogee_shared_standard integer, --  format = 'J'
napogee_shared_science integer, --  format = 'J'
napogee_shared_sky integer, --  format = 'J'
nboss_shared_standard integer, --  format = 'J'
nboss_shared_science integer, --  format = 'J'
nboss_shared_sky integer, --  format = 'J'
minskyinblockboss_shared integer, --  format = 'J'
minstandardinblockboss_shared text, --  format = '1A'
reddeningMed real[5], --  format = '5E, --  dim = '(5)'
tileId integer, --  format = 'J'
theta integer, --  format = 'J'
platerun text, --  format = '17A'
platedesign_version text, --  format = '9A'
yanny_uid integer, --  format = 'J'
yanny_filename text, --  format = '129A'
plateinput8 text, --  format = '92A'
plateinput9 text, --  format = '92A'
plateinput10 text, --  format = '92A'
plateinput11 text, --  format = '92A'
plateinput12 text, --  format = '91A'
plateinput13 text, --  format = '90A'
plateinput14 text, --  format = '96A'
plateinput15 text, --  format = '96A'
plateinput16 text, --  format = '96A'
skyinput17 text, --  format = '75A'
plateinput18 text, --  format = '95A'
plateinput17 text, --  format = '95A'
skyinput18 text, --  format = '75A'
plateinput19 text, --  format = '95A'
skyinput16 text, --  format = '75A'
skyinput19 text, --  format = '75A'
plateinput20 text, --  format = '87A'
skyinput15 text, --  format = '73A'
skyinput21 text, --  format = '73A'
plateinput22 text, --  format = '76A'
skyinput13 text, --  format = '73A'
skyinput20 text, --  format = '75A'
plateinput21 text, --  format = '81A'
skyinput14 text, --  format = '73A'
skyinput6 text, --  format = '65A'
defaultsurveymode text, --  format = '7A'
skyinput23 text, --  format = '63A'
plateinput24 text --  format = '65A'
);
