-- Based on the information in the below fits file
-- plateholes_STRUCT1.fits
-- The fits file column named 'offset'
-- has been changed to the table column 'offset_integer'
-- because 'offset' is a PostgreSQL keyword. 

create table catalogdb.sdssv_plateholes (
holetype text, -- format = '14A'
targettype text, -- format = '9A'
sourcetype text, -- format = '5A'
target_ra double precision, -- format = 'D'
target_dec double precision, -- format = 'D'
iplateinput integer, -- format = 'J'
pointing integer, -- format = 'J'
offset_integer integer, -- format = 'J'
fiberid integer, -- format = 'J'
block integer, -- format = 'J'
iguide integer, -- format = 'J'
xf_default real, -- format = 'E'
yf_default real, -- format = 'E'
lambda_eff real, -- format = 'E'
zoffset real, -- format = 'E'
bluefiber integer, -- format = 'J'
chunk integer, -- format = 'J'
ifinal integer, -- format = 'J'
origfile text, -- format = '2A'
fileindx integer, -- format = 'J'
diameter real, -- format = 'E'
buffer real, -- format = 'E'
priority integer, -- format = 'J'
assigned integer, -- format = 'J'
conflicted integer, -- format = 'J'
ranout integer, -- format = 'J'
outside integer, -- format = 'J'
mangaid text, -- format = '2A'
ifudesign integer, -- format = 'J'
ifudesignsize integer, -- format = 'J'
bundle_size integer, -- format = 'J'
fiber_size real, -- format = 'E'
tmass_j real, -- format = 'E'
tmass_h real, -- format = 'E'
tmass_k real, -- format = 'E'
gsc_vmag real, -- format = 'E'
tyc_bmag real, -- format = 'E'
tyc_vmag real, -- format = 'E'
mfd_mag  real[6], -- format = '6E, -- dim = '(6)'
usnob_mag real[5], -- format = '5E, -- dim = '(5)'
source_id bigint, -- format = 'K'
phot_g_mean_mag real, -- format = 'E'
sp_param_source text, -- format = '3A'
sp_params real[4], -- format = '4E, -- dim = '(4)'
sp_param_err real[4], -- format = '4E, -- dim = '(4)'
marvels_target1 integer, -- format = 'J'
marvels_target2 integer, -- format = 'J'
boss_target1 bigint, -- format = 'K'
boss_target2 bigint, -- format = 'K'
ancillary_target1 bigint, -- format = 'K'
ancillary_target2 bigint, -- format = 'K'
segue2_target1 integer, -- format = 'J'
segue2_target2 integer, -- format = 'J'
segueb_target1 integer, -- format = 'J'
segueb_target2 integer, -- format = 'J'
apogee_target1 integer, -- format = 'J'
apogee_target2 integer, -- format = 'J'
manga_target1 integer, -- format = 'J'
manga_target2 integer, -- format = 'J'
manga_target3 integer, -- format = 'J'
eboss_target0 bigint, -- format = 'K'
eboss_target1 bigint, -- format = 'K'
eboss_target2 bigint, -- format = 'K'
eboss_target_id bigint, -- format = 'K'
thing_id_targeting integer, -- format = 'J'
objid_targeting bigint, -- format = 'K'
apogee2_target1 integer, -- format = 'J'
apogee2_target2 integer, -- format = 'J'
apogee2_target3 integer, -- format = 'J'
run integer, -- format = 'J'
rerun text, -- format = '2A'
camcol integer, -- format = 'J'
field integer, -- format = 'J'
id integer, -- format = 'J'
psfflux real[5], -- format = '5E, -- dim = '(5)'
psfflux_ivar real[5], -- format = '5E, -- dim = '(5)'
fiberflux real[5], -- format = '5E, -- dim = '(5)'
fiberflux_ivar real[5], -- format = '5E, -- dim = '(5)'
fiber2flux real[5], -- format = '5E, -- dim = '(5)'
fiber2flux_ivar real[5], -- format = '5E, -- dim = '(5)'
psfmag real[5], -- format = '5E, -- dim = '(5)'
fibermag real[5], -- format = '5E, -- dim = '(5)'
fiber2mag real[5], -- format = '5E, -- dim = '(5)'
mag real[5], -- format = '5E, -- dim = '(5)'
epoch real, -- format = 'E'
pmra real, -- format = 'E'
pmdec real, -- format = 'E'
targetids text, -- format = '3A'
ifuid integer, -- format = 'J'
catalogid bigint, -- format = 'K'
gaia_bp real, -- format = 'E'
gaia_rp real, -- format = 'E'
gaia_g real, -- format = 'E'
tmass_id text, -- format = '25A'
sdssv_apogee_target0 integer, -- format = 'J'
sdssv_boss_target0 bigint, -- format = 'K'
gri_gaia_transform integer, -- format = 'J'
firstcarton text, -- format = '49A'
xfocal double precision, -- format = 'D'
yfocal double precision, -- format = 'D'
yanny_uid integer, -- format = 'J'
yanny_filename text -- format = '129A'
);
