#! /usr/bin/bash
# encoding: utf-8


ls /uufs/chpc.utah.edu/common/home/sdss/sdsswork/gaia/dr2/gaia_source/csv/*.csv.gz | parallel -j25 "psql -U sdss sdss5db -c \"\copy catalogdb.gaia_dr2_source FROM program 'zcat {}' WITH CSV HEADER;\""
