#! /usr/bin/bash
# encoding: utf-8


ls /scratch/general/lustre/u0449727/2MASS_psc/* | parallel -j25 "psql -U sdss sdss5db -c \"\copy catalogdb.twomass_psc FROM '{}' WITH DELIMITER '|' NULL '\N' CSV;;\""

#SCN in one file
echo "start scn"
psql -U sdss sdss5db -c "\copy catalogdb.twomass_scn FROM '/scratch/general/lustre/u0449727/2MASS_scn/scn_aaa' WITH DELIMITER '|' NULL '\N' CSV;"

echo "start xsc"
#XSC is two files
psql -U sdss sdss5db -c "\copy catalogdb.twomass_xsc FROM '/scratch/general/lustre/u0449727/2MASS_xsc/xsc_aaa' WITH DELIMITER '|' NULL '\N' CSV;"
psql -U sdss sdss5db -c "\copy catalogdb.twomass_xsc FROM '/scratch/general/lustre/u0449727/2MASS_xsc/xsc_baa' WITH DELIMITER '|' NULL '\N' CSV;"
echo "done"

