\o erosita_superset_agn_load.out
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_eFEDS_official_lsdr8_ext0_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_eFEDS_official_lsdr8_extlike6to14_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_catwise2020_gaiadr2_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_catwise2020_lsdr8_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_catwise2020_ps1dr2_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_catwise2020_skymapperdr2_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_catwise2020_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_nway_lsdr8_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_SEP_catwise2020_gaiadr2_MS_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_SEP_catwise2020_gaiadr2_v0.1.2.csv' delimiter ',';
\copy catalogdb.erosita_superset_agn from '/uufs/chpc.utah.edu/common/home/sdss10/sdss5/target/catalogs/eRosita/erosita_for_catalogdb_v0.5/sdssv_erosita_homogenise_superset_v0.1.2/csv/erosita_superset_agn/sdssv_spiders_erass1_update_v05_agn_SEP_catwise2020_v0.1.2.csv' delimiter ',';
\o
