-- The column names are from line 10 of 
-- and the column types are from line 11 of
-- GLM360A_l108-169.tbl
-- the char sizes are from table 8 page 26 of
-- http://www.astro.wisc.edu/sirtf/glimpse360_dataprod_v1.2.pdf

create table catalogdb.glimpse360 (
designation char(26),
tmass_designation char(16),
tmass_cntr integer,
l double precision,
b double precision,
dl double precision,
db double precision,
ra double precision,
dec double precision,
dra double precision,
ddec double precision,
csf integer,
mag_J real,
dJ_m real,
mag_H real,
dH_m real,
mag_Ks real,
dKs_m real,
mag3_6 real,
d3_6m real,
mag4_5 real,
d4_5m real,
mag5_8 real,
d5_8m real,
mag8_0 real,
d8_0m real,
f_J real,
df_J real,
f_H real,
df_H real,
f_Ks real,
df_Ks real,
f3_6 real,
df3_6 real,
f4_5 real,
df4_5 real,
f5_8 real,
df5_8 real,
f8_0 real,
df8_0 real,
rms_f3_6 real,
rms_f4_5 real,
rms_f5_8 real,
rms_f8_0 real,
sky_3_6 real,
sky_4_5 real,
sky_5_8 real,
sky_8_0 real,
sn_J real,
sn_H real,
sn_Ks real,
sn_3_6 real,
sn_4_5 real,
sn_5_8 real,
sn_8_0 real,
dens_3_6 real,
dens_4_5 real,
dens_5_8 real,
dens_8_0 real,
m3_6 integer,
m4_5 integer,
m5_8 integer,
m8_0 integer,
n3_6 integer,
n4_5 integer,
n5_8 integer,
n8_0 integer,
sqf_J integer,
sqf_H integer,
sqf_Ks integer,
sqf_3_6 integer,
sqf_4_5 integer,
sqf_5_8 integer,
sqf_8_0 integer,
mf3_6 integer,
mf4_5 integer,
mf5_8 integer,
mf8_0 integer
)
