CREATE TABLE boss_drp.boss_version (
    id SERIAL NOT NULL PRIMARY KEY,
    ipl INT2,
    run2d VARCHAR,
    run1d VARCHAR,
    is_default BOOLEAN,
    is_epoch BOOLEAN,
    is_custom BOOLEAN,
    custom_name VARCHAR,
    sdssc2bv integer
    created timestamp with time zone,
    modified timestamp with time zone default NOW()
);
ALTER TABLE boss_drp.boss_version OWNER TO sdss;
ALTER INDEX boss_drp.boss_version_pkey SET TABLESPACE nvme;


CREATE TABLE boss_drp.boss_field (
    id SERIAL NOT NULL PRIMARY KEY,
    boss_version_id int not null references boss_drp.boss_version(id),
    field integer,
    designs VARCHAR,
    design_vers VARCHAR,
    design_mode VARCHAR,
    configs VARCHAR,
    mjd integer,
    observatory VARCHAR,
    run2d VARCHAR,
    run1d VARCHAR,
    racen real,
    deccen real,
    epoch real,
    cartid VARCHAR,
    tai double precision,
    tai_beg double precision,
    tai_end double precision,
    airmass real,
    exptime real,
    mapname VARCHAR,
    tileid integer,
    designid integer,
    survey VARCHAR,
    programname VARCHAR,
    chunk VARCHAR,
    fieldquality VARCHAR,
    fieldsn2 real,
    deredsn2 real,
    qsurvey integer,
    mjdlist VARCHAR,
    nexp integer,
    nexp_b1 integer,
    nexp_r1 integer,
    nexp_b2 integer,
    nexp_r2 integer,
    expt_b1 real,
    expt_r1 real,
    expt_b2 real,
    expt_r2 real,
    sn2_g1 real,
    sn2_r1 real,
    sn2_i1 real,
    sn2_g2 real,
    sn2_r2 real,
    sn2_i2 real,
    goffstd real,
    grmsstd real,
    roffstd real,
    rrmsstd real,
    ioffstd real,
    irmsstd real,
    groffstd real,
    grrmsstd real,
    rioffstd real,
    rirmsstd real,
    goffgal real,
    grmsgal real,
    roffgal real,
    rrmsgal real,
    ioffgal real,
    irmsgal real,
    groffgal real,
    grrmsgal real,
    rioffgal real,
    rirmsgal real,
    nguide integer,
    seeing20 real,
    seeing50 real,
    seeing80 real,
    rmsoff20 real,
    rmsoff50 real,
    rmsoff80 real,
    airtemp real,
    xsigma real,
    xsigmin real,
    xsigmax real,
    wsigma real,
    wsigmin real,
    wsigmax real,
    xchi2 real,
    xchi2min real,
    xchi2max real,
    skychi2 real,
    schi2min real,
    schi2max real,
    fbadpix real,
    fbadpix1 real,
    fbadpix2 real,
    n_total integer,
    n_galaxy integer,
    n_qso integer,
    n_star integer,
    n_unknown integer,
    n_sky integer,
    n_std integer,
    n_target_qso integer,
    n_target_main integer,
    n_target_lrg1 integer,
    n_target_lrg2 integer,
    n_target_elg integer,
    success_main real,
    success_lrg1 real,
    success_lrg2 real,
    success_elg real,
    success_qso real,
    status2d VARCHAR,
    statuscombine VARCHAR,
    status1d VARCHAR,
    public VARCHAR,
    qualcomments VARCHAR,
    moon_frac real,
    field_cadence VARCHAR,
    design_ver VARCHAR,
    design_mode VARCHAR,
    created timestamp with time zone,
    modified timestamp with time zone default NOW()
);
ALTER TABLE boss_drp.boss_field OWNER TO sdss;
ALTER INDEX boss_drp.boss_field_pkey SET TABLESPACE nvme;

CREATE TABLE boss_drp.boss_spectrum (
    id SERIAL NOT NULL PRIMARY KEY,
    boss_version_id int not null references boss_drp.boss_version(id),
    field integer,
    mjd integer,
    mjd_final real,
    obs VARCHAR,
    run2d VARCHAR,
    run1d VARCHAR,
    nexp smallint,
    exptime real,
    target_index integer,
    spec_file VARCHAR,
    programname VARCHAR,
    survey VARCHAR,
    cadence VARCHAR,
    firstcarton VARCHAR,
    sdss5_target_flags bytea,
    too BOOLEAN,
--- sdssv_boss_target0 bigint,
--- primtarget integer,
--- sectarget integer,
--- chunk VARCHAR,
    objtype VARCHAR,
    catalogid bigint,
    sdss_id bigint,
    specobjid numeric(29),
    calibflux real[],
    calibflux_ivar real[],
    optical_prov VARCHAR,
    mag real[],
    psfmag real[],
    fiber2mag real[],
    catdb_mag real[],
    gri_gaia_transform bigint
    gaia_bp_mag real,
    gaia_rp_mag real,
    gaia_g_mag real,
    gaia_id bigint,
    wise_mag real[],
    twomass_mag real[],
    guvcat_mag real[],
    ebv real,
    ebv_type VARCHAR,
    fiber_ra double precision,
    fiber_dec double precision,
    plug_ra double precision,
    plug_dec double precision,
    racat double precision,
    deccat double precision,
    coord_epoch real,
    delta_ra double precision,
    delta_dec double precision,
    pmra real,
    pmdec real,
    parallax real,
    fiber_offset integer,
    --- bluefiber integer,
    lambda_eff real,
    healpix integer,
    healpixgrp smallint,
    healpix_dir VARCHAR,
    fieldquality VARCHAR,
    exp_disp_med double precision,
    fieldsn2 real,
    --- deredsn2 real,
    spec1_g real,
    spec1_r real,
    spec1_i real,
    spec2_g real,
    spec2_r real,
    spec2_i real,
    sn_median real[],
    sn_median_all real,
    airmass real,
    seeing20 real,
    seeing50 real,
    seeing80 real,
    moon_dist real,
    moon_phase real,
    assigned BOOLEAN,
    on_target BOOLEAN,
    valid BOOLEAN,
    decollided BOOLEAN,
    anyandmask integer,
    anyormask integer,
    specprimary smallint,
    specboss smallint,
    boss_specobj_id integer,
    nspecobs smallint,
    spectroflux real[],
    spectroflux_ivar real[],
    spectrosynflux real[],
    spectrosynflux_ivar real[],
    spectroskyflux real[],
    wavemin real,
    wavemax real,
    wcoverage real,
    objclass VARCHAR,
    subclass VARCHAR,
    z real,
    z_err real,
    zwarning integer,
    rchi2 real,
    dof integer,
    rchi2diff real,
    tfile VARCHAR,
    vdisp real,
    vdisp_err real,
    vdispz real,
    vdispz_err real,
    vdispchi2 real,
    vdispnpix real,
    vdispdof integer,
    chi68p real,
    z_noqso real,
    z_err_noqso real,
    znum_noqso integer,
    zwarning_noqso integer,
    class_noqso VARCHAR,
    subclass_noqso VARCHAR,
    rchi2diff_noqso real,
    xcsao_rv real,
    xcsao_erv real,
    xcsao_rxc real,
    xcsao_teff real,
    xcsao_eteff real,
    xcsao_logg real,
    xcsao_elogg real,
    xcsao_feh real,
    xcsao_efeh real,
    too BOOLEARN,
    too_id bigint,
    --- elodie_filename VARCHAR,
    --- elodie_object VARCHAR,
    --- elodie_sptype VARCHAR,
    --- elodie_bv real,
    --- elodie_teff real,
    --- elodie_logg real,
    --- elodie_feh real,
    --- elodie_z real,
    --- elodie_z_err real,
    --- elodie_z_modelerr real,
    --- elodie_rchi2 real,
    --- elodie_dof integer,
    --- mjd_list VARCHAR,
    --- tai_list VARCHAR,
    --- fieldsnr2g_list VARCHAR,
    --- fieldsnr2r_list VARCHAR,
    --- fieldsnr2i_list VARCHAR,
    --- tcolumn integer[],
    --- npoly integer,
    --- theta real[],
    --- fracnsigma real[],
    --- fracnsighi real[],
    --- fracnsiglo real[],
    created timestamp with time zone,
    modified timestamp with time zone default NOW()
);
ALTER TABLE boss_drp.boss_spectrum OWNER TO sdss;
ALTER INDEX boss_drp.boss_spectrum_pkey SET TABLESPACE nvme;
CREATE INDEX boss_spectrum_sdss_id_idx ON boss_drp.boss_spectrum(sdss_id);
CREATE INDEX boss_spectrum_run2d_idx ON boss_drp.boss_spectrum(run2d);
CREATE INDEX boss_spectrum_obs_idx ON boss_drp.boss_spectrum(obs);
CREATE INDEX boss_spectrum_version_id_idx ON boss_drp.boss_spectrum(boss_version_id);


CREATE TABLE boss_drp.boss_spectrum_line (
    id SERIAL NOT NULL PRIMARY KEY,
    boss_version_id int not null references boss_drp.boss_version(id),
    field integer,
    mjd integer,
    target_index integer,
    catalogid bigint,
    sdss_id bigint,
    linename VARCHAR,
    linewave double precision,
    linez real,
    linez_err real,
    linesigma real,
    linesigma_err real,
    linearea real,
    linearea_err real,
    lineew real,
    lineew_err real,
    linecontlevel real,
    linecontlevel_err real,
    linenpixleft integer,
    linenpixright integer,
    linedof real,
    linechi2 real,
    obs VARCHAR,
    created timestamp with time zone,
    modified timestamp with time zone default NOW()
);
ALTER TABLE boss_drp.boss_spectrum_line OWNER TO sdss;
ALTER INDEX boss_drp.boss_spectrum_line_pkey SET TABLESPACE nvme;
