-- The create table statement is based on the below link.
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_extra--galactic_tables/ssec_dm_galaxy_candidates.html

create table catalogdb.gaia_dr3_galaxy_candidates(
solution_id bigint,  -- Solution Identifier (long)
source_id bigint,  -- Unique source identifier (unique within a particular Data Release) (long)
vari_best_class_name text,  -- Name of best class, see table vari_classifier_class_definition for details of the class (string)
vari_best_class_score real,  -- Score of the best class (float)
classprob_dsc_combmod_galaxy real,  -- Probability from DSC-Combmod of being a galaxy (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_quasar real,  -- Probability from DSC-Combmod of being a quasar (data used: BP/RP spectrum, photometry, astrometry) (float)
classlabel_dsc text,  -- Class assigned by DSC based on the probability from its Combmod classifier (string)
classlabel_dsc_joint text,  -- Class assigned by DSC based on the probability from its Specmod and Allosmod classifiers (string)
classlabel_oa text,  -- Class assigned by OA the neuron that represents the source (string)
redshift_ugc real,  -- Redshift from UGC (float)
redshift_ugc_lower real,  -- Redshift prediction lower limit from UGC (float)
redshift_ugc_upper real,  -- Redshift prediction upper limit from UGC (float)
n_transits integer,  -- Number of transits used for the morphological analysis (int)
posangle_sersic double precision,  -- Fitted position angle of the source for the Sersic Profile (double, Angle[deg])
posangle_sersic_error double precision,  -- Error on the fitted position angle of the source for the Sersic Profile (double, Angle[deg])
intensity_sersic double precision,  -- Fitted intensity of the source for the Sersic Profile (double, Flux[e− s−1])
intensity_sersic_error double precision,  -- Error on the fitted intensity of the source at effective radius radius_sersic (double, Flux[e− s−1])
radius_sersic double precision,  -- Fitted effective radius of the source for the Sersic Profile (double, Angle[mas])
radius_sersic_error double precision,  -- Error on the fitted effective radius of the source for the Sersic Profile (double, Angle[mas])
ellipticity_sersic double precision,  -- Fitted ellipticity of source for the Sersic Profile (double)
ellipticity_sersic_error double precision,  -- Error on the fitted ellipticity of the source for the Sersic Profile (double)
n_sersic real,  -- Fitted Sersic Index for Sersic Profile (float)
n_sersic_error real,  -- Error on the fitted Sersic Index for Sersic Profile (float)
l2_sersic double precision,  -- L2 norm for the Sersic Profile (double)
morph_params_corr_vec_sersic text,  -- Vector form of the upper triangle of the correlation matrix for the fitted parameters for the Sersic Profile (double[10] array)
flags_sersic smallint,  -- Flag indicative of processing or scientific quality for the morphological parameters fitting for the Sersic Profile (byte)
posangle_de_vaucouleurs double precision,  -- Fitted position angle of the source for the de Vaucouleurs Profile (double, Angle[deg])
posangle_de_vaucouleurs_error double precision,  -- Error on the fitted position angle of the source for the de Vaucouleurs Profile (double, Angle[deg])
intensity_de_vaucouleurs double precision,  -- Fitted intensity of the source for the de Vaucouleurs Profile (double, Flux[e− s−1])
intensity_de_vaucouleurs_error double precision,  -- Error on the fitted intensity of the bulge for the de Vaucouleurs Profile (double, Flux[e− s−1])
radius_de_vaucouleurs double precision,  -- Fitted effective radius of the source for de Vaucouleurs Profile (double, Angle[mas])
radius_de_vaucouleurs_error double precision,  -- Error on the fitted effective radius of the source for the de Vaucouleurs Profile (double, Angle[mas])
ellipticity_de_vaucouleurs double precision,  -- Fitted ellipticity of source for the de Vaucouleurs Profile (double)
ellipticity_de_vaucouleurs_error double precision,  -- Error on the fitted ellipticity of the source for the de Vaucouleurs Profile (double)
l2_de_vaucouleurs double precision,  -- L2 norm for the de Vaucouleurs Profile (double)
morph_params_corr_vec_de_vaucouleurs text,  -- Vector form of the upper triangle of the correlation matrix for the fitted parameters for the de Vaucouleurs Profile (double[21] array)
flags_de_vaucouleurs smallint,  -- Flag indicative of processing or scientific quality for the morphological parameters fitting for the de Vaucouleurs Profile (byte)
source_selection_flags integer  -- Bit indicative of whether the input data from a given module met the source list eligibility criteria for the source of interest (int)
);
