-- The create table statement is based on the information
-- in the dr6_v2_LRS_xGEDR3_SID.fits file.  

create table catalogdb.lamost_dr6 (
obsid integer,  -- format = 'J'
designation text,  -- format = '19A'
obsdate text,  -- format = '10A'
lmjd integer,  -- format = 'J'
mjd integer,  -- format = 'J'
planid text,  -- format = '40A'
spid smallint,  -- format = 'B'
fiberid smallint,  -- format = 'B'
ra_obs double precision,  -- format = 'D ,  -- unit = 'deg'
dec_obs double precision,  -- format = 'D ,  -- unit = 'deg'
snru real,  -- format = 'E'
snrg real,  -- format = 'E'
snrr real,  -- format = 'E'
snri real,  -- format = 'E'
snrz real,  -- format = 'E'
objtype text,  -- format = '16A'
class text,  -- format = '20A'
subclass text,  -- format = '20A'
z real,  -- format = 'E'
z_err real,  -- format = 'E'
magtype text,  -- format = '25A'
mag1 real,  -- format = 'E ,  -- unit = 'mag'
mag2 real,  -- format = 'E ,  -- unit = 'mag'
mag3 real,  -- format = 'E ,  -- unit = 'mag'
mag4 real,  -- format = 'E ,  -- unit = 'mag'
mag5 real,  -- format = 'E ,  -- unit = 'mag'
mag6 real,  -- format = 'E ,  -- unit = 'mag'
mag7 real,  -- format = 'E ,  -- unit = 'mag'
tsource text,  -- format = '16A'
fibertype text,  -- format = '10A'
tfrom text,  -- format = '60A'
tcomment text,  -- format = '60A'
offsets smallint,  -- format = 'B'
offsets_v real,  -- format = 'E'
ra double precision,  -- format = 'D ,  -- unit = 'deg'
dec double precision,  -- format = 'D ,  -- unit = 'deg'
fibermask smallint,  -- format = 'I'
ra_x double precision,  -- format = 'D ,  -- unit = 'deg'
dec_x double precision,  -- format = 'D ,  -- unit = 'deg'
errHalfMaj real,  -- format = 'E ,  -- unit = 'arcsec'
errHalfMin real,  -- format = 'E ,  -- unit = 'arcsec'
errPosAng real,  -- format = 'E ,  -- unit = 'deg'
source_id bigint  -- format = 'K'
);

