/*

SDSS AllStarMerge r13

Provided by Nicholas Troup - https://bit.ly/39emJ31

At Utah: /uufs/chpc.utah.edu/common/home/sdss50/sdsswork/target/catalogs/sdssApogeeAllStarMerge/r13/
Catalogue generated via IDL script: aporbitprep_mergestar.pro

*/

CREATE TABLE catalogdb.sdss_apogeeAllStarMerge_r13 (
    apogee_id TEXT,
    nvisits SMALLINT,
    nentries INTEGER,
    ra DOUBLE PRECISION,
    dec DOUBLE PRECISION,
    glon DOUBLE PRECISION,
    glat DOUBLE PRECISION,
    pmra DOUBLE PRECISION,
    pmdec DOUBLE PRECISION,
    pm_src TEXT,
    j REAL,
    j_err REAL,
    h REAL,
    h_err REAL,
    k REAL,
    k_err REAL,
    ak REAL,
    vhelio_avg REAL,
    vhelio_err REAL,
    vscatter REAL,
    sig_rvvar REAL,
    baseline REAL,
    mean_fiber REAL,
    sig_fiber REAL,
    apstar_ids TEXT,
    nvisit_apstar SMALLINT[20],
    weights REAL[20],
    visits TEXT,
    fields TEXT,
    surveys TEXT,
    telescopes TEXT,
    location_id SMALLINT[20],
    commiss SMALLINT[20],
    targflags TEXT,
    starflags TEXT,
    aspcapflags TEXT,
    teff REAL,
    teff_err REAL,
    logg REAL,
    logg_err REAL,
    feh REAL,
    feh_err REAL,
    param REAL[9],
    param_cov REAL[9][9],
    fparam REAL[9],
    fparam_cov REAL[9][9],
    param_symbol TEXT[9],
    x_h REAL[26],
    x_h_err REAL[26],
    felem REAL[26],
    felem_err REAL[26],
    elem_symbol TEXT[26],
    felemtoh SMALLINT[31],
    startype TEXT,
    vjitter REAL,
    dist REAL,
    dist_err REAL,
    dist_src TEXT,
    dist_srclist TEXT,
    mstar REAL,
    mstar_err REAL,
    rstar REAL,
    rstar_err REAL,
    mstar_src TEXT,
    jd DOUBLE PRECISION[65],
    rv DOUBLE PRECISION[65],
    rv_err DOUBLE PRECISION[65],
    rv_src TEXT[65],
    snr REAL[65],
    fiberid SMALLINT[65],
    visit_pk INTEGER[65]
);
