# Code generated by:
# source: astra_080.py
# Adapted for schema-dispatched ASTRA models

from peewee import (
    AutoField,
    BigIntegerField,
    BooleanField,
    DateTimeField,
    FloatField,
    ForeignKeyField,
    IntegerField,
    SQL,
    TextField,
)
from playhouse.postgres_ext import ArrayField

from sdssdb.peewee.sdss5db.astra import base as common


class AstraBase(common.AstraCommon):
    class Meta:
        database = common.AstraCommon._meta.database
        schema = "astra_080"


class Source(AstraBase, common.Source):
    pk = AutoField()
    gaia_dr2_source_id = BigIntegerField(null=True, unique=True)
    gaia_dr3_source_id = BigIntegerField(null=True, unique=True)
    catalogid = BigIntegerField(index=True, null=True)
    catalogid21 = BigIntegerField(index=True, null=True)
    catalogid25 = BigIntegerField(index=True, null=True)
    catalogid31 = BigIntegerField(index=True, null=True)
    l = FloatField(null=True)
    b = FloatField(null=True)
    w1_mag = FloatField(null=True)
    e_w1_mag = FloatField(null=True)
    w2_mag = FloatField(null=True)
    e_w2_mag = FloatField(null=True)
    c_star = FloatField(null=True)
    u_jkc_mag = FloatField(null=True)
    b_jkc_mag = FloatField(null=True)
    v_jkc_mag = FloatField(null=True)
    r_jkc_mag = FloatField(null=True)
    i_jkc_mag = FloatField(null=True)
    u_sdss_mag = FloatField(null=True)
    g_sdss_mag = FloatField(null=True)
    r_sdss_mag = FloatField(null=True)
    i_sdss_mag = FloatField(null=True)
    z_sdss_mag = FloatField(null=True)
    y_ps1_mag = FloatField(null=True)
    created = DateTimeField()
    modified = DateTimeField()
    crossmatch_flags = IntegerField(constraints=[SQL("DEFAULT 0")], null=True)
    class Meta:
        table_name = 'source'


class Spectrum(AstraBase, common.Spectrum):
    pk = AutoField()
    spectrum_flags = BigIntegerField()
    class Meta:
        table_name = 'spectrum'


class ApogeeCoaddedSpectrumInApStar(AstraBase, common.ApogeeCoaddedSpectrumInApStar):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_coadded_spectrum_in_ap_star')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='apogee_coadded_spectrum_in_ap_star')
    created = DateTimeField()
    modified = DateTimeField()
    field = TextField()
    prefix = TextField()
    starver = IntegerField(null=True)
    class Meta:
        table_name = 'apogee_coadded_spectrum_in_ap_star'
        indexes = (
            (('release', 'apred', 'apstar', 'obj', 'telescope', 'field', 'prefix'), True)
        )

class ApogeeCombinedSpectrum(AstraBase, common.ApogeeCombinedSpectrum):
    pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_combined_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='apogee_combined_spectrum')
    created = DateTimeField()
    modified = DateTimeField()
    class Meta:
        table_name = 'apogee_combined_spectrum'
        indexes = (
            (('release', 'filetype', 'v_astra', 'healpix', 'sdss_id', 'telescope', 'apred'), True)
        )

class ApogeeNet(AstraBase, common.ApogeeNet):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_net')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='apogee_net')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    raw_e_teff = FloatField(null=True)
    raw_e_logg = FloatField(null=True)
    raw_e_fe_h = FloatField(null=True)
    class Meta:
        table_name = 'apogee_net'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
            (('spectrum_pk', 'v_astra_major_minor'), True),
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class ApogeeRestFrameVisitSpectrum(AstraBase, common.ApogeeRestFrameVisitSpectrum):
    pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_rest_frame_visit_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='apogee_rest_frame_visit_spectrum')
    in_stack = BooleanField()
    created = DateTimeField()
    modified = DateTimeField()
    class Meta:
        table_name = 'apogee_rest_frame_visit_spectrum'
        indexes = (
            (('release', 'v_astra', 'sdss_id', 'apred', 'mjd', 'plate', 'telescope', 'field', 'fiber', 'prefix', 'reduction'), True)
        )

class ApogeeVisitSpectrum(AstraBase, common.ApogeeVisitSpectrum):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_visit_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='apogee_visit_spectrum')
    created = DateTimeField()
    modified = DateTimeField()
    class Meta:
        table_name = 'apogee_visit_spectrum'
        indexes = (
            (('release', 'apred', 'mjd', 'plate', 'telescope', 'field', 'fiber', 'prefix', 'reduction'), True)
            (('source_pk', 'telescope', 'mjd', 'fiber', 'plate', 'field'), False)
        )

class ApogeeVisitSpectrumInApStar(AstraBase, common.ApogeeVisitSpectrumInApStar):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='apogee_visit_spectrum_in_ap_star')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='apogee_visit_spectrum_in_ap_star')
    drp_spectrum_pk = IntegerField(unique=True)
    created = DateTimeField()
    modified = DateTimeField()
    field = TextField()
    class Meta:
        table_name = 'apogee_visit_spectrum_in_ap_star'
        indexes = (
            (('release', 'apred', 'apstar', 'obj', 'telescope', 'field', 'prefix', 'plate', 'mjd', 'fiber'), True)
        )

class Aspcap(AstraBase):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='aspcap')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='aspcap')
    v_astra = IntegerField()
    created = DateTimeField()
    modified = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    v_astra_major_minor = IntegerField()
    irfm_teff = FloatField(null=True)
    irfm_teff_flags = BigIntegerField()
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    v_micro = FloatField(null=True)
    e_v_micro = FloatField(null=True)
    v_sini = FloatField(null=True)
    e_v_sini = FloatField(null=True)
    m_h_atm = FloatField(null=True)
    e_m_h_atm = FloatField(null=True)
    alpha_m_atm = FloatField(null=True)
    e_alpha_m_atm = FloatField(null=True)
    c_m_atm = FloatField(null=True)
    e_c_m_atm = FloatField(null=True)
    n_m_atm = FloatField(null=True)
    e_n_m_atm = FloatField(null=True)
    al_h = FloatField(null=True)
    e_al_h = FloatField(null=True)
    al_h_flags = BigIntegerField()
    al_h_rchi2 = FloatField(null=True)
    c_12_13 = FloatField(null=True)
    e_c_12_13 = FloatField(null=True)
    c_12_13_flags = BigIntegerField()
    c_12_13_rchi2 = FloatField(null=True)
    ca_h = FloatField(null=True)
    e_ca_h = FloatField(null=True)
    ca_h_flags = BigIntegerField()
    ca_h_rchi2 = FloatField(null=True)
    ce_h = FloatField(null=True)
    e_ce_h = FloatField(null=True)
    ce_h_flags = BigIntegerField()
    ce_h_rchi2 = FloatField(null=True)
    c_h = FloatField(null=True)
    e_c_h = FloatField(null=True)
    c_h_flags = BigIntegerField()
    c_h_rchi2 = FloatField(null=True)
    co_h = FloatField(null=True)
    e_co_h = FloatField(null=True)
    co_h_flags = BigIntegerField()
    co_h_rchi2 = FloatField(null=True)
    cr_h = FloatField(null=True)
    e_cr_h = FloatField(null=True)
    cr_h_flags = BigIntegerField()
    cr_h_rchi2 = FloatField(null=True)
    cu_h = FloatField(null=True)
    e_cu_h = FloatField(null=True)
    cu_h_flags = BigIntegerField()
    cu_h_rchi2 = FloatField(null=True)
    fe_h = FloatField(null=True)
    e_fe_h = FloatField(null=True)
    fe_h_flags = BigIntegerField()
    fe_h_rchi2 = FloatField(null=True)
    k_h = FloatField(null=True)
    e_k_h = FloatField(null=True)
    k_h_flags = BigIntegerField()
    k_h_rchi2 = FloatField(null=True)
    mg_h = FloatField(null=True)
    e_mg_h = FloatField(null=True)
    mg_h_flags = BigIntegerField()
    mg_h_rchi2 = FloatField(null=True)
    mn_h = FloatField(null=True)
    e_mn_h = FloatField(null=True)
    mn_h_flags = BigIntegerField()
    mn_h_rchi2 = FloatField(null=True)
    na_h = FloatField(null=True)
    e_na_h = FloatField(null=True)
    na_h_flags = BigIntegerField()
    na_h_rchi2 = FloatField(null=True)
    nd_h = FloatField(null=True)
    e_nd_h = FloatField(null=True)
    nd_h_flags = BigIntegerField()
    nd_h_rchi2 = FloatField(null=True)
    ni_h = FloatField(null=True)
    e_ni_h = FloatField(null=True)
    ni_h_flags = BigIntegerField()
    ni_h_rchi2 = FloatField(null=True)
    n_h = FloatField(null=True)
    e_n_h = FloatField(null=True)
    n_h_flags = BigIntegerField()
    n_h_rchi2 = FloatField(null=True)
    o_h = FloatField(null=True)
    e_o_h = FloatField(null=True)
    o_h_flags = BigIntegerField()
    o_h_rchi2 = FloatField(null=True)
    p_h = FloatField(null=True)
    e_p_h = FloatField(null=True)
    p_h_flags = BigIntegerField()
    p_h_rchi2 = FloatField(null=True)
    si_h = FloatField(null=True)
    e_si_h = FloatField(null=True)
    si_h_flags = BigIntegerField()
    si_h_rchi2 = FloatField(null=True)
    s_h = FloatField(null=True)
    e_s_h = FloatField(null=True)
    s_h_flags = BigIntegerField()
    s_h_rchi2 = FloatField(null=True)
    ti_h = FloatField(null=True)
    e_ti_h = FloatField(null=True)
    ti_h_flags = BigIntegerField()
    ti_h_rchi2 = FloatField(null=True)
    v_h = FloatField(null=True)
    e_v_h = FloatField(null=True)
    v_h_flags = BigIntegerField()
    v_h_rchi2 = FloatField(null=True)
    short_grid_name = TextField()
    continuum_order = IntegerField()
    continuum_reject = FloatField(null=True)
    interpolation_order = IntegerField()
    initial_flags = BigIntegerField()
    rchi2 = FloatField(null=True)
    ferre_log_snr_sq = FloatField(null=True)
    ferre_time_coarse = FloatField(null=True)
    ferre_time_params = FloatField(null=True)
    ferre_time_abundances = FloatField(null=True)
    result_flags = BigIntegerField()
    initial_teff = FloatField(null=True)
    initial_logg = FloatField(null=True)
    initial_v_micro = FloatField(null=True)
    initial_v_sini = FloatField(null=True)
    initial_m_h_atm = FloatField(null=True)
    initial_alpha_m_atm = FloatField(null=True)
    initial_c_m_atm = FloatField(null=True)
    initial_n_m_atm = FloatField(null=True)
    coarse_teff = FloatField(null=True)
    coarse_logg = FloatField(null=True)
    coarse_v_micro = FloatField(null=True)
    coarse_v_sini = FloatField(null=True)
    coarse_m_h_atm = FloatField(null=True)
    coarse_alpha_m_atm = FloatField(null=True)
    coarse_c_m_atm = FloatField(null=True)
    coarse_n_m_atm = FloatField(null=True)
    coarse_ferre_flags = BigIntegerField()
    coarse_rchi2 = FloatField(null=True)
    coarse_penalized_rchi2 = FloatField(null=True)
    pwd = TextField(null=True)
    ferre_index = IntegerField(null=True)
    calibrated_flags = BigIntegerField(null=True)
    mass = FloatField(null=True)
    radius = FloatField(null=True)
    raw_teff = FloatField(null=True)
    raw_e_teff = FloatField(null=True)
    raw_logg = FloatField(null=True)
    raw_e_logg = FloatField(null=True)
    raw_v_micro = FloatField(null=True)
    raw_e_v_micro = FloatField(null=True)
    raw_v_sini = FloatField(null=True)
    raw_e_v_sini = FloatField(null=True)
    raw_m_h_atm = FloatField(null=True)
    raw_e_m_h_atm = FloatField(null=True)
    raw_alpha_m_atm = FloatField(null=True)
    raw_e_alpha_m_atm = FloatField(null=True)
    raw_c_m_atm = FloatField(null=True)
    raw_e_c_m_atm = FloatField(null=True)
    raw_n_m_atm = FloatField(null=True)
    raw_e_n_m_atm = FloatField(null=True)
    raw_al_h = FloatField(null=True)
    raw_e_al_h = FloatField(null=True)
    raw_c_12_13 = FloatField(null=True)
    raw_e_c_12_13 = FloatField(null=True)
    raw_ca_h = FloatField(null=True)
    raw_e_ca_h = FloatField(null=True)
    raw_ce_h = FloatField(null=True)
    raw_e_ce_h = FloatField(null=True)
    raw_c_h = FloatField(null=True)
    raw_e_c_h = FloatField(null=True)
    raw_co_h = FloatField(null=True)
    raw_e_co_h = FloatField(null=True)
    raw_cr_h = FloatField(null=True)
    raw_e_cr_h = FloatField(null=True)
    raw_cu_h = FloatField(null=True)
    raw_e_cu_h = FloatField(null=True)
    raw_fe_h = FloatField(null=True)
    raw_e_fe_h = FloatField(null=True)
    raw_k_h = FloatField(null=True)
    raw_e_k_h = FloatField(null=True)
    raw_mg_h = FloatField(null=True)
    raw_e_mg_h = FloatField(null=True)
    raw_mn_h = FloatField(null=True)
    raw_e_mn_h = FloatField(null=True)
    raw_na_h = FloatField(null=True)
    raw_e_na_h = FloatField(null=True)
    raw_nd_h = FloatField(null=True)
    raw_e_nd_h = FloatField(null=True)
    raw_ni_h = FloatField(null=True)
    raw_e_ni_h = FloatField(null=True)
    raw_n_h = FloatField(null=True)
    raw_e_n_h = FloatField(null=True)
    raw_o_h = FloatField(null=True)
    raw_e_o_h = FloatField(null=True)
    raw_p_h = FloatField(null=True)
    raw_e_p_h = FloatField(null=True)
    raw_si_h = FloatField(null=True)
    raw_e_si_h = FloatField(null=True)
    raw_s_h = FloatField(null=True)
    raw_e_s_h = FloatField(null=True)
    raw_ti_h = FloatField(null=True)
    raw_e_ti_h = FloatField(null=True)
    raw_v_h = FloatField(null=True)
    raw_e_v_h = FloatField(null=True)
    class Meta:
        table_name = 'aspcap'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class AstroNn(AstraBase, common.AstroNn):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='astro_nn')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='astro_nn')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    raw_teff = FloatField(null=True)
    raw_e_teff = FloatField(null=True)
    raw_logg = FloatField(null=True)
    raw_e_logg = FloatField(null=True)
    raw_c_h = FloatField(null=True)
    raw_e_c_h = FloatField(null=True)
    raw_c_1_h = FloatField(null=True)
    raw_e_c_1_h = FloatField(null=True)
    raw_n_h = FloatField(null=True)
    raw_e_n_h = FloatField(null=True)
    raw_o_h = FloatField(null=True)
    raw_e_o_h = FloatField(null=True)
    raw_na_h = FloatField(null=True)
    raw_e_na_h = FloatField(null=True)
    raw_mg_h = FloatField(null=True)
    raw_e_mg_h = FloatField(null=True)
    raw_al_h = FloatField(null=True)
    raw_e_al_h = FloatField(null=True)
    raw_si_h = FloatField(null=True)
    raw_e_si_h = FloatField(null=True)
    raw_p_h = FloatField(null=True)
    raw_e_p_h = FloatField(null=True)
    raw_s_h = FloatField(null=True)
    raw_e_s_h = FloatField(null=True)
    raw_k_h = FloatField(null=True)
    raw_e_k_h = FloatField(null=True)
    raw_ca_h = FloatField(null=True)
    raw_e_ca_h = FloatField(null=True)
    raw_ti_h = FloatField(null=True)
    raw_e_ti_h = FloatField(null=True)
    raw_ti_2_h = FloatField(null=True)
    raw_e_ti_2_h = FloatField(null=True)
    raw_v_h = FloatField(null=True)
    raw_e_v_h = FloatField(null=True)
    raw_cr_h = FloatField(null=True)
    raw_e_cr_h = FloatField(null=True)
    raw_mn_h = FloatField(null=True)
    raw_e_mn_h = FloatField(null=True)
    raw_fe_h = FloatField(null=True)
    raw_e_fe_h = FloatField(null=True)
    raw_co_h = FloatField(null=True)
    raw_e_co_h = FloatField(null=True)
    raw_ni_h = FloatField(null=True)
    raw_e_ni_h = FloatField(null=True)
    class Meta:
        table_name = 'astro_nn'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class AstroNnDist(AstraBase, common.AstroNnDist):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='astro_nn_dist')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='astro_nn_dist')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    a_k_mag = FloatField(column_name='A_k_mag', null=True)
    e_l_fakemag = FloatField(column_name='e_L_fakemag', null=True)
    e_dist = FloatField(null=True)
    class Meta:
        table_name = 'astro_nn_dist'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class BossCombinedSpectrum(AstraBase, common.BossCombinedSpectrum):
    pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='boss_combined_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='boss_combined_spectrum')
    created = DateTimeField()
    modified = DateTimeField()
    class Meta:
        table_name = 'boss_combined_spectrum'
        indexes = (
            (('release', 'filetype', 'v_astra', 'healpix', 'sdss_id', 'telescope', 'run2d'), True),
        )

class BossNet(AstraBase, common.BossNet):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='boss_net')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='boss_net')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    bn_v_r = FloatField(null=True)
    e_bn_v_r = FloatField(null=True)
    class Meta:
        table_name = 'boss_net'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class BossRestFrameVisitSpectrum(AstraBase, common.BossRestFrameVisitSpectrum):
    pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='boss_rest_frame_visit_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='boss_rest_frame_visit_spectrum')
    created = DateTimeField()
    modified = DateTimeField()
    class Meta:
        table_name = 'boss_rest_frame_visit_spectrum'
        indexes = (
            (('v_astra', 'filetype', 'release', 'run2d', 'fieldid', 'mjd', 'catalogid'), True),
        )

class BossVisitSpectrum(AstraBase, common.BossVisitSpectrum):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='boss_visit_spectrum')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, unique=True, backref='boss_visit_spectrum')
    created = DateTimeField()
    modified = DateTimeField()
    catalogid = BigIntegerField(index=True)
    spec_file = TextField(null=True)
    class Meta:
        table_name = 'boss_visit_spectrum'
        indexes = (
            (('release', 'run2d', 'fieldid', 'mjd', 'catalogid'), True),
            (('source_pk', 'telescope', 'mjd', 'fieldid', 'plateid'), False),
        )

class Corv(AstraBase, common.Corv):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='corv')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='corv')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    result_flags = BigIntegerField()
    class Meta:
        table_name = 'corv'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class LineForest(AstraBase, common.LineForest):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='line_forest')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='line_forest')
    v_astra = IntegerField()
    modified = DateTimeField()
    tag = TextField(index=True)
    v_astra_major_minor = IntegerField()
    eqw_percentiles_h_alpha = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_alpha = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_beta = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_beta = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_gamma = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_gamma = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_delta = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_delta = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_epsilon = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_epsilon = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_8 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_8 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_9 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_9 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_10 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_10 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_11 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_11 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_12 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_12 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_13 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_13 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_14 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_14 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_15 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_15 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_16 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_16 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_h_17 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_h_17 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_7 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_7 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_8 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_8 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_9 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_9 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_10 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_10 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_11 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_11 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_12 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_12 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_13 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_13 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_14 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_14 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_15 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_15 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_16 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_16 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_pa_17 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_pa_17 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_ca_ii_8662 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_ca_ii_8662 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_ca_ii_8542 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_ca_ii_8542 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_ca_ii_8498 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_ca_ii_8498 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_ca_k_3933 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_ca_k_3933 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_ca_h_3968 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_ca_h_3968 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_he_i_6678 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_he_i_6678 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_he_i_5875 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_he_i_5875 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_he_i_5015 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_he_i_5015 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_he_i_4471 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_he_i_4471 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_he_ii_4685 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_he_ii_4685 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_n_ii_6583 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_n_ii_6583 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_n_ii_6548 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_n_ii_6548 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_s_ii_6716 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_s_ii_6716 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_s_ii_6730 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_s_ii_6730 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_fe_ii_5018 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_fe_ii_5018 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_fe_ii_5169 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_fe_ii_5169 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_fe_ii_5197 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_fe_ii_5197 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_fe_ii_6432 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_fe_ii_6432 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_i_5577 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_i_5577 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_i_6300 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_i_6300 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_i_6363 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_i_6363 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_ii_3727 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_ii_3727 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_iii_4959 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_iii_4959 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_iii_5006 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_iii_5006 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_o_iii_4363 = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_o_iii_4363 = ArrayField(index=True, null=True)  # ARRAY
    eqw_percentiles_li_i = ArrayField(index=True, null=True)  # ARRAY
    abs_percentiles_li_i = ArrayField(index=True, null=True)  # ARRAY
    class Meta:
        table_name = 'line_forest'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class MDwarfType(AstraBase, common.MDwarfType):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='m_dwarf_type')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='m_dwarf_type')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    spectral_type = TextField(null=True)
    sub_type = FloatField(null=True)
    rchi2 = FloatField(null=True)
    class Meta:
        table_name = 'm_dwarf_type'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class MwmSpectrumProductStatus(AstraBase):
    task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='mwm_spectrum_product_status')
    v_astra = IntegerField()
    created = DateTimeField()
    modified = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    v_astra_major_minor = IntegerField()
    flags = BigIntegerField()
    class Meta:
        table_name = 'mwm_spectrum_product_status'
        indexes = (
            (('source_pk', 'v_astra_major_minor'), True),
        )

class Slam(AstraBase, common.Slam):
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='slam')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='slam')

    class Meta:
        table_name = 'slam'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )

class SnowWhite(AstraBase, common.SnowWhite):
    #task_pk = AutoField()
    source = ForeignKeyField(Source, column_name='source_pk', null=True, index=True, backref='snow_white')
    spectrum = ForeignKeyField(Spectrum, column_name='spectrum_pk', null=True, index=True, backref='snow_white')
    v_astra = IntegerField()
    modified = DateTimeField()
    v_astra_major_minor = IntegerField()
    raw_e_teff = FloatField(null=True)
    raw_e_logg = FloatField(null=True)
    class Meta:
        table_name = 'snow_white'
        indexes = (
            (('spectrum_pk', 'v_astra_major_minor'), True),
        )
