# !usr/bin/env python
# -*- coding: utf-8 -*-
#

# this file was autogenerated with sqlacodegen and then adapted for sdssdb
# flake8: noqa: E501,E741

from typing import Optional
from typing_extensions import Annotated
import datetime
from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    SmallInteger,
    Text,
    UniqueConstraint,
    text,
)
from sqlalchemy.orm import declared_attr, Mapped, mapped_column, relationship

from sdssdb.sqlalchemy.sdss5db import SDSS5dbBase, database


SCHEMA = "apogee_drp"
float53 = Annotated[float, 53]
intpk = Annotated[int, mapped_column(primary_key=True)]


class Base(SDSS5dbBase):
    __abstract__ = True
    _schema = SCHEMA
    _relations = "define_relations"

    type_annotation_map = {
        float53: Float(53),
    }

    @declared_attr
    def __table_args__(cls):
        return {"schema": cls._schema}


class CalibrationStatus(Base):
    __tablename__ = "calib_status"

    pk: Mapped[intpk]
    logfile: Mapped[Optional[str]] = mapped_column(Text)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    instrument: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    caltype: Mapped[Optional[str]] = mapped_column(Text, index=True)
    plate: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    configid: Mapped[Optional[str]] = mapped_column(Text)
    designid: Mapped[Optional[str]] = mapped_column(Text)
    fieldid: Mapped[Optional[str]] = mapped_column(Text)
    pbskey: Mapped[Optional[str]] = mapped_column(Text)
    checktime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    num: Mapped[Optional[str]] = mapped_column(Text, index=True)
    calfile: Mapped[Optional[str]] = mapped_column(Text)
    success3d: Mapped[Optional[bool]] = mapped_column(Boolean)
    success2d: Mapped[Optional[bool]] = mapped_column(Boolean)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))


class DailyStatus(Base):
    __tablename__ = "daily_status"

    pk: Mapped[intpk]
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    nexposures: Mapped[Optional[str]] = mapped_column(Text)
    nplanfiles: Mapped[Optional[str]] = mapped_column(Text)
    begtime: Mapped[Optional[str]] = mapped_column(Text, index=True)
    endtime: Mapped[Optional[str]] = mapped_column(Text, index=True)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))


class Exposure(Base):
    __tablename__ = "exposure"
    __table_args__ = (UniqueConstraint("num", "observatory"), {"schema": "apogee_drp"})

    pk: Mapped[intpk]
    num: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    nread: Mapped[Optional[int]] = mapped_column(Integer)
    exptype: Mapped[Optional[str]] = mapped_column(Text)
    plateid: Mapped[Optional[str]] = mapped_column(Text)
    exptime: Mapped[Optional[float]] = mapped_column(Float)
    dateobs: Mapped[Optional[str]] = mapped_column(Text)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    observatory: Mapped[Optional[str]] = mapped_column(Text)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    arctype: Mapped[Optional[str]] = mapped_column(Text)
    configid: Mapped[Optional[str]] = mapped_column(Text)
    designid: Mapped[Optional[str]] = mapped_column(Text)
    fieldid: Mapped[Optional[str]] = mapped_column(Text)
    dithpix: Mapped[Optional[float]] = mapped_column(Float)
    gangstate: Mapped[Optional[str]] = mapped_column(Text)
    shutter: Mapped[Optional[str]] = mapped_column(Text)
    calshutter: Mapped[Optional[str]] = mapped_column(Text)


class ExposureStatus(Base):
    __tablename__ = "exposure_status"

    pk: Mapped[intpk]
    exposure_pk: Mapped[int] = mapped_column(ForeignKey("apogee_drp.exposure.pk"), index=True)
    planfile: Mapped[Optional[str]] = mapped_column(Text)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    instrument: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    platetype: Mapped[Optional[str]] = mapped_column(Text)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    plate: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    proctype: Mapped[Optional[str]] = mapped_column(Text, index=True)
    pbskey: Mapped[Optional[str]] = mapped_column(Text)
    checktime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    num: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    configid: Mapped[Optional[str]] = mapped_column(Text)
    designid: Mapped[Optional[str]] = mapped_column(Text)
    fieldid: Mapped[Optional[str]] = mapped_column(Text)

    exposure: Mapped["Exposure"] = relationship("Exposure")


class MasterCalibrationStatus(Base):
    __tablename__ = "mastercal_status"

    pk: Mapped[intpk]
    logfile: Mapped[Optional[str]] = mapped_column(Text)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    instrument: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    caltype: Mapped[Optional[str]] = mapped_column(Text, index=True)
    pbskey: Mapped[Optional[str]] = mapped_column(Text)
    checktime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    name: Mapped[Optional[str]] = mapped_column(Text, index=True)
    calfile: Mapped[Optional[str]] = mapped_column(Text)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))


class Plan(Base):
    __tablename__ = "plan"

    pk: Mapped[intpk]
    planfile: Mapped[Optional[str]] = mapped_column(Text, index=True)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    instrument: Mapped[Optional[str]] = mapped_column(Text, index=True)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    plate: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    platetype: Mapped[Optional[str]] = mapped_column(Text, index=True)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    configid: Mapped[Optional[str]] = mapped_column(Text)
    designid: Mapped[Optional[str]] = mapped_column(Text)
    fieldid: Mapped[Optional[str]] = mapped_column(Text)
    fps: Mapped[Optional[bool]] = mapped_column(Boolean)


class RvStatus(Base):
    __tablename__ = "rv_status"

    pk: Mapped[intpk]
    apogee_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    healpix: Mapped[Optional[int]] = mapped_column(Integer)
    nvisits: Mapped[Optional[int]] = mapped_column(Integer)
    pbskey: Mapped[Optional[str]] = mapped_column(Text)
    file: Mapped[Optional[str]] = mapped_column(Text)
    checktime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)


class RvVisit(Base):
    __tablename__ = "rv_visit"
    __table_args__ = (
        UniqueConstraint("apred_vers", "telescope", "plate", "mjd", "fiberid", "starver"),
        {"schema": "apogee_drp"},
    )

    pk: Mapped[intpk]
    visit_pk: Mapped[int] = mapped_column(ForeignKey("apogee_drp.visit.pk"), index=True)
    apogee_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    catalogid: Mapped[Optional[int]] = mapped_column(BigInteger)
    star_pk: Mapped[int] = mapped_column(ForeignKey("apogee_drp.star.pk"), index=True)
    starver: Mapped[Optional[str]] = mapped_column(Text)
    file: Mapped[Optional[str]] = mapped_column(Text)
    uri: Mapped[Optional[str]] = mapped_column(Text)
    fiberid: Mapped[Optional[int]] = mapped_column(SmallInteger, index=True)
    plate: Mapped[Optional[str]] = mapped_column(Text, index=True)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    ra: Mapped[Optional[float53]]
    dec: Mapped[Optional[float53]]
    hmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    snr: Mapped[Optional[float]] = mapped_column(Float)
    dateobs: Mapped[Optional[str]] = mapped_column(Text)
    jd: Mapped[Optional[float53]]
    bc: Mapped[Optional[float]] = mapped_column(Float)
    vtype: Mapped[Optional[int]] = mapped_column(SmallInteger)
    vrel: Mapped[Optional[float]] = mapped_column(Float)
    vrelerr: Mapped[Optional[float]] = mapped_column(Float)
    vrad: Mapped[Optional[float]] = mapped_column(Float, index=True)
    chisq: Mapped[Optional[float]] = mapped_column(Float)
    rv_teff: Mapped[Optional[float]] = mapped_column(Float)
    rv_tefferr: Mapped[Optional[float]] = mapped_column(Float)
    rv_feh: Mapped[Optional[float]] = mapped_column(Float)
    rv_feherr: Mapped[Optional[float]] = mapped_column(Float)
    rv_logg: Mapped[Optional[float]] = mapped_column(Float)
    rv_loggerr: Mapped[Optional[float]] = mapped_column(Float)
    xcorr_vrel: Mapped[Optional[float]] = mapped_column(Float)
    xcorr_vrelerr: Mapped[Optional[float]] = mapped_column(Float)
    xcorr_vrad: Mapped[Optional[float]] = mapped_column(Float)
    n_components: Mapped[Optional[int]] = mapped_column(Integer)
    rv_components: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)

    star: Mapped["Star"] = relationship("Star")
    visit: Mapped["Visit"] = relationship("Visit")


class Star(Base):
    __tablename__ = "star"
    __table_args__ = (
        UniqueConstraint("apred_vers", "telescope", "apogee_id", "starver"),
        {"schema": "apogee_drp"},
    )

    pk: Mapped[intpk]
    apogee_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    file: Mapped[Optional[str]] = mapped_column(Text)
    uri: Mapped[Optional[str]] = mapped_column(Text)
    starver: Mapped[Optional[str]] = mapped_column(Text)
    mjdbeg: Mapped[Optional[int]] = mapped_column(Integer)
    mjdend: Mapped[Optional[int]] = mapped_column(Integer)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    healpix: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    snr: Mapped[Optional[float]] = mapped_column(Float)
    ra: Mapped[Optional[float53]]
    dec: Mapped[Optional[float53]]
    glon: Mapped[Optional[float53]]
    glat: Mapped[Optional[float53]]
    jmag: Mapped[Optional[float]] = mapped_column(Float)
    jerr: Mapped[Optional[float]] = mapped_column(Float)
    hmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    herr: Mapped[Optional[float]] = mapped_column(Float)
    kmag: Mapped[Optional[float]] = mapped_column(Float)
    kerr: Mapped[Optional[float]] = mapped_column(Float)
    src_h: Mapped[Optional[str]] = mapped_column(Text)
    targ_pmra: Mapped[Optional[float]] = mapped_column(Float)
    targ_pmdec: Mapped[Optional[float]] = mapped_column(Float)
    targ_pm_src: Mapped[Optional[str]] = mapped_column(Text)
    apogee_target1: Mapped[Optional[int]] = mapped_column(Integer)
    apogee_target2: Mapped[Optional[int]] = mapped_column(Integer)
    apogee2_target1: Mapped[Optional[int]] = mapped_column(Integer)
    apogee2_target2: Mapped[Optional[int]] = mapped_column(Integer)
    apogee2_target3: Mapped[Optional[int]] = mapped_column(Integer)
    apogee2_target4: Mapped[Optional[int]] = mapped_column(Integer)
    catalogid: Mapped[Optional[int]] = mapped_column(BigInteger, index=True)
    gaia_sourceid: Mapped[Optional[int]] = mapped_column(BigInteger)
    gaia_plx: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_plx_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_pmra: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_pmra_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_pmdec: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_pmdec_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_gmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_gerr: Mapped[Optional[float]] = mapped_column(Float)
    gaia_bpmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_bperr: Mapped[Optional[float]] = mapped_column(Float)
    gaia_rpmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_rperr: Mapped[Optional[float]] = mapped_column(Float)
    sdssv_apogee_target0: Mapped[Optional[int]] = mapped_column(Integer)
    firstcarton: Mapped[Optional[str]] = mapped_column(Text)
    targflags: Mapped[Optional[str]] = mapped_column(Text)
    nvisits: Mapped[Optional[int]] = mapped_column(Integer)
    ngoodvisits: Mapped[Optional[int]] = mapped_column(Integer)
    ngoodrvs: Mapped[Optional[int]] = mapped_column(Integer)
    starflag: Mapped[Optional[int]] = mapped_column(Integer)
    starflags: Mapped[Optional[str]] = mapped_column(Text)
    andflag: Mapped[Optional[int]] = mapped_column(Integer)
    andflags: Mapped[Optional[str]] = mapped_column(Text)
    vrad: Mapped[Optional[float]] = mapped_column(Float, index=True)
    vscatter: Mapped[Optional[float]] = mapped_column(Float)
    verr: Mapped[Optional[float]] = mapped_column(Float)
    vmederr: Mapped[Optional[float]] = mapped_column(Float)
    chisq: Mapped[Optional[float]] = mapped_column(Float)
    rv_teff: Mapped[Optional[float]] = mapped_column(Float)
    rv_tefferr: Mapped[Optional[float]] = mapped_column(Float)
    rv_logg: Mapped[Optional[float]] = mapped_column(Float)
    rv_loggerr: Mapped[Optional[float]] = mapped_column(Float)
    rv_feh: Mapped[Optional[float]] = mapped_column(Float)
    rv_feherr: Mapped[Optional[float]] = mapped_column(Float)
    rv_ccpfwhm: Mapped[Optional[float]] = mapped_column(Float)
    rv_autofwhm: Mapped[Optional[float]] = mapped_column(Float)
    n_components: Mapped[Optional[int]] = mapped_column(Integer)
    meanfib: Mapped[Optional[float]] = mapped_column(Float)
    sigfib: Mapped[Optional[float]] = mapped_column(Float)
    nres: Mapped[Optional[str]] = mapped_column(Text)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    cadence: Mapped[Optional[str]] = mapped_column(Text)
    program: Mapped[Optional[str]] = mapped_column(Text)
    category: Mapped[Optional[str]] = mapped_column(Text)
    gaia_release: Mapped[Optional[str]] = mapped_column(Text)
    sdss_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    sdss5_target_carton_pks: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_cartons: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_flagshex: Mapped[Optional[str]] = mapped_column(Text)
    ra_sdss_id: Mapped[Optional[float]] = mapped_column(Float(53))
    dec_sdss_id: Mapped[Optional[float]] = mapped_column(Float(53))
    sdss5_target_pks: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_catalogids: Mapped[Optional[str]] = mapped_column(Text)
    brightneicount: Mapped[Optional[int]] = mapped_column(Integer)
    brightneiflag: Mapped[Optional[int]] = mapped_column(Integer)
    brightneifluxfrac: Mapped[Optional[float]] = mapped_column(Float)


class StarLatest(Base):
    __tablename__ = "star_latest"
    __table_args__ = (
        UniqueConstraint("apred_vers", "telescope", "apogee_id", "starver"),
        {"schema": "apogee_drp"},
    )

    pk: Mapped[intpk]
    apogee_id: Mapped[Optional[str]] = mapped_column("apogee_id", Text)
    file: Mapped[Optional[str]] = mapped_column("file", Text)
    uri: Mapped[Optional[str]] = mapped_column("uri", Text)
    starver: Mapped[Optional[str]] = mapped_column("starver", Text)
    mjdbeg: Mapped[Optional[int]] = mapped_column("mjdbeg", Integer)
    mjdend: Mapped[Optional[int]] = mapped_column("mjdend", Integer)
    telescope: Mapped[Optional[str]] = mapped_column("telescope", Text)
    apred_vers: Mapped[Optional[str]] = mapped_column("apred_vers", Text)
    healpix: Mapped[Optional[int]] = mapped_column("healpix", Integer)
    snr: Mapped[Optional[float]] = mapped_column("snr", Float)
    ra: Mapped[Optional[float53]]
    dec: Mapped[Optional[float53]]
    glon: Mapped[Optional[float53]]
    glat: Mapped[Optional[float53]]
    jmag: Mapped[Optional[float]] = mapped_column("jmag", Float)
    jerr: Mapped[Optional[float]] = mapped_column("jerr", Float)
    hmag: Mapped[Optional[float]] = mapped_column("hmag", Float)
    herr: Mapped[Optional[float]] = mapped_column("herr", Float)
    kmag: Mapped[Optional[float]] = mapped_column("kmag", Float)
    kerr: Mapped[Optional[float]] = mapped_column("kerr", Float)
    src_h: Mapped[Optional[str]] = mapped_column("src_h", Text)
    targ_pmra: Mapped[Optional[float]] = mapped_column("targ_pmra", Float)
    targ_pmdec: Mapped[Optional[float]] = mapped_column("targ_pmdec", Float)
    targ_pm_src: Mapped[Optional[str]] = mapped_column("targ_pm_src", Text)
    apogee_target1: Mapped[Optional[int]] = mapped_column("apogee_target1", Integer)
    apogee_target2: Mapped[Optional[int]] = mapped_column("apogee_target2", Integer)
    apogee2_target1: Mapped[Optional[int]] = mapped_column("apogee2_target1", Integer)
    apogee2_target2: Mapped[Optional[int]] = mapped_column("apogee2_target2", Integer)
    apogee2_target3: Mapped[Optional[int]] = mapped_column("apogee2_target3", Integer)
    apogee2_target4: Mapped[Optional[int]] = mapped_column("apogee2_target4", Integer)
    catalogid: Mapped[Optional[int]] = mapped_column("catalogid", BigInteger)
    gaia_sourceid: Mapped[Optional[int]] = mapped_column("gaia_sourceid", BigInteger)
    gaia_plx: Mapped[Optional[float]] = mapped_column("gaia_plx", Float)
    gaia_plx_error: Mapped[Optional[float]] = mapped_column("gaia_plx_error", Float)
    gaia_pmra: Mapped[Optional[float]] = mapped_column("gaia_pmra", Float)
    gaia_pmra_error: Mapped[Optional[float]] = mapped_column("gaia_pmra_error", Float)
    gaia_pmdec: Mapped[Optional[float]] = mapped_column("gaia_pmdec", Float)
    gaia_pmdec_error: Mapped[Optional[float]] = mapped_column("gaia_pmdec_error", Float)
    gaia_gmag: Mapped[Optional[float]] = mapped_column("gaia_gmag", Float)
    gaia_gerr: Mapped[Optional[float]] = mapped_column("gaia_gerr", Float)
    gaia_bpmag: Mapped[Optional[float]] = mapped_column("gaia_bpmag", Float)
    gaia_bperr: Mapped[Optional[float]] = mapped_column("gaia_bperr", Float)
    gaia_rpmag: Mapped[Optional[float]] = mapped_column("gaia_rpmag", Float)
    gaia_rperr: Mapped[Optional[float]] = mapped_column("gaia_rperr", Float)
    sdssv_apogee_target0: Mapped[Optional[int]] = mapped_column("sdssv_apogee_target0", Integer)
    firstcarton: Mapped[Optional[str]] = mapped_column("firstcarton", Text)
    targflags: Mapped[Optional[str]] = mapped_column("targflags", Text)
    nvisits: Mapped[Optional[int]] = mapped_column("nvisits", Integer)
    ngoodvisits: Mapped[Optional[int]] = mapped_column("ngoodvisits", Integer)
    ngoodrvs: Mapped[Optional[int]] = mapped_column("ngoodrvs", Integer)
    starflag: Mapped[Optional[int]] = mapped_column("starflag", Integer)
    starflags: Mapped[Optional[str]] = mapped_column("starflags", Text)
    andflag: Mapped[Optional[int]] = mapped_column("andflag", Integer)
    andflags: Mapped[Optional[str]] = mapped_column("andflags", Text)
    vheliobary: Mapped[Optional[float]] = mapped_column("vheliobary", Float)
    vscatter: Mapped[Optional[float]] = mapped_column("vscatter", Float)
    verr: Mapped[Optional[float]] = mapped_column("verr", Float)
    vmederr: Mapped[Optional[float]] = mapped_column("vmederr", Float)
    chisq: Mapped[Optional[float]] = mapped_column("chisq", Float)
    rv_teff: Mapped[Optional[float]] = mapped_column("rv_teff", Float)
    rv_tefferr: Mapped[Optional[float]] = mapped_column("rv_tefferr", Float)
    rv_logg: Mapped[Optional[float]] = mapped_column("rv_logg", Float)
    rv_loggerr: Mapped[Optional[float]] = mapped_column("rv_loggerr", Float)
    rv_feh: Mapped[Optional[float]] = mapped_column("rv_feh", Float)
    rv_feherr: Mapped[Optional[float]] = mapped_column("rv_feherr", Float)
    rv_ccpfwhm: Mapped[Optional[float]] = mapped_column("rv_ccpfwhm", Float)
    rv_autofwhm: Mapped[Optional[float]] = mapped_column("rv_autofwhm", Float)
    n_components: Mapped[Optional[int]] = mapped_column("n_components", Integer)
    meanfib: Mapped[Optional[float]] = mapped_column("meanfib", Float)
    sigfib: Mapped[Optional[float]] = mapped_column("sigfib", Float)
    nres: Mapped[Optional[str]] = mapped_column("nres", Text)
    created: Mapped[Optional[datetime.datetime]] = mapped_column("created", DateTime(True))


class Test(Base):
    __tablename__ = "test"
    __table_args__ = (UniqueConstraint("id", "version", "telescope"), {"schema": "apogee_drp"})

    pk: Mapped[intpk]
    id: Mapped[Optional[str]] = mapped_column(Text)
    version: Mapped[Optional[str]] = mapped_column(Text)
    telescope: Mapped[Optional[str]] = mapped_column(Text)
    width: Mapped[Optional[str]] = mapped_column(Text)
    flux: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))


class Version(Base):
    __tablename__ = "version"

    pk: Mapped[intpk]
    name: Mapped[Optional[str]] = mapped_column(Text)
    type: Mapped[Optional[str]] = mapped_column(Text)
    current: Mapped[Optional[bool]] = mapped_column(Boolean)
    datarelease: Mapped[Optional[str]] = mapped_column(Text)
    modified: Mapped[Optional[str]] = mapped_column(Text)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))


class Visit(Base):
    __tablename__ = "visit"
    __table_args__ = (
        UniqueConstraint("apred_vers", "telescope", "plate", "mjd", "fiberid"),
        Index("visit_apred_pk_idx", "apred_vers", "pk"),
        {"schema": "apogee_drp"},
    )

    pk: Mapped[intpk]
    apogee_id: Mapped[Optional[str]] = mapped_column(Text, index=True)
    target_id: Mapped[Optional[str]] = mapped_column(Text)
    file: Mapped[Optional[str]] = mapped_column(Text)
    uri: Mapped[Optional[str]] = mapped_column(Text)
    fiberid: Mapped[Optional[int]] = mapped_column(SmallInteger, index=True)
    plate: Mapped[Optional[str]] = mapped_column(Text, index=True)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    survey: Mapped[Optional[str]] = mapped_column(Text)
    field: Mapped[Optional[str]] = mapped_column(Text, index=True)
    programname: Mapped[Optional[str]] = mapped_column(Text)
    objtype: Mapped[Optional[str]] = mapped_column(Text)
    ra: Mapped[Optional[float53]]
    dec: Mapped[Optional[float53]]
    glon: Mapped[Optional[float53]]
    glat: Mapped[Optional[float53]]
    jmag: Mapped[Optional[float]] = mapped_column(Float)
    jerr: Mapped[Optional[float]] = mapped_column(Float)
    hmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    herr: Mapped[Optional[float]] = mapped_column(Float)
    kmag: Mapped[Optional[float]] = mapped_column(Float)
    kerr: Mapped[Optional[float]] = mapped_column(Float)
    src_h: Mapped[Optional[str]] = mapped_column(Text)
    pmra: Mapped[Optional[float]] = mapped_column(Float)
    pmdec: Mapped[Optional[float]] = mapped_column(Float)
    pm_src: Mapped[Optional[str]] = mapped_column(Text)
    apogee_target1: Mapped[Optional[int]] = mapped_column(Integer)
    apogee_target2: Mapped[Optional[int]] = mapped_column(Integer)
    apogee_target3: Mapped[Optional[int]] = mapped_column(Integer)
    apogee_target4: Mapped[Optional[int]] = mapped_column(Integer)
    catalogid: Mapped[Optional[int]] = mapped_column(BigInteger, index=True)
    gaia_sourceid: Mapped[Optional[int]] = mapped_column(BigInteger, index=True)
    gaia_plx: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_plx_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_pmra: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_pmra_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_pmdec: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_pmdec_error: Mapped[Optional[float]] = mapped_column(Float)
    gaia_gmag: Mapped[Optional[float]] = mapped_column(Float)
    gaia_gerr: Mapped[Optional[float]] = mapped_column(Float)
    gaia_bpmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_bperr: Mapped[Optional[float]] = mapped_column(Float)
    gaia_rpmag: Mapped[Optional[float]] = mapped_column(Float, index=True)
    gaia_rperr: Mapped[Optional[float]] = mapped_column(Float)
    sdssv_apogee_target0: Mapped[Optional[int]] = mapped_column(Integer)
    firstcarton: Mapped[Optional[str]] = mapped_column(Text)
    targflags: Mapped[Optional[str]] = mapped_column(Text)
    snr: Mapped[Optional[float]] = mapped_column(Float)
    starflag: Mapped[Optional[int]] = mapped_column(Integer)
    starflags: Mapped[Optional[str]] = mapped_column(Text)
    dateobs: Mapped[Optional[str]] = mapped_column(Text)
    jd: Mapped[Optional[float53]]
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    assigned: Mapped[Optional[int]] = mapped_column(SmallInteger)
    on_target: Mapped[Optional[int]] = mapped_column(SmallInteger)
    valid: Mapped[Optional[int]] = mapped_column(SmallInteger)
    cadence: Mapped[Optional[str]] = mapped_column(Text)
    program: Mapped[Optional[str]] = mapped_column(Text)
    category: Mapped[Optional[str]] = mapped_column(Text)
    exptime: Mapped[Optional[float]] = mapped_column(Float)
    nframes: Mapped[Optional[int]] = mapped_column(Integer)
    gaia_release: Mapped[Optional[str]] = mapped_column(Text)
    design: Mapped[Optional[str]] = mapped_column(Text)
    sdss_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    sdss5_target_carton_pks: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_cartons: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_flagshex: Mapped[Optional[str]] = mapped_column(Text)
    ra_sdss_id: Mapped[Optional[float]] = mapped_column(Float(53))
    dec_sdss_id: Mapped[Optional[float]] = mapped_column(Float(53))
    healpix: Mapped[Optional[int]] = mapped_column(Integer)
    sdss5_target_pks: Mapped[Optional[str]] = mapped_column(Text)
    sdss5_target_catalogids: Mapped[Optional[str]] = mapped_column(Text)
    brightneicount: Mapped[Optional[int]] = mapped_column(Integer)
    brightneiflag: Mapped[Optional[int]] = mapped_column(Integer)
    brightneifluxfrac: Mapped[Optional[float]] = mapped_column(Float)
    too: Mapped[Optional[bool]] = mapped_column(Boolean)


class VisitLatest(Base):
    __tablename__ = "visit_latest"
    __table_args__ = (
        UniqueConstraint("apred_vers", "telescope", "plate", "mjd", "fiberid"),
        {"schema": "apogee_drp"},
    )

    apogee_id: Mapped[Optional[str]] = mapped_column("apogee_id", Text)
    target_id: Mapped[Optional[str]] = mapped_column("target_id", Text)
    catalogid: Mapped[int] = mapped_column("catalogid", primary_key=True)
    apred_vers: Mapped[str] = mapped_column("apred_vers", Text, primary_key=True)
    v_apred: Mapped[Optional[str]] = mapped_column("v_apred", Text)
    file: Mapped[str] = mapped_column("file", Text, primary_key=True)
    uri: Mapped[Optional[str]] = mapped_column("uri", Text)
    fiberid: Mapped[Optional[int]] = mapped_column("fiberid", SmallInteger)
    plate: Mapped[Optional[str]] = mapped_column("plate", Text)
    exptime: Mapped[Optional[float]] = mapped_column("exptime", Float)
    nframes: Mapped[Optional[int]] = mapped_column("nframes", Integer)
    mjd: Mapped[Optional[int]] = mapped_column("mjd", Integer)
    telescope: Mapped[Optional[str]] = mapped_column("telescope", Text)
    survey: Mapped[Optional[str]] = mapped_column("survey", Text)
    field: Mapped[Optional[str]] = mapped_column("field", Text)
    programname: Mapped[Optional[str]] = mapped_column("programname", Text)
    ra: Mapped[Optional[float53]]
    dec: Mapped[Optional[float53]]
    glon: Mapped[Optional[float53]]
    glat: Mapped[Optional[float53]]
    jmag: Mapped[Optional[float]] = mapped_column("jmag", Float)
    jerr: Mapped[Optional[float]] = mapped_column("jerr", Float)
    hmag: Mapped[Optional[float]] = mapped_column("hmag", Float)
    herr: Mapped[Optional[float]] = mapped_column("herr", Float)
    kmag: Mapped[Optional[float]] = mapped_column("kmag", Float)
    kerr: Mapped[Optional[float]] = mapped_column("kerr", Float)
    src_h: Mapped[Optional[str]] = mapped_column("src_h", Text)
    pmra: Mapped[Optional[float]] = mapped_column("pmra", Float)
    pmdec: Mapped[Optional[float]] = mapped_column("pmdec", Float)
    pm_src: Mapped[Optional[str]] = mapped_column("pm_src", Text)
    apogee_target1: Mapped[Optional[int]] = mapped_column("apogee_target1", Integer)
    apogee_target2: Mapped[Optional[int]] = mapped_column("apogee_target2", Integer)
    apogee_target3: Mapped[Optional[int]] = mapped_column("apogee_target3", Integer)
    apogee_target4: Mapped[Optional[int]] = mapped_column("apogee_target4", Integer)
    sdssv_apogee_target0: Mapped[Optional[int]] = mapped_column("sdssv_apogee_target0", Integer)
    firstcarton: Mapped[Optional[str]] = mapped_column("firstcarton", Text)
    cadence: Mapped[Optional[str]] = mapped_column("cadence", Text)
    program: Mapped[Optional[str]] = mapped_column("program", Text)
    category: Mapped[Optional[str]] = mapped_column("category", Text)
    targflags: Mapped[Optional[str]] = mapped_column("targflags", Text)
    gaia_plx: Mapped[Optional[float]] = mapped_column("gaia_plx", Float)
    gaia_plx_error: Mapped[Optional[float]] = mapped_column("gaia_plx_error", Float)
    gaia_pmra: Mapped[Optional[float]] = mapped_column("gaia_pmra", Float)
    gaia_pmra_error: Mapped[Optional[float]] = mapped_column("gaia_pmra_error", Float)
    gaia_pmdec: Mapped[Optional[float]] = mapped_column("gaia_pmdec", Float)
    gaia_pmdec_error: Mapped[Optional[float]] = mapped_column("gaia_pmdec_error", Float)
    gaia_gmag: Mapped[Optional[float]] = mapped_column("gaia_gmag", Float)
    gaia_gerr: Mapped[Optional[float]] = mapped_column("gaia_gerr", Float)
    gaia_bpmag: Mapped[Optional[float]] = mapped_column("gaia_bpmag", Float)
    gaia_bperr: Mapped[Optional[float]] = mapped_column("gaia_bperr", Float)
    gaia_rpmag: Mapped[Optional[float]] = mapped_column("gaia_rpmag", Float)
    gaia_rperr: Mapped[Optional[float]] = mapped_column("gaia_rperr", Float)
    snr: Mapped[Optional[float]] = mapped_column("snr", Float)
    starflag: Mapped[Optional[int]] = mapped_column("starflag", Integer)
    starflags: Mapped[Optional[str]] = mapped_column("starflags", Text)
    dateobs: Mapped[Optional[str]] = mapped_column("dateobs", Text)
    jd: Mapped[Optional[float53]]
    starver: Mapped[Optional[str]] = mapped_column("starver", Text)
    bc: Mapped[Optional[float]] = mapped_column("bc", Float)
    vtype: Mapped[Optional[int]] = mapped_column("vtype", SmallInteger)
    vrel: Mapped[Optional[float]] = mapped_column("vrel", Float)
    vrelerr: Mapped[Optional[float]] = mapped_column("vrelerr", Float)
    vrad: Mapped[Optional[float]] = mapped_column("vrad", Float)
    chisq: Mapped[Optional[float]] = mapped_column("chisq", Float)
    rv_teff: Mapped[Optional[float]] = mapped_column("rv_teff", Float)
    rv_feh: Mapped[Optional[float]] = mapped_column("rv_feh", Float)
    rv_logg: Mapped[Optional[float]] = mapped_column("rv_logg", Float)
    xcorr_vrel: Mapped[Optional[float]] = mapped_column("xcorr_vrel", Float)
    xcorr_vrelerr: Mapped[Optional[float]] = mapped_column("xcorr_vrelerr", Float)
    xcorr_vrad: Mapped[Optional[float]] = mapped_column("xcorr_vrad", Float)
    n_components: Mapped[Optional[int]] = mapped_column("n_components", Integer)
    rv_components: Mapped[Optional[list[float]]] = mapped_column("rv_components", ARRAY(Float()))
    goodvisit: Mapped[Optional[bool]] = mapped_column("goodvisit", Boolean)

class VisitStatus(Base):
    __tablename__ = "visit_status"

    pk: Mapped[intpk]
    planfile: Mapped[Optional[str]] = mapped_column(Text)
    logfile: Mapped[Optional[str]] = mapped_column(Text)
    errfile: Mapped[Optional[str]] = mapped_column(Text)
    apred_vers: Mapped[Optional[str]] = mapped_column(Text)
    instrument: Mapped[Optional[str]] = mapped_column(Text, index=True)
    telescope: Mapped[Optional[str]] = mapped_column(Text, index=True)
    platetype: Mapped[Optional[str]] = mapped_column(Text)
    mjd: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    plate: Mapped[Optional[int]] = mapped_column(Integer, index=True)
    nobj: Mapped[Optional[int]] = mapped_column(Integer)
    pbskey: Mapped[Optional[str]] = mapped_column(Text)
    checktime: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime)
    ap3d_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    ap3d_nexp_success: Mapped[Optional[int]] = mapped_column(Integer)
    ap2d_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    ap2d_nexp_success: Mapped[Optional[int]] = mapped_column(Integer)
    apcframe_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    apcframe_nexp_success: Mapped[Optional[int]] = mapped_column(Integer)
    applate_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    apvisit_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    apvisit_nobj_success: Mapped[Optional[int]] = mapped_column(Integer)
    apvisitsum_success: Mapped[Optional[bool]] = mapped_column(Boolean)
    success: Mapped[Optional[bool]] = mapped_column(Boolean)
    created: Mapped[datetime.datetime] = mapped_column(DateTime(True), nullable=False, server_default=text("now()"))
    v_apred: Mapped[Optional[str]] = mapped_column(Text)
    configid: Mapped[Optional[str]] = mapped_column(Text)
    designid: Mapped[Optional[str]] = mapped_column(Text)
    fieldid: Mapped[Optional[str]] = mapped_column(Text)


def define_relations():
    """leaving this empty as relations were autogenerated"""
    pass


# prepare the base
database.add_base(Base)