# !usr/bin/env python
# -*- coding: utf-8 -*-
#

# this file was autogenerated with sqlacodegen and then adapted for sdssdb
# flake8: noqa: E501,E741
import datetime
from typing_extensions import Annotated
from typing import Optional
from sqlalchemy import (
    ARRAY,
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    LargeBinary,
    SmallInteger,
    String,
    text,
)
from sqlalchemy.orm import declared_attr, Mapped, mapped_column, relationship

from sdssdb.sqlalchemy.sdss5db import SDSS5dbBase, database


SCHEMA = "boss_drp"
float53 = Annotated[float, 53]
intpk = Annotated[int, mapped_column(primary_key=True)]


class Base(SDSS5dbBase):
    __abstract__ = True
    _schema = SCHEMA
    _relations = "define_relations"
    type_annotation_map = {
        float53: Float(53),
    }

    @declared_attr
    def __table_args__(cls):
        return {"schema": cls._schema}



class BossVersion(Base):
    """model for boss version table"""
    __tablename__ = "boss_version"

    id: Mapped[intpk]
    ipl: Mapped[Optional[int]] = mapped_column(SmallInteger)
    run2d: Mapped[Optional[str]] = mapped_column(String)
    run1d: Mapped[Optional[str]] = mapped_column(String)
    is_default: Mapped[Optional[bool]] = mapped_column(Boolean)
    is_epoch: Mapped[Optional[bool]] = mapped_column(Boolean)
    is_custom: Mapped[Optional[bool]] = mapped_column(Boolean)
    custom_name: Mapped[Optional[str]] = mapped_column(String)
    created: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    modified: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text('now()'))
    sdssc2bv: Mapped[Optional[int]] = mapped_column(Integer)

    boss_field: Mapped[list['BossField']] = relationship(back_populates='boss_version')
    boss_spectrum: Mapped[list['BossSpectrum']] = relationship(back_populates='boss_version')
    boss_spectrum_line: Mapped[list['BossSpectrumLine']] = relationship(back_populates='boss_version')


class BossField(Base):
    """model for boss field table"""
    __tablename__ = "boss_field"

    id: Mapped[intpk]
    boss_version_id: Mapped[int] = mapped_column(ForeignKey("boss_drp.boss_version.id"), nullable=False)
    field: Mapped[Optional[int]] = mapped_column(Integer)
    designs: Mapped[Optional[str]] = mapped_column(String)
    configs: Mapped[Optional[str]] = mapped_column(String)
    mjd: Mapped[Optional[int]] = mapped_column(Integer)
    observatory: Mapped[Optional[str]] = mapped_column(String)
    run2d: Mapped[Optional[str]] = mapped_column(String)
    run1d: Mapped[Optional[str]] = mapped_column(String)
    racen: Mapped[Optional[float]] = mapped_column(Float)
    deccen: Mapped[Optional[float]] = mapped_column(Float)
    epoch: Mapped[Optional[float]] = mapped_column(Float)
    cartid: Mapped[Optional[str]] = mapped_column(String)
    tai: Mapped[Optional[float53]]
    tai_beg: Mapped[Optional[float53]]
    tai_end: Mapped[Optional[float53]]
    airmass: Mapped[Optional[float]] = mapped_column(Float)
    exptime: Mapped[Optional[float]] = mapped_column(Float)
    mapname: Mapped[Optional[str]] = mapped_column(String)
    tileid: Mapped[Optional[int]] = mapped_column(Integer)
    designid: Mapped[Optional[int]] = mapped_column(Integer)
    survey: Mapped[Optional[str]] = mapped_column(String)
    programname: Mapped[Optional[str]] = mapped_column(String)
    chunk: Mapped[Optional[str]] = mapped_column(String)
    fieldquality: Mapped[Optional[str]] = mapped_column(String)
    fieldsn2: Mapped[Optional[float]] = mapped_column(Float)
    deredsn2: Mapped[Optional[float]] = mapped_column(Float)
    qsurvey: Mapped[Optional[int]] = mapped_column(Integer)
    mjdlist: Mapped[Optional[str]] = mapped_column(String)
    nexp: Mapped[Optional[int]] = mapped_column(Integer)
    nexp_b1: Mapped[Optional[int]] = mapped_column(Integer)
    nexp_r1: Mapped[Optional[int]] = mapped_column(Integer)
    nexp_b2: Mapped[Optional[int]] = mapped_column(Integer)
    nexp_r2: Mapped[Optional[int]] = mapped_column(Integer)
    expt_b1: Mapped[Optional[float]] = mapped_column(Float)
    expt_r1: Mapped[Optional[float]] = mapped_column(Float)
    expt_b2: Mapped[Optional[float]] = mapped_column(Float)
    expt_r2: Mapped[Optional[float]] = mapped_column(Float)
    sn2_g1: Mapped[Optional[float]] = mapped_column(Float)
    sn2_r1: Mapped[Optional[float]] = mapped_column(Float)
    sn2_i1: Mapped[Optional[float]] = mapped_column(Float)
    sn2_g2: Mapped[Optional[float]] = mapped_column(Float)
    sn2_r2: Mapped[Optional[float]] = mapped_column(Float)
    sn2_i2: Mapped[Optional[float]] = mapped_column(Float)
    goffstd: Mapped[Optional[float]] = mapped_column(Float)
    grmsstd: Mapped[Optional[float]] = mapped_column(Float)
    roffstd: Mapped[Optional[float]] = mapped_column(Float)
    rrmsstd: Mapped[Optional[float]] = mapped_column(Float)
    ioffstd: Mapped[Optional[float]] = mapped_column(Float)
    irmsstd: Mapped[Optional[float]] = mapped_column(Float)
    groffstd: Mapped[Optional[float]] = mapped_column(Float)
    grrmsstd: Mapped[Optional[float]] = mapped_column(Float)
    rioffstd: Mapped[Optional[float]] = mapped_column(Float)
    rirmsstd: Mapped[Optional[float]] = mapped_column(Float)
    goffgal: Mapped[Optional[float]] = mapped_column(Float)
    grmsgal: Mapped[Optional[float]] = mapped_column(Float)
    roffgal: Mapped[Optional[float]] = mapped_column(Float)
    rrmsgal: Mapped[Optional[float]] = mapped_column(Float)
    ioffgal: Mapped[Optional[float]] = mapped_column(Float)
    irmsgal: Mapped[Optional[float]] = mapped_column(Float)
    groffgal: Mapped[Optional[float]] = mapped_column(Float)
    grrmsgal: Mapped[Optional[float]] = mapped_column(Float)
    rioffgal: Mapped[Optional[float]] = mapped_column(Float)
    rirmsgal: Mapped[Optional[float]] = mapped_column(Float)
    nguide: Mapped[Optional[int]] = mapped_column(Integer)
    seeing20: Mapped[Optional[float]] = mapped_column(Float)
    seeing50: Mapped[Optional[float]] = mapped_column(Float)
    seeing80: Mapped[Optional[float]] = mapped_column(Float)
    rmsoff20: Mapped[Optional[float]] = mapped_column(Float)
    rmsoff50: Mapped[Optional[float]] = mapped_column(Float)
    rmsoff80: Mapped[Optional[float]] = mapped_column(Float)
    airtemp: Mapped[Optional[float]] = mapped_column(Float)
    xsigma: Mapped[Optional[float]] = mapped_column(Float)
    xsigmin: Mapped[Optional[float]] = mapped_column(Float)
    xsigmax: Mapped[Optional[float]] = mapped_column(Float)
    wsigma: Mapped[Optional[float]] = mapped_column(Float)
    wsigmin: Mapped[Optional[float]] = mapped_column(Float)
    wsigmax: Mapped[Optional[float]] = mapped_column(Float)
    xchi2: Mapped[Optional[float]] = mapped_column(Float)
    xchi2min: Mapped[Optional[float]] = mapped_column(Float)
    xchi2max: Mapped[Optional[float]] = mapped_column(Float)
    skychi2: Mapped[Optional[float]] = mapped_column(Float)
    schi2min: Mapped[Optional[float]] = mapped_column(Float)
    schi2max: Mapped[Optional[float]] = mapped_column(Float)
    fbadpix: Mapped[Optional[float]] = mapped_column(Float)
    fbadpix1: Mapped[Optional[float]] = mapped_column(Float)
    fbadpix2: Mapped[Optional[float]] = mapped_column(Float)
    n_total: Mapped[Optional[int]] = mapped_column(Integer)
    n_galaxy: Mapped[Optional[int]] = mapped_column(Integer)
    n_qso: Mapped[Optional[int]] = mapped_column(Integer)
    n_star: Mapped[Optional[int]] = mapped_column(Integer)
    n_unknown: Mapped[Optional[int]] = mapped_column(Integer)
    n_sky: Mapped[Optional[int]] = mapped_column(Integer)
    n_std: Mapped[Optional[int]] = mapped_column(Integer)
    n_target_qso: Mapped[Optional[int]] = mapped_column(Integer)
    n_target_main: Mapped[Optional[int]] = mapped_column(Integer)
    n_target_lrg1: Mapped[Optional[int]] = mapped_column(Integer)
    n_target_lrg2: Mapped[Optional[int]] = mapped_column(Integer)
    n_target_elg: Mapped[Optional[int]] = mapped_column(Integer)
    success_main: Mapped[Optional[float]] = mapped_column(Float)
    success_lrg1: Mapped[Optional[float]] = mapped_column(Float)
    success_lrg2: Mapped[Optional[float]] = mapped_column(Float)
    success_elg: Mapped[Optional[float]] = mapped_column(Float)
    success_qso: Mapped[Optional[float]] = mapped_column(Float)
    status2d: Mapped[Optional[str]] = mapped_column(String)
    statuscombine: Mapped[Optional[str]] = mapped_column(String)
    status1d: Mapped[Optional[str]] = mapped_column(String)
    public: Mapped[Optional[str]] = mapped_column(String)
    qualcomments: Mapped[Optional[str]] = mapped_column(String)
    moon_frac: Mapped[Optional[float]] = mapped_column(Float)
    field_cadence: Mapped[Optional[str]] = mapped_column(String)
    created: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    modified: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text("now()"))
    design_vers: Mapped[Optional[str]] = mapped_column(String)
    design_mode: Mapped[Optional[str]] = mapped_column(String)

    boss_version: Mapped["BossVersion"] = relationship(back_populates="boss_field")


class BossSpectrum(Base):
    __tablename__ = "boss_spectrum"

    id: Mapped[intpk]
    boss_version_id: Mapped[int] = mapped_column(ForeignKey("boss_drp.boss_version.id"), nullable=False)
    field: Mapped[Optional[int]] = mapped_column(Integer)
    mjd: Mapped[Optional[int]] = mapped_column(Integer)
    mjd_final: Mapped[Optional[float]] = mapped_column(Float)
    obs: Mapped[Optional[str]] = mapped_column(String)
    run2d: Mapped[Optional[str]] = mapped_column(String)
    run1d: Mapped[Optional[str]] = mapped_column(String)
    nexp: Mapped[Optional[int]] = mapped_column(SmallInteger)
    exptime: Mapped[Optional[float]] = mapped_column(Float)
    target_index: Mapped[Optional[int]] = mapped_column(Integer)
    spec_file: Mapped[Optional[str]] = mapped_column(String)
    programname: Mapped[Optional[str]] = mapped_column(String)
    survey: Mapped[Optional[str]] = mapped_column(String)
    cadence: Mapped[Optional[str]] = mapped_column(String)
    firstcarton: Mapped[Optional[str]] = mapped_column(String)
    sdss5_target_flags: Mapped[Optional[bytes]] = mapped_column(LargeBinary)
    objtype: Mapped[Optional[str]] = mapped_column(String)
    catalogid: Mapped[Optional[int]] = mapped_column(BigInteger)
    sdss_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    specobjid: Mapped[Optional[int]] = mapped_column(BigInteger)
    calibflux: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    calibflux_ivar: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    optical_prov: Mapped[Optional[str]] = mapped_column(String)
    mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    psfmag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    fiber2mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    catdb_mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    gri_gaia_transform: Mapped[Optional[int]] = mapped_column(BigInteger)
    gaia_bp_mag: Mapped[Optional[float]] = mapped_column(Float)
    gaia_rp_mag: Mapped[Optional[float]] = mapped_column(Float)
    gaia_g_mag: Mapped[Optional[float]] = mapped_column(Float)
    gaia_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    wise_mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    twomass_mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    guvcat_mag: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    ebv: Mapped[Optional[float]] = mapped_column(Float)
    ebv_type: Mapped[Optional[str]] = mapped_column(String)
    fiber_ra: Mapped[Optional[float53]]
    fiber_dec: Mapped[Optional[float53]]
    plug_ra: Mapped[Optional[float53]]
    plug_dec: Mapped[Optional[float53]]
    racat: Mapped[Optional[float53]]
    deccat: Mapped[Optional[float53]]
    coord_epoch: Mapped[Optional[float]] = mapped_column(Float)
    delta_ra: Mapped[Optional[float53]]
    delta_dec: Mapped[Optional[float53]]
    pmra: Mapped[Optional[float]] = mapped_column(Float)
    pmdec: Mapped[Optional[float]] = mapped_column(Float)
    parallax: Mapped[Optional[float]] = mapped_column(Float)
    fiber_offset: Mapped[Optional[int]] = mapped_column(Integer)
    lambda_eff: Mapped[Optional[float]] = mapped_column(Float)
    healpix: Mapped[Optional[int]] = mapped_column(Integer)
    healpixgrp: Mapped[Optional[int]] = mapped_column(SmallInteger)
    healpix_dir: Mapped[Optional[str]] = mapped_column(String)
    fieldquality: Mapped[Optional[str]] = mapped_column(String)
    exp_disp_med: Mapped[Optional[float53]]
    fieldsn2: Mapped[Optional[float]] = mapped_column(Float)
    spec1_g: Mapped[Optional[float]] = mapped_column(Float)
    spec1_r: Mapped[Optional[float]] = mapped_column(Float)
    spec1_i: Mapped[Optional[float]] = mapped_column(Float)
    spec2_g: Mapped[Optional[float]] = mapped_column(Float)
    spec2_r: Mapped[Optional[float]] = mapped_column(Float)
    spec2_i: Mapped[Optional[float]] = mapped_column(Float)
    sn_median: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    sn_median_all: Mapped[Optional[float]] = mapped_column(Float)
    airmass: Mapped[Optional[float]] = mapped_column(Float)
    seeing20: Mapped[Optional[float]] = mapped_column(Float)
    seeing50: Mapped[Optional[float]] = mapped_column(Float)
    seeing80: Mapped[Optional[float]] = mapped_column(Float)
    moon_dist: Mapped[Optional[float]] = mapped_column(Float)
    moon_phase: Mapped[Optional[float]] = mapped_column(Float)
    assigned: Mapped[Optional[bool]] = mapped_column(Boolean)
    on_target: Mapped[Optional[bool]] = mapped_column(Boolean)
    valid: Mapped[Optional[bool]] = mapped_column(Boolean)
    decollided: Mapped[Optional[bool]] = mapped_column(Boolean)
    anyandmask: Mapped[Optional[int]] = mapped_column(Integer)
    anyormask: Mapped[Optional[int]] = mapped_column(Integer)
    specprimary: Mapped[Optional[int]] = mapped_column(SmallInteger)
    specboss: Mapped[Optional[int]] = mapped_column(SmallInteger)
    boss_specobj_id: Mapped[Optional[int]] = mapped_column(Integer)
    nspecobs: Mapped[Optional[int]] = mapped_column(SmallInteger)
    spectroflux: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    spectroflux_ivar: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    spectrosynflux: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    spectrosynflux_ivar: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    spectroskyflux: Mapped[Optional[list[float]]] = mapped_column(ARRAY(Float()))
    wavemin: Mapped[Optional[float]] = mapped_column(Float)
    wavemax: Mapped[Optional[float]] = mapped_column(Float)
    wcoverage: Mapped[Optional[float]] = mapped_column(Float)
    objclass: Mapped[Optional[str]] = mapped_column(String)
    subclass: Mapped[Optional[str]] = mapped_column(String)
    z: Mapped[Optional[float]] = mapped_column(Float)
    z_err: Mapped[Optional[float]] = mapped_column(Float)
    zwarning: Mapped[Optional[int]] = mapped_column(Integer)
    rchi2: Mapped[Optional[float]] = mapped_column(Float)
    dof: Mapped[Optional[int]] = mapped_column(Integer)
    rchi2diff: Mapped[Optional[float]] = mapped_column(Float)
    tfile: Mapped[Optional[str]] = mapped_column(String)
    vdisp: Mapped[Optional[float]] = mapped_column(Float)
    vdisp_err: Mapped[Optional[float]] = mapped_column(Float)
    vdispz: Mapped[Optional[float]] = mapped_column(Float)
    vdispz_err: Mapped[Optional[float]] = mapped_column(Float)
    vdispchi2: Mapped[Optional[float]] = mapped_column(Float)
    vdispnpix: Mapped[Optional[float]] = mapped_column(Float)
    vdispdof: Mapped[Optional[int]] = mapped_column(Integer)
    chi68p: Mapped[Optional[float]] = mapped_column(Float)
    z_noqso: Mapped[Optional[float]] = mapped_column(Float)
    z_err_noqso: Mapped[Optional[float]] = mapped_column(Float)
    znum_noqso: Mapped[Optional[int]] = mapped_column(Integer)
    zwarning_noqso: Mapped[Optional[int]] = mapped_column(Integer)
    class_noqso: Mapped[Optional[str]] = mapped_column(String)
    subclass_noqso: Mapped[Optional[str]] = mapped_column(String)
    rchi2diff_noqso: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_rv: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_erv: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_rxc: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_teff: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_eteff: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_logg: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_elogg: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_feh: Mapped[Optional[float]] = mapped_column(Float)
    xcsao_efeh: Mapped[Optional[float]] = mapped_column(Float)
    created: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    modified: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text("now()"))
    gri_gaia_transform: Mapped[Optional[int]] = mapped_column(BigInteger)
    delta_ra: Mapped[Optional[float53]]
    delta_dec: Mapped[Optional[float53]]
    too: Mapped[Optional[bool]] = mapped_column(Boolean, server_default=text('false'))
    too_id: Mapped[Optional[int]] = mapped_column(BigInteger)

    boss_version: Mapped["BossVersion"] = relationship(back_populates="boss_spectrum")


class BossSpectrumLine(Base):
    __tablename__ = "boss_spectrum_line"

    id: Mapped[intpk]
    boss_version_id: Mapped[int] = mapped_column(ForeignKey("boss_drp.boss_version.id"), nullable=False)
    field: Mapped[Optional[int]] = mapped_column(Integer)
    mjd: Mapped[Optional[int]] = mapped_column(Integer)
    target_index: Mapped[Optional[int]] = mapped_column(Integer)
    catalogid: Mapped[Optional[int]] = mapped_column(BigInteger)
    sdss_id: Mapped[Optional[int]] = mapped_column(BigInteger)
    linename: Mapped[Optional[str]] = mapped_column(String)
    linewave: Mapped[Optional[float53]]
    linez: Mapped[Optional[float]] = mapped_column(Float)
    linez_err: Mapped[Optional[float]] = mapped_column(Float)
    linesigma: Mapped[Optional[float]] = mapped_column(Float)
    linesigma_err: Mapped[Optional[float]] = mapped_column(Float)
    linearea: Mapped[Optional[float]] = mapped_column(Float)
    linearea_err: Mapped[Optional[float]] = mapped_column(Float)
    lineew: Mapped[Optional[float]] = mapped_column(Float)
    lineew_err: Mapped[Optional[float]] = mapped_column(Float)
    linecontlevel: Mapped[Optional[float]] = mapped_column(Float)
    linecontlevel_err: Mapped[Optional[float]] = mapped_column(Float)
    linenpixleft: Mapped[Optional[int]] = mapped_column(Integer)
    linenpixright: Mapped[Optional[int]] = mapped_column(Integer)
    linedof: Mapped[Optional[float]] = mapped_column(Float)
    linechi2: Mapped[Optional[float]] = mapped_column(Float)
    created: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True))
    modified: Mapped[Optional[datetime.datetime]] = mapped_column(DateTime(True), server_default=text("now()"))
    obs: Mapped[Optional[str]] = mapped_column(String)
    boss_version: Mapped["BossVersion"] = relationship(back_populates="boss_spectrum_line")


def define_relations():
    """leaving this empty as relations were autogenerated"""
    pass


# prepare the base
database.add_base(Base)
