/*

SkyMapper Southern Sky Survey DR1.1 - http://skymapper.anu.edu.au

To download the file see: http://skymapper.anu.edu.au/_data/DR1.1/
Table columns: http://skymapper.anu.edu.au/table-browser/ (different order as the CSVs!)

At Utah: /uufs/chpc.utah.edu/common/home/sdss50/sdsswork/target/catalogs/skymapper/dr1.1

*/

CREATE TABLE catalogdb.skymapper_dr1_1 (
    object_id BIGINT,
    raj2000 DOUBLE PRECISION,
    dej2000 DOUBLE PRECISION,
    e_raj2000 INTEGER,
    e_dej2000 INTEGER,
    smss_j VARCHAR(18),
    mean_epoch DOUBLE PRECISION,
    rms_epoch REAL,
    glon REAL,
    glat REAL,
    flags SMALLINT,
    nimaflags INTEGER,
    ngood SMALLINT,
    ngood_min SMALLINT,
    nch_max SMALLINT,
    u_flags SMALLINT,
    u_nimaflags INTEGER,
    u_ngood SMALLINT,
    u_nch SMALLINT,
    u_nvisit SMALLINT,
    v_flags SMALLINT,
    v_nimaflags INTEGER,
    v_ngood SMALLINT,
    v_nch SMALLINT,
    v_nvisit SMALLINT,
    g_flags SMALLINT,
    g_nimaflags INTEGER,
    g_ngood SMALLINT,
    g_nch SMALLINT,
    g_nvisit SMALLINT,
    r_flags SMALLINT,
    r_nimaflags INTEGER,
    r_ngood SMALLINT,
    r_nch SMALLINT,
    r_nvisit SMALLINT,
    i_flags SMALLINT,
    i_nimaflags INTEGER,
    i_ngood SMALLINT,
    i_nch SMALLINT,
    i_nvisit SMALLINT,
    z_flags SMALLINT,
    z_nimaflags INTEGER,
    z_ngood SMALLINT,
    z_nch SMALLINT,
    z_nvisit SMALLINT,
    class_star REAL,
    radius_petro REAL,
    a REAL,
    e_a REAL,
    b REAL,
    e_b REAL,
    pa REAL,
    e_pa REAL,
    u_psf REAL,
    e_u_psf REAL,
    u_petro REAL,
    e_u_petro REAL,
    v_psf REAL,
    e_v_psf REAL,
    v_petro REAL,
    e_v_petro REAL,
    g_psf REAL,
    e_g_psf REAL,
    g_petro REAL,
    e_g_petro REAL,
    r_psf REAL,
    e_r_psf REAL,
    r_petro REAL,
    e_r_petro REAL,
    i_psf REAL,
    e_i_psf REAL,
    i_petro REAL,
    e_i_petro REAL,
    z_psf REAL,
    e_z_psf REAL,
    z_petro REAL,
    e_z_petro REAL,
    ebmv_sfd REAL,
    prox REAL,
    prox_id BIGINT,
    edr_id BIGINT,
    edr_dist REAL,
    twomass_key1 BIGINT,
    twomass_dist1 REAL,
    twomass_cat1 VARCHAR(3),
    twomass_key2 BIGINT,
    twomass_dist2 REAL,
    twomass_cat2 VARCHAR(3),
    allwise_cntr BIGINT,
    allwise_dist REAL,
    ucac4_mpos BIGINT,
    ucac4_dist REAL,
    apass_recno BIGINT,
    apass_dist REAL,
    gaia_dr1_id BIGINT,
    gaia_dr1_dist REAL,
    ps1_dr1_id BIGINT,
    ps1_dr1_dist REAL,
    galex_bcs_id BIGINT,
    galex_bcs_dist REAL,
    gaia_dr2_id1 BIGINT,
    gaia_dr2_dist1 REAL,
    gaia_dr2_id2 BIGINT,
    gaia_dr2_dist2 REAL
);
