#! /usr/bin/bash
# encoding: utf-8

psql -U sdss sdss5db -c "\copy catalogdb.erosita_agn_mock FROM $CATALOGDB_DIR/eRosita/mock/prepCSV/ummary_eRASS3_agn_SDSS_V_format.csv WITH CSV HEADER NULL 'NULL';"

psql -U sdss sdss5db -c "\copy catalogdb.erosita_clusters_mock FROM $CATALOGDB_DIR/eRosita/mock/prepCSV/ummary_eRASS3_clusters_SDSS_V_format.csv WITH CSV HEADER NULL 'NULL';"

