
-- PK
ALTER TABLE catalogdb.dtic_v8 ADD PRIMARY KEY (id);

-- Indices
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (ra);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (dec);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (gallong);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (gallat);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (Bmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (Vmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (umag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (gmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (rmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (imag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (zmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (Jmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (Hmag);
CREATE INDEX CONCURRENTLY ON catalogdb.dtic_v8 USING BTREE (Kmag);
