-- Based on the information in the below fits file.
-- ElBadryRix2018_wide_binaries.fits

create table catalogdb.elbadry_rix (
source_id2 bigint,
ra2 double precision,
dec2 double precision,
astrometric_chi2_al_2 double precision,
astrometric_n_good_obs_al2 integer,
phot_g_mean_flux_over_error2 double precision,
phot_rp_mean_flux_over_error2 double precision,
phot_bp_mean_flux_over_error2 double precision,
phot_bp_rp_excess_factor2 double precision,
pmra2 double precision,
pmra_error2 double precision,
pmdec2 double precision,
pmdec_error2 double precision,
phot_g_mean_mag2 double precision,
phot_bp_mean_mag2 double precision,
phot_rp_mean_mag2 double precision,
parallax2 double precision,
parallax_over_error2 double precision,
radial_velocity2 double precision,
radial_velocity_error2 double precision,
rv_nb_transits2 integer,
source_id bigint,
ra double precision,
dec double precision,
pmra double precision,
pmra_error double precision,
pmdec double precision,
pmdec_error double precision,
phot_g_mean_mag double precision,
phot_bp_mean_mag double precision,
phot_rp_mean_mag double precision,
parallax double precision,
parallax_over_error double precision,
astrometric_chi2_al double precision,
astrometric_n_good_obs_al integer,
phot_g_mean_flux_over_error double precision,
phot_rp_mean_flux_over_error double precision,
phot_bp_mean_flux_over_error double precision,
phot_bp_rp_excess_factor double precision,
radial_velocity double precision,
radial_velocity_error double precision,
rv_nb_transits integer,
pairdistance double precision,
binary_class char(4),
s_AU double precision
);
