-- This create table statement is based on the below link.
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_astrophysical_parameter_tables/ssec_dm_astrophysical_parameters.html

create table catalogdb.gaia_dr3_astrophysical_parameters(
solution_id bigint,  -- Solution Identifier (long)
source_id bigint,  -- Source Identifier (long)
classprob_dsc_combmod_quasar real,  -- Probability from DSC-Combmod of being a quasar (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_galaxy real,  -- Probability from DSC-Combmod of being a galaxy (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_star real,  -- Probability from DSC-Combmod of being a single star (but not a white dwarf) (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_whitedwarf real,  -- Probability from DSC-Combmod of being a white dwarf (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_combmod_binarystar real,  -- Probability from DSC-Combmod of being a binary star (data used: BP/RP spectrum, photometry, astrometry) (float)
classprob_dsc_specmod_quasar real,  -- Probability from DSC-Specmod of being a quasar (data used: BP/RP spectrum) (float)
classprob_dsc_specmod_galaxy real,  -- Probability from DSC-Specmod of being a galaxy (data used: BP/RP spectrum) (float)
classprob_dsc_specmod_star real,  -- Probability from DSC-Specmod of being a single star (but not a white dwarf) (data used: BP/RP spectrum) (float)
classprob_dsc_specmod_whitedwarf real,  -- Probability from DSC-Specmod of being a white dwarf (data used: BP/RP spectrum) (float)
classprob_dsc_specmod_binarystar real,  -- Probability from DSC-Specmod of being a binary star (data used: BP/RP spectrum) (float)
classprob_dsc_allosmod_quasar real,  -- Probability from DSC-Allosmod of being a quasar (data used: photometry, astrometry) (float)
classprob_dsc_allosmod_galaxy real,  -- Probability from DSC-Allosmod of being a galaxy (data used: photometry, astrometry) (float)
classprob_dsc_allosmod_star real,  -- Probability from DSC-Allosmod of being a star (data used: photometry, astrometry) (float)
teff_gspphot real,  -- Effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
teff_gspphot_lower real,  -- Lower confidence level (16%) of effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
teff_gspphot_upper real,  -- Upper confidence level (84%) of effective temperature from GSP-Phot Aeneas best library using BP/RP spectra (float, Temperature[K])
logg_gspphot real,  -- Surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
logg_gspphot_lower real,  -- Lower confidence level (16%) of surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
logg_gspphot_upper real,  -- Upper confidence level (84%) of surface gravity from GSP-Phot Aeneas best library using BP/RP spectra (float, GravitySurface[log cgs])
mh_gspphot real,  -- Iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
mh_gspphot_lower real,  -- Lower confidence level (16%) of iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
mh_gspphot_upper real,  -- Upper confidence level (84%) of iron abundance from GSP-Phot Aeneas best library using BP/RP spectra (float, Abundances[dex])
distance_gspphot real,  -- Distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
distance_gspphot_lower real,  -- Lower confidence level (16%) of distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
distance_gspphot_upper real,  -- Upper confidence level (84%) of distance from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[pc])
azero_gspphot real,  -- Monochromatic extinction 𝐴0 at 541.4 nm from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
azero_gspphot_lower real,  -- Lower confidence level (16%) of monochromatic extinction 𝐴0 at 541.4 nm from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
azero_gspphot_upper real,  -- Upper confidence level (84%) of monochromatic extinction 𝐴0 at 541.4 nm from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ag_gspphot real,  -- Extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ag_gspphot_lower real,  -- Lower confidence level (16%) of extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ag_gspphot_upper real,  -- Upper confidence level (84%) of extinction in G band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
abp_gspphot real,  -- Extinction in 𝐺BP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
abp_gspphot_lower real,  -- Lower confidence level (16%) of extinction in 𝐺BP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
abp_gspphot_upper real,  -- Upper confidence level (84%) of extinction in 𝐺BP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
arp_gspphot real,  -- Extinction in 𝐺RP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
arp_gspphot_lower real,  -- Lower confidence level (16%) of extinction in 𝐺RP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
arp_gspphot_upper real,  -- Upper confidence level (84%) of extinction in 𝐺RP band from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ebpminrp_gspphot real,  -- Reddening 𝐸(𝐺BP−𝐺RP) from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ebpminrp_gspphot_lower real,  -- Lower confidence level (16%) of reddening 𝐸(𝐺BP−𝐺RP) from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
ebpminrp_gspphot_upper real,  -- Upper confidence level (84%) of reddening 𝐸(𝐺BP−𝐺RP) from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
mg_gspphot real,  -- Absolute magnitude 𝑀G from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
mg_gspphot_lower real,  -- Lower confidence level (16%) of absolute magnitude 𝑀G from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
mg_gspphot_upper real,  -- Upper confidence level (84%) of absolute magnitude 𝑀G from GSP-Phot Aeneas best library using BP/RP spectra (float, Magnitude[mag])
radius_gspphot real,  -- Radius from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[Solar Radius])
radius_gspphot_lower real,  -- Lower confidence level (16%) of radius from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[Solar Radius])
radius_gspphot_upper real,  -- Upper confidence level (84%) of radius from GSP-Phot Aeneas best library using BP/RP spectra (float, Length & Distance[Solar Radius])
logposterior_gspphot real,  -- Goodness-of-fit score (mean log-posterior of MCMC) of GSP-Phot Aeneas MCMC best library (float)
mcmcaccept_gspphot real,  -- MCMC acceptance rate of GSP-Phot Aeneas MCMC best library (float)
libname_gspphot text,  -- Name of library that achieves the highest mean log-posterior in MCMC samples and was used to derive GSP-Phot parameters in this table (string)
teff_gspspec real,  -- Effective temperature from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Temperature[K])
teff_gspspec_lower real,  -- 16th percentile of effective temperature from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Temperature[K])
teff_gspspec_upper real,  -- 84th percentile of effective temperature from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Temperature[K])
logg_gspspec real,  -- Logarithm of the stellar surface gravity from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, GravitySurface[log cgs])
logg_gspspec_lower real,  -- 16th percentile of the logarithm of the stellar surface gravity from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, GravitySurface[log cgs])
logg_gspspec_upper real,  -- 84th percentile of the logarithm of the stellar surface gravity from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, GravitySurface[log cgs])
mh_gspspec real,  -- Global metallicity [M/H] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
mh_gspspec_lower real,  -- 16th percentile of global metallicity [M/H] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
mh_gspspec_upper real,  -- 84th percentile of global metallicity [M/H] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
alphafe_gspspec real,  -- Abundance of alpha-elements [alpha/Fe] with respect to iron from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
alphafe_gspspec_lower real,  -- 16th percentile of the abundance of alpha-elements [alpha/Fe] with respect to iron from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
alphafe_gspspec_upper real,  -- 84th percentile of the abundance of alpha-elements [alpha/Fe] with respect to iron from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
fem_gspspec real,  -- Abundance of neutral iron [Fe/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in fem_gspspec_nlines (float, Abundances[dex])
fem_gspspec_lower real,  -- 16th percentile of the abundance of neutral iron [Fe/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
fem_gspspec_upper real,  -- 84th percentile of the abundance of neutral iron [Fe/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
fem_gspspec_nlines integer,  -- Number of lines used for [Fe/M] abundance estimation (int)
fem_gspspec_linescatter real,  -- Uncertainty estimation of [Fe/M] abundance using N lines of the element, given in fem_gspspec_nlines (float, Abundances[dex])
sife_gspspec real,  -- Abundance of silicon [Si/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in sife_gspspec_nlines (float, Abundances[dex])
sife_gspspec_lower real,  -- 16th percentile of the abundance of silicon [Si/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
sife_gspspec_upper real,  -- 84th percentile of the abundance of silicon [Si/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
sife_gspspec_nlines integer,  -- Number of lines used for [Si/Fe] abundance estimation (int)
sife_gspspec_linescatter real,  -- Uncertainty estimation of [Si/Fe] abundance using N lines of the element, given in sife_gspspec_nlines (float, Abundances[dex])
cafe_gspspec real,  -- Abundance of calcium [Ca/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in cafe_gspspec_nlines (float, Abundances[dex])
cafe_gspspec_lower real,  -- 16th percentile of the abundance of calcium [Ca/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
cafe_gspspec_upper real,  -- 84th percentile of the abundance of calcium [Ca/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
cafe_gspspec_nlines integer,  -- Number of lines used for [Ca/Fe] abundance estimation (int)
cafe_gspspec_linescatter real,  -- Uncertainty estimation of [Ca/Fe] abundance using N lines of the element, given in cafe_gspspec_nlines (float, Abundances[dex])
tife_gspspec real,  -- Abundance of titanium [Ti/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in tife_gspspec_nlines (float, Abundances[dex])
tife_gspspec_lower real,  -- 16th percentile of the abundance of titanium [Ti/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
tife_gspspec_upper real,  -- 84th percentile of the abundance of titanium [Ti/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
tife_gspspec_nlines integer,  -- Number of lines used for [Ti/Fe] abundance estimation (int)
tife_gspspec_linescatter real,  -- Uncertainty estimation of [Ti/Fe] abundance using N lines of the element, given in tife_gspspec_nlines (float, Abundances[dex])
mgfe_gspspec real,  -- Abundance of magnesium [Mg/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in mgfe_gspspec_nlines (float, Abundances[dex])
mgfe_gspspec_lower real,  -- 16th percentile of the abundance of magnesium [Mg/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
mgfe_gspspec_upper real,  -- 84th percentile of the abundance of magnesium [Mg/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
mgfe_gspspec_nlines integer,  -- Number of lines used for [Mg/Fe] abundance estimation (int)
mgfe_gspspec_linescatter real,  -- Uncertainty estimation of [Mg/Fe] abundance using N lines of the element, given in mgfe_gspspec_nlines (float, Abundances[dex])
ndfe_gspspec real,  -- Abundance of neodymium [Nd/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in ndfe_gspspec_nlines (float, Abundances[dex])
ndfe_gspspec_lower real,  -- 16th percentile of the abundance of neodymium [Nd/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
ndfe_gspspec_upper real,  -- 84th percentile of the abundance of neodymium [Nd/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
ndfe_gspspec_nlines integer,  -- Number of lines used for [Nd/Fe] abundance estimation (int)
ndfe_gspspec_linescatter real,  -- Uncertainty estimation of [Nd/Fe] abundance using N lines of the element, given in ndfe_gspspec_nlines (float, Abundances[dex])
feiim_gspspec real,  -- Abundance of ionised iron [FeII/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in feiim_gspspec_nlines (float, Abundances[dex])
feiim_gspspec_lower real,  -- 16th percentile of the abundance of ionised iron [FeII/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
feiim_gspspec_upper real,  -- 84th percentile of the abundance of ionised iron [FeII/M] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
feiim_gspspec_nlines integer,  -- Number of lines used for [FeII/M] abundance estimation (int)
feiim_gspspec_linescatter real,  -- Uncertainty estimation of [FeII/M] abundance using N lines of the element, given in feiim_gspspec_nlines (float, Abundances[dex])
sfe_gspspec real,  -- Abundance of sulphur [S/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in sfe_gspspec_nlines (float, Abundances[dex])
sfe_gspspec_lower real,  -- 16th percentile of the abundance of sulphur [S/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
sfe_gspspec_upper real,  -- 84th percentile of the abundance of sulphur [S/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
sfe_gspspec_nlines integer,  -- Number of lines used for [S/Fe] abundance estimation (int)
sfe_gspspec_linescatter real,  -- Uncertainty estimation of [S/Fe] abundance using N lines of the element, given in sfe_gspspec_nlines (float, Abundances[dex])
zrfe_gspspec real,  -- Abundance of zirconium [Zr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in zrfe_gspspec_nlines (float, Abundances[dex])
zrfe_gspspec_lower real,  -- 16th percentile of the abundance of zirconium [Zr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
zrfe_gspspec_upper real,  -- 84th percentile of the abundance of zirconium [Zr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
zrfe_gspspec_nlines integer,  -- Number of lines used for [Zr/Fe] abundance estimation (int)
zrfe_gspspec_linescatter real,  -- Uncertainty estimation of [Zr/Fe] abundance using N lines of the element, given in zrfe_gspspec_nlines (float, Abundances[dex])
nfe_gspspec real,  -- Abundance of nitrogen [N/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in nfe_gspspec_nlines (float, Abundances[dex])
nfe_gspspec_lower real,  -- 16th percentile of the abundance of nitrogen [N/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
nfe_gspspec_upper real,  -- 84th percentile of the abundance of nitrogen [N/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
nfe_gspspec_nlines integer,  -- Number of lines used for [N/Fe] abundance estimation (int)
nfe_gspspec_linescatter real,  -- Uncertainty estimation of [N/Fe] abundance using N lines of the element, given in nfe_gspspec_nlines (float, Abundances[dex])
crfe_gspspec real,  -- Abundance of chromium [Cr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in crfe_gspspec_nlines (float, Abundances[dex])
crfe_gspspec_lower real,  -- 16th percentile of the abundance of chromium [Cr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
crfe_gspspec_upper real,  -- 84th percentile of the abundance of chromium [Cr/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
crfe_gspspec_nlines integer,  -- Number of lines used for [Cr/Fe] abundance estimation (int)
crfe_gspspec_linescatter real,  -- Uncertainty estimation of [Cr/Fe] abundance using N lines of the element, given in crfe_gspspec_nlines (float, Abundances[dex])
cefe_gspspec real,  -- Abundance of cerium [Ce/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in cefe_gspspec_nlines (float, Abundances[dex])
cefe_gspspec_lower real,  -- 16th percentile of the abundance of cerium [Ce/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
cefe_gspspec_upper real,  -- 84th percentile of the abundance of cerium [Ce/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
cefe_gspspec_nlines integer,  -- Number of lines used for [Ce/Fe] abundance estimation (int)
cefe_gspspec_linescatter real,  -- Uncertainty estimation of [Ce/Fe] abundance using N lines of the element, given in cefe_gspspec_nlines (float, Abundances[dex])
nife_gspspec real,  -- Abundance of nickel [Ni/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations, applied to the individual N lines of the element, given in nife_gspspec_nlines (float, Abundances[dex])
nife_gspspec_lower real,  -- 16th percentile of the abundance of nickel [Ni/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
nife_gspspec_upper real,  -- 84th percentile of the abundance of nickel [Ni/Fe] from GSP-Spec MatisseGauguin using RVS spectra and Monte Carlo realisations (float, Abundances[dex])
nife_gspspec_nlines integer,  -- Number of lines used for [Ni/Fe] abundance estimation (int)
nife_gspspec_linescatter real,  -- Uncertainty estimation of [Ni/Fe] abundance using N lines of the element, given in nife_gspspec_nlines (float, Abundances[dex])
cn0ew_gspspec real,  -- Equivalent witdh of cyanogen absorption line, derived from RVS spectra (float, Length & Distance[nm])
cn0ew_gspspec_uncertainty real,  -- Uncertainty of equivalent witdh of cyanogen absorption line, derived from RVS spectra (float, Length & Distance[nm])
cn0_gspspec_centralline real,  -- Central wavelength of cyanogen line, derived from RVS spectra using DIB algorithm (float, Length & Distance[nm])
cn0_gspspec_width real,  -- Width of cyoanogen line, derived from RVS spectra using DIB algorithm (float, Length & Distance[nm])
dib_gspspec_lambda real,  -- DIB central wavelength from GSP-Spec MatisseGauguin using RVS spectra (float, Length & Distance[nm])
dib_gspspec_lambda_uncertainty real,  -- Uncertainty on DIB central wavelength from GSP-Spec MatisseGauguin using RVS spectra (float, Length & Distance[nm])
dibew_gspspec real,  -- Equivalent width of the DIB from GSP-Spec MatisseGauguin using RVS spectra (float, Length & Distance[Å])
dibew_gspspec_uncertainty real,  -- Global uncertainty on DIB equivalent width value using DIB algorithm (float, Length & Distance[Å])
dibewnoise_gspspec_uncertainty real,  -- Uncertainty on DIB equivalent width value occuring from noise part (float, Length & Distance[Å])
dibp0_gspspec real,  -- Depth (𝑝0 parameter) of the DIB derived from a Gaussian model fit (float)
dibp2_gspspec real,  -- Width (𝑝2 parameter) of the DIB derived from a Gaussian model fit (float, Length & Distance[Å])
dibp2_gspspec_uncertainty real,  -- Uncertainty on the dibp2_gspspec parameter (float, Length & Distance[Å])
dibqf_gspspec integer,  -- Quality flag of the DIB computation (int)
flags_gspspec text,  -- Catalogue flags for GSP-Spec MatisseGauguin (string)
logchisq_gspspec real,  -- Logarithm of the goodness-of-fit for the GSP-Spec MatisseGauguin parameters (float)
ew_espels_halpha real,  -- Halpha pseudo-equivalent width from ESP-ELS (float, Length & Distance[nm])
ew_espels_halpha_uncertainty real,  -- Uncertainty of the Halpha pseudo-equivalent width from ESP-ELS (float, Length & Distance[nm])
ew_espels_halpha_flag text,  -- Quality flag of the Halpha pseudo-equivalent width from ESP-ELS (string)
ew_espels_halpha_model real,  -- Halpha pseudo-equivalent width from ESP-ELS measured on the synthetic spectrum (float, Length & Distance[nm])
classlabel_espels text,  -- Adopted ELS class label from ESP-ELS (string)
classlabel_espels_flag text,  -- Quality flag of the adopted ELS class label from ESP-ELS (string)
classprob_espels_wcstar real,  -- Probability from ESP-ELS of being a Wolf-Rayet star of type WC (float)
classprob_espels_wnstar real,  -- Probability from ESP-ELS of being a Wolf-Rayet star of type WN (float)
classprob_espels_bestar real,  -- Probability from ESP-ELS of being a Be Star (float)
classprob_espels_ttauristar real,  -- Probability from ESP-ELS of being a T Tauri Star (float)
classprob_espels_herbigstar real,  -- Probability from ESP-ELS of being a Herbig Ae/Be Star (float)
classprob_espels_dmestar real,  -- Probability from ESP-ELS of being an active M dwarf Star (float)
classprob_espels_pne real,  -- Probability from ESP-ELS of being a planetary nebula (float)
azero_esphs real,  -- Monochromatic interstellar extinction, A0, from ESP-HS (float, Magnitude[mag])
azero_esphs_uncertainty real,  -- Uncertainty at a 68% confidence level on A0 from ESP-HS (float, Magnitude[mag])
ag_esphs real,  -- Intersterstellar extinction in G band from ESP-HS (float, Magnitude[mag])
ag_esphs_uncertainty real,  -- Uncertainty on 𝐴G from ESP-HS (float, Magnitude[mag])
ebpminrp_esphs real,  -- Reddening 𝐸(𝐺BP−𝐺RP) from ESP-HS (float, Magnitude[mag])
ebpminrp_esphs_uncertainty real,  -- Uncertainty on 𝐸(𝐺BP−𝐺RP) from ESP-HS (float, Magnitude[mag])
teff_esphs real,  -- Effective temperature from ESP-HS (float, Temperature[K])
teff_esphs_uncertainty real,  -- Uncertainty at a 68% confidence level on the effective temperature from ESP-HS (float, Temperature[K])
logg_esphs real,  -- Surface gravity from ESP-HS (float, GravitySurface[log cgs])
logg_esphs_uncertainty real,  -- Uncertainty at a 68% confidence level on the surface gravity from ESP-HS (float, GravitySurface[log cgs])
vsini_esphs real,  -- Projected rotational velocity from ESP-HS (float, Velocity[km s−1])
vsini_esphs_uncertainty real,  -- Uncertainty on the projected rotational velocity from ESP-HS (float, Velocity[km s−1])
flags_esphs text,  -- Quality flag of the ESP-HS parametrisation (string)
spectraltype_esphs text,  -- Spectral type from ESP-ELS (string)
activityindex_espcs real,  -- Chromospheric activity index from ESP-CS, measured on the calcium triplet using RVS spectra (float, Length & Distance[nm])
activityindex_espcs_uncertainty real,  -- Uncertainty in the chromospheric activity index from ESP-CS (float, Length & Distance[nm])
activityindex_espcs_input text,  -- Source of input stellar parameters for the computation of the activity index by ESP-CS (string)
teff_espucd real,  -- Effective temperature estimate from ESP-UCD based on the RP spectrum (float, Temperature[K])
teff_espucd_uncertainty real,  -- Uncertainty of the effective temperature estimate produced by ESP-UCD (float, Temperature[K])
flags_espucd text,  -- Quality flags of the ESP-UCD parameter estimates (string)
radius_flame real,  -- Radius of the star from FLAME using teff_gspphot and lum_flame (float, Length & Distance[Solar Radius])
radius_flame_lower real,  -- Lower confidence level (16%) of radius_flame (float, Length & Distance[Solar Radius])
radius_flame_upper real,  -- Upper confidence level (84%) of radius_flame (float, Length & Distance[Solar Radius])
lum_flame real,  -- Luminosity of the star from FLAME using G band magnitude, extinction (ag_gspphot), parallax or distance, and a bolometric correction bc_flame (float, Luminosity[Solar Luminosity])
lum_flame_lower real,  -- Lower confidence level (16%) of lum_flame (float, Luminosity[Solar Luminosity])
lum_flame_upper real,  -- Upper confidence level (84%) of lum_flame (float, Luminosity[Solar Luminosity])
mass_flame real,  -- Mass of the star from FLAME using stellar models, lum_flame, and teff_gspphot (float, Mass[Solar Mass])
mass_flame_lower real,  -- Lower confidence level (16%) of mass_flame (float, Mass[Solar Mass])
mass_flame_upper real,  -- Upper confidence level (84%) of mass_flame (float, Mass[Solar Mass])
age_flame real,  -- Age of the star from FLAME using stellar models, see mass_flame for details (float, Time[Gyr])
age_flame_lower real,  -- Lower confidence level (16%) of age_flame (float, Time[Gyr])
age_flame_upper real,  -- Upper confidence level (84%) of age_flame (float, Time[Gyr])
flags_flame text,  -- Flags indicating quality and processing information from FLAME (string)
evolstage_flame integer,  -- Evolutionary stage of the star from FLAME using stellar models, see mass_flame for details (int)
gravredshift_flame real,  -- Gravitational redshift from FLAME using radius_flame and logg_gspphot (float, Velocity[km s−1])
gravredshift_flame_lower real,  -- Lower confidence level (16%) of gravredshift_flame (float, Velocity[km s−1])
gravredshift_flame_upper real,  -- Upper confidence level (84%) of gravredshift_flame (float, Velocity[km s−1])
bc_flame real,  -- Bolometric correction used to derive lum_flame (float, Magnitude[mag])
mh_msc real,  -- Metallicity of the source treated as a binary system from MSC using BP/RP spectra and parallax (float, Abundances[dex])
mh_msc_upper real,  -- Upper confidence level (84%) of the metallicity from MSC using BP/RP spectra and parallax (float, Abundances[dex])
mh_msc_lower real,  -- Lower confidence level (16%) of the metallicity from MSC using BP/RP spectra and parallax (float, Abundances[dex])
azero_msc real,  -- Monochromatic extinction 𝐴0 at 541.4 nm of the source treated as a binary system from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
azero_msc_upper real,  -- Upper confidence level (84%) of monochromatic extinction 𝐴0 at 541.4 nm from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
azero_msc_lower real,  -- Lower confidence level (16%) of monochromatic extinction 𝐴0 at 541.4 nm from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
distance_msc real,  -- Distance from MSC using BP/RP spectra and parallax (float, Length & Distance[pc])
distance_msc_upper real,  -- Upper confidence level (84%) of distance from MSC using BP/RP spectra and parallax (float, Length & Distance[pc])
distance_msc_lower real,  -- Lower confidence level (16%) of distance from MSC using BP/RP spectra and parallax (float, Length & Distance[pc])
teff_msc1 real,  -- Effective temperature of the primary from MSC using BP/RP spectra and parallax (float, Temperature[K])
teff_msc1_upper real,  -- Upper confidence level (84%) of effective temperature of the primary from MSC using BP/RP spectra and parallax (float, Temperature[K])
teff_msc1_lower real,  -- Lower confidence level (16%) of effective temperature of the primary from MSC using BP/RP spectra and parallax (float, Temperature[K])
teff_msc2 real,  -- Effective temperature of the secondary from MSC using BP/RP spectra and parallax (float, Temperature[K])
teff_msc2_upper real,  -- Upper confidence level (84%) of effective temperature of the secondary from MSC using BP/RP spectra and parallax (float, Temperature[K])
teff_msc2_lower real,  -- Lower confidence level (16%) of effective temperature of the secondary from MSC using BP/RP spectra and parallax (float, Temperature[K])
logg_msc1 real,  -- Surface gravity of the primary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
logg_msc1_upper real,  -- Upper confidence level (84%) of surface gravity of the primary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
logg_msc1_lower real,  -- Lower confidence level (16%) of surface gravity of the primary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
logg_msc2 real,  -- Surface gravity of the secondary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
logg_msc2_upper real,  -- Upper confidence level (84%) of surface gravity of the secondary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
logg_msc2_lower real,  -- Lower confidence level (16%) of surface gravity of the secondary from MSC using BP/RP spectra and parallax (float, GravitySurface[log cgs])
ag_msc real,  -- Extinction in G band of the source treated as a binary system from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
ag_msc_upper real,  -- Upper confidence level (84%) of extinction in G band from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
ag_msc_lower real,  -- Lower confidence level (16%) of extinction in G band from MSC using BP/RP spectra and parallax (float, Magnitude[mag])
logposterior_msc real,  -- Goodness-of-fit score (normalised log-posterior) of MSC MCMC (float)
mcmcaccept_msc real,  -- Mean MCMC acceptance rate of MSC MCMC (float)
mcmcdrift_msc real,  -- Mean drift of the MSC MCMC chain in units of parameter standard deviation (float)
flags_msc text,  -- Flag indicating quality information from MSC (string)
neuron_oa_id bigint,  -- Identifier of the OA SOM map neuron that represents the source (long)
neuron_oa_dist float,  -- Distance between the source XP spectra and the OA neuron XP prototype that represents the source (float)
neuron_oa_dist_percentile_rank integer,  -- Percentile rank according to the distance distribution of the OA neuron that represents the source (int)
flags_oa text  -- Flags indicating quality and processing information from OA (string)
);
