CREATE TABLE sandbox.virac2 (
  sourceid BIGINT,
  astfit_epochs SMALLINT,
  astfit_params SMALLINT,
  duplicate SMALLINT,
  ref_epoch DOUBLE PRECISION,
  ra DOUBLE PRECISION,
  ra_error DOUBLE PRECISION,
  de DOUBLE PRECISION,
  de_error DOUBLE PRECISION,
  parallax DOUBLE PRECISION,
  parallax_error DOUBLE PRECISION,
  pmra DOUBLE PRECISION,
  pmra_error DOUBLE PRECISION,
  pmde DOUBLE PRECISION,
  pmde_error DOUBLE PRECISION,
  ra_de_corr REAL,
  ra_parallax_corr REAL,
  ra_pmra_corr REAL,
  ra_pmde_corr REAL,
  de_parallax_corr REAL,
  de_pmra_corr REAL,
  de_pmde_corr REAL,
  parallax_pmra_corr REAL,
  parallax_pmde_corr REAL,
  pmra_pmde_corr REAL,
  chisq REAL,
  uwe REAL,
  phot_z_mean_mag REAL,
  phot_z_std_mag REAL,
  phot_z_n_epochs SMALLINT,
  z_n_obs SMALLINT,
  z_n_det SMALLINT,
  z_n_amb SMALLINT,
  phot_y_mean_mag REAL,
  phot_y_std_mag REAL,
  phot_y_n_epochs SMALLINT,
  y_n_obs SMALLINT,
  y_n_det SMALLINT,
  y_n_amb SMALLINT,
  phot_j_mean_mag REAL,
  phot_j_std_mag REAL,
  phot_j_n_epochs SMALLINT,
  j_n_obs SMALLINT,
  j_n_det SMALLINT,
  j_n_amb SMALLINT,
  phot_h_mean_mag REAL,
  phot_h_std_mag REAL,
  phot_h_n_epochs SMALLINT,
  h_n_obs SMALLINT,
  h_n_det SMALLINT,
  h_n_amb SMALLINT,
  phot_ks_mean_mag REAL,
  phot_ks_std_mag REAL,
  phot_ks_n_epochs SMALLINT,
  ks_n_obs SMALLINT,
  ks_n_det SMALLINT,
  ks_n_amb SMALLINT,
  ks_first_epoch DOUBLE PRECISION,
  ks_last_epoch DOUBLE PRECISION,
  ks_skew REAL,
  ks_p0 REAL,
  ks_p1 REAL,
  ks_p2 REAL,
  ks_p4 REAL,
  ks_p5 REAL,
  ks_p8 REAL,
  ks_p16 REAL,
  ks_p25 REAL,
  ks_p32 REAL,
  ks_p50 REAL,
  ks_p68 REAL,
  ks_p75 REAL,
  ks_p84 REAL,
  ks_p92 REAL,
  ks_p95 REAL,
  ks_p96 REAL,
  ks_p98 REAL,
  ks_p99 REAL,
  ks_p100 REAL,
  ks_mad REAL,
  ks_med_err REAL,
  ks_stetson_i DOUBLE PRECISION,
  ks_stetson_j DOUBLE PRECISION,
  ks_stetson_k DOUBLE PRECISION,
  ks_stetson_group_count INTEGER,
  ks_eta DOUBLE PRECISION,
  ks_eta_f DOUBLE PRECISION,
  healpix_29 BIGINT,
  hats_norder SMALLINT,
  hats_dir BIGINT,
  hats_npix BIGINT
);


ALTER TABLE sandbox.virac2 ADD PRIMARY KEY (sourceid);

CREATE INDEX virac2_q3c_radec ON sandbox.virac2 (q3c_ang2ipix(ra, de));
CREATE INDEX virac2_healpix_29_idx ON sandbox.virac2 (healpix_29);
CREATE INDEX virac2_phot_j_mean_mag_idx ON sandbox.virac2 (phot_j_mean_mag);
CREATE INDEX virac2_phot_k_mean_mag_idx ON sandbox.virac2 (phot_k_mean_mag);
CREATE INDEX virac2_phot_ks_mean_mag_idx ON sandbox.virac2 (phot_ks_mean_mag);
