-- This create table statement is based on the below link.
-- https://gea.esac.esa.int/archive/documentation/GDR3/Gaia_archive/chap_datamodel/sec_dm_performance_verification/ssec_dm_synthetic_photometry_gspc.html

create table catalogdb.gaia_dr3_synthetic_photometry_gspc(
source_id bigint,  -- Unique source identifier (unique within a particular Data Release) (long)
c_star real,  -- BP/RP excess factor corrected for the expected colour dependency (float)
u_jkc_flux real,  -- U flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
u_jkc_flux_error real,  -- Error on the U flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
u_jkc_mag real,  -- U magnitude in the Johnson-Kron-Cousins system (float, Magnitude[mag])
u_jkc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
b_jkc_flux real,  -- B flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
b_jkc_flux_error real,  -- Error on the B flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
b_jkc_mag float,  -- B magnitude in the Johnson-Kron-Cousins system (float, Magnitude[mag])
b_jkc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
v_jkc_flux real,  -- V flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
v_jkc_flux_error real,  -- Error on the V flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
v_jkc_mag real,  -- V magnitude in the Johnson-Kron-Cousins system (float, Magnitude[mag])
v_jkc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
r_jkc_flux real,  -- R flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
r_jkc_flux_error real,  -- Error on the R flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
r_jkc_mag real,  -- R magnitude in the Johnson-Kron-Cousins system (float, Magnitude[mag])
r_jkc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
i_jkc_flux real,  -- I flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
i_jkc_flux_error real,  -- Error on the I flux in the Johnson-Kron-Cousins system (float, Flux[W m−2 nm−1])
i_jkc_mag real,  -- I magnitude in the Johnson-Kron-Cousins system (float, Magnitude[mag])
i_jkc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
u_sdss_flux real,  -- u flux in the SDSS system (float, Flux[W m−2 nm−1])
u_sdss_flux_error real,  -- Error on the u flux in the SDSS system (float, Flux[W m−2 nm−1])
u_sdss_mag real,  -- u magnitude in the SDSS system (float, Magnitude[mag])
u_sdss_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
g_sdss_flux real,  -- g flux in the SDSS system (float, Flux[W m−2 nm−1])
g_sdss_flux_error real,  -- Error on the g flux in the SDSS system (float, Flux[W m−2 nm−1])
g_sdss_mag real,  -- g magnitude in the SDSS system (float, Magnitude[mag])
g_sdss_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
r_sdss_flux real,  -- r flux in the SDSS system (float, Flux[W m−2 nm−1])
r_sdss_flux_error real,  -- Error on the r flux in the SDSS system (float, Flux[W m−2 nm−1])
r_sdss_mag real,  -- r magnitude in the SDSS system (float, Magnitude[mag])
r_sdss_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
i_sdss_flux real,  -- i flux in the SDSS system (float, Flux[W m−2 nm−1])
i_sdss_flux_error real,  -- Error on the i flux in the SDSS system (float, Flux[W m−2 nm−1])
i_sdss_mag real,  -- i magnitude in the SDSS system (float, Magnitude[mag])
i_sdss_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
z_sdss_flux real,  -- z flux in the SDSS system (float, Flux[W m−2 nm−1])
z_sdss_flux_error real,  -- Error on the z flux in the SDSS system (float, Flux[W m−2 nm−1])
z_sdss_mag real,  -- z magnitude in the SDSS system (float, Magnitude[mag])
z_sdss_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
y_ps1_flux real,  -- y flux in the Pan-STARRS1 system (float, Flux[W m−2 nm−1])
y_ps1_flux_error real,  -- Error on the y flux in the Pan-STARRS1 system (float, Flux[W m−2 nm−1])
y_ps1_mag real,  -- y magnitude in the Pan-STARRS1 system (float, Magnitude[mag])
y_ps1_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
f606w_acswfc_flux real,  -- F606W flux in the HST ACS/WFC system (float, Flux[W m−2 nm−1])
f606w_acswfc_flux_error real,  -- Error on the F606W flux in the HST ACS/WFC system (float, Flux[W m−2 nm−1])
f606w_acswfc_mag real,  -- F606W magnitude in the HST ACS/WFC system (float, Magnitude[mag])
f606w_acswfc_flag smallint,  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
f814w_acswfc_flux real,  -- F814W flux in the HST ACS/WFC system (float, Flux[W m−2 nm−1])
f814w_acswfc_flux_error real,  -- Error on the F814W flux in the HST ACS/WFC system (float, Flux[W m−2 nm−1])
f814w_acswfc_mag real,  -- F814W magnitude in the HST ACS/WFC system (float, Magnitude[mag])
f814w_acswfc_flag smallint  -- Flag indicating if G mag and BP-RP color of the source lie in the validated range (byte)
);
