#!/usr/bin/env python
# -*- coding: utf-8 -*-

# flake8: noqa: E501,E741
import operator
from functools import reduce

from peewee import (
    AutoField,
    BigBitField,
    BigIntegerField,
    BooleanField,
    DateTimeField,
    DoubleField,
    FloatField,
    IntegerField,
    TextField,
    fn
)
from playhouse.hybrid import hybrid_method
from playhouse.postgres_ext import ArrayField

from ... import BaseModel
from .. import database

class AstraCommon(BaseModel):
    class Meta:
        database = database


# --- Common ORMs across astra_050/080/081 ---

class ApogeeCoaddedSpectrumInApStar(AstraCommon):
    pk = AutoField()
    source_pk = IntegerField(index=True, null=True)
    star_pk = BigIntegerField(null=True, unique=True)
    release = TextField()
    filetype = TextField()
    apred = TextField()
    apstar = TextField()
    obj = TextField()
    telescope = TextField()
    healpix = IntegerField(null=True)
    min_mjd = IntegerField(null=True)
    max_mjd = IntegerField(null=True)
    n_entries = IntegerField(null=True)
    n_visits = IntegerField(null=True)
    n_good_visits = IntegerField(null=True)
    n_good_rvs = IntegerField(null=True)
    snr = FloatField(null=True)
    mean_fiber = FloatField(null=True)
    std_fiber = FloatField(null=True)
    spectrum_flags = BigIntegerField()
    v_rad = FloatField(null=True)
    e_v_rad = FloatField(null=True)
    std_v_rad = FloatField(null=True)
    median_e_v_rad = FloatField(null=True)
    doppler_teff = FloatField(null=True)
    doppler_e_teff = FloatField(null=True)
    doppler_logg = FloatField(null=True)
    doppler_e_logg = FloatField(null=True)
    doppler_fe_h = FloatField(null=True)
    doppler_e_fe_h = FloatField(null=True)
    doppler_rchi2 = FloatField(null=True)
    doppler_flags = BigIntegerField()
    xcorr_v_rad = FloatField(null=True)
    xcorr_v_rel = FloatField(null=True)
    xcorr_e_v_rel = FloatField(null=True)
    ccfwhm = FloatField(null=True)
    autofwhm = FloatField(null=True)
    n_components = IntegerField(null=True)

    class Meta:
        table_name = 'apogee_coadded_spectrum_in_ap_star'

class ApogeeCombinedSpectrum(AstraCommon):
    source_pk = IntegerField(index=True, null=True)
    release = TextField(index=True)
    filetype = TextField()
    v_astra = TextField()
    healpix = IntegerField()
    sdss_id = BigIntegerField(index=True, null=True)
    apred = TextField()
    obj = TextField()
    telescope = TextField()
    min_mjd = IntegerField(null=True)
    max_mjd = IntegerField(null=True)
    n_entries = IntegerField(null=True)
    n_visits = IntegerField(null=True)
    n_good_visits = IntegerField(null=True)
    n_good_rvs = IntegerField(null=True)
    snr = FloatField(null=True)
    mean_fiber = FloatField(null=True)
    std_fiber = FloatField(null=True)
    spectrum_flags = BigIntegerField()
    v_rad = FloatField(null=True)
    e_v_rad = FloatField(null=True)
    std_v_rad = FloatField(null=True)
    median_e_v_rad = FloatField(null=True)
    doppler_teff = FloatField(null=True)
    doppler_e_teff = FloatField(null=True)
    doppler_logg = FloatField(null=True)
    doppler_e_logg = FloatField(null=True)
    doppler_fe_h = FloatField(null=True)
    doppler_e_fe_h = FloatField(null=True)
    doppler_rchi2 = FloatField(null=True)
    doppler_flags = BigIntegerField()
    xcorr_v_rad = FloatField(null=True)
    xcorr_v_rel = FloatField(null=True)
    xcorr_e_v_rel = FloatField(null=True)
    ccfwhm = FloatField(null=True)
    autofwhm = FloatField(null=True)
    n_components = IntegerField(null=True)
    nmf_rchi2 = FloatField(null=True)
    nmf_flags = BigIntegerField()

    class Meta:
        table_name = 'apogee_combined_spectrum'

class ApogeeNet(AstraCommon):
    task_pk = AutoField()
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    fe_h = FloatField(null=True)
    e_fe_h = FloatField(null=True)
    result_flags = BigIntegerField()

class ApogeeRestFrameVisitSpectrum(AstraCommon):
    source_pk = IntegerField(index=True, null=True)
    catalogid = BigIntegerField(index=True, null=True)
    star_pk = BigIntegerField(null=True)
    visit_pk = BigIntegerField(null=True)
    rv_visit_pk = BigIntegerField(null=True)
    release = TextField(index=True)
    filetype = TextField()
    v_astra = TextField()
    healpix = IntegerField()
    sdss_id = BigIntegerField(index=True)
    apred = TextField(index=True)
    plate = TextField(index=True)
    telescope = TextField(index=True)
    fiber = IntegerField(index=True)
    mjd = IntegerField(index=True)
    field = TextField(index=True)
    prefix = TextField()
    reduction = TextField()
    obj = TextField(null=True)
    date_obs = DateTimeField(null=True)
    jd = FloatField(null=True)
    exptime = FloatField(null=True)
    dithered = BooleanField(null=True)
    f_night_time = FloatField(null=True)
    input_ra = FloatField(null=True)
    input_dec = FloatField(null=True)
    n_frames = IntegerField(null=True)
    assigned = IntegerField(null=True)
    on_target = IntegerField(null=True)
    valid = IntegerField(null=True)
    fps = BooleanField(null=True)
    snr = FloatField(null=True)
    spectrum_flags = BigIntegerField()
    v_rad = FloatField(null=True)
    v_rel = FloatField(null=True)
    e_v_rel = FloatField(null=True)
    bc = FloatField(null=True)
    doppler_teff = FloatField(null=True)
    doppler_e_teff = FloatField(null=True)
    doppler_logg = FloatField(null=True)
    doppler_e_logg = FloatField(null=True)
    doppler_fe_h = FloatField(null=True)
    doppler_e_fe_h = FloatField(null=True)
    doppler_rchi2 = FloatField(null=True)
    doppler_flags = BigIntegerField()
    xcorr_v_rad = FloatField(null=True)
    xcorr_v_rel = FloatField(null=True)
    xcorr_e_v_rel = FloatField(null=True)
    ccfwhm = FloatField(null=True)
    autofwhm = FloatField(null=True)
    n_components = IntegerField(null=True)
    nmf_rchi2 = FloatField(null=True)
    nmf_flags = BigIntegerField()

    class Meta:
        table_name = 'apogee_rest_frame_visit_spectrum'

class ApogeeVisitSpectrum(AstraCommon):
    pk = AutoField()
    source_pk = IntegerField(index=True, null=True)
    catalogid = BigIntegerField(index=True, null=True)
    star_pk = BigIntegerField(null=True)
    visit_pk = BigIntegerField(null=True, unique=True)
    rv_visit_pk = BigIntegerField(null=True, unique=True)
    release = TextField(index=True)
    filetype = TextField()
    apred = TextField(index=True)
    plate = TextField(index=True)
    telescope = TextField(index=True)
    fiber = IntegerField(index=True)
    mjd = IntegerField(index=True)
    field = TextField(index=True)
    prefix = TextField()
    reduction = TextField()
    obj = TextField(null=True)
    date_obs = DateTimeField(null=True)
    jd = FloatField(null=True)
    exptime = FloatField(null=True)
    dithered = BooleanField(null=True)
    f_night_time = FloatField(null=True)
    input_ra = FloatField(null=True)
    input_dec = FloatField(null=True)
    n_frames = IntegerField(null=True)
    assigned = IntegerField(null=True)
    on_target = IntegerField(null=True)
    valid = IntegerField(null=True)
    fps = BooleanField(null=True)
    snr = FloatField(null=True)
    spectrum_flags = BigIntegerField()
    v_rad = FloatField(null=True)
    v_rel = FloatField(null=True)
    e_v_rel = FloatField(null=True)
    bc = FloatField(null=True)
    doppler_teff = FloatField(null=True)
    doppler_e_teff = FloatField(null=True)
    doppler_logg = FloatField(null=True)
    doppler_e_logg = FloatField(null=True)
    doppler_fe_h = FloatField(null=True)
    doppler_e_fe_h = FloatField(null=True)
    doppler_rchi2 = FloatField(null=True)
    doppler_flags = BigIntegerField()
    xcorr_v_rad = FloatField(null=True)
    xcorr_v_rel = FloatField(null=True)
    xcorr_e_v_rel = FloatField(null=True)
    ccfwhm = FloatField(null=True)
    autofwhm = FloatField(null=True)
    n_components = IntegerField(null=True)

    class Meta:
        table_name = 'apogee_visit_spectrum'

class ApogeeVisitSpectrumInApStar(AstraCommon):
    pk = AutoField()
    source_pk = IntegerField(index=True, null=True)
    release = TextField()
    filetype = TextField()
    apred = TextField()
    apstar = TextField()
    obj = TextField()
    telescope = TextField()
    healpix = IntegerField(null=True)
    prefix = TextField()
    plate = TextField()
    mjd = IntegerField()
    fiber = IntegerField()
    reduction = TextField(null=True)

    class Meta:
        table_name = 'apogee_visit_spectrum_in_ap_star'

class AstroNn(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    c_h = FloatField(null=True)
    e_c_h = FloatField(null=True)
    c_1_h = FloatField(null=True)
    e_c_1_h = FloatField(null=True)
    n_h = FloatField(null=True)
    e_n_h = FloatField(null=True)
    o_h = FloatField(null=True)
    e_o_h = FloatField(null=True)
    na_h = FloatField(null=True)
    e_na_h = FloatField(null=True)
    mg_h = FloatField(null=True)
    e_mg_h = FloatField(null=True)
    al_h = FloatField(null=True)
    e_al_h = FloatField(null=True)
    si_h = FloatField(null=True)
    e_si_h = FloatField(null=True)
    p_h = FloatField(null=True)
    e_p_h = FloatField(null=True)
    s_h = FloatField(null=True)
    e_s_h = FloatField(null=True)
    k_h = FloatField(null=True)
    e_k_h = FloatField(null=True)
    ca_h = FloatField(null=True)
    e_ca_h = FloatField(null=True)
    ti_h = FloatField(null=True)
    e_ti_h = FloatField(null=True)
    ti_2_h = FloatField(null=True)
    e_ti_2_h = FloatField(null=True)
    v_h = FloatField(null=True)
    e_v_h = FloatField(null=True)
    cr_h = FloatField(null=True)
    e_cr_h = FloatField(null=True)
    mn_h = FloatField(null=True)
    e_mn_h = FloatField(null=True)
    fe_h = FloatField(null=True)
    e_fe_h = FloatField(null=True)
    co_h = FloatField(null=True)
    e_co_h = FloatField(null=True)
    ni_h = FloatField(null=True)
    e_ni_h = FloatField(null=True)
    result_flags = BigIntegerField()

    class Meta:
        table_name = 'astro_nn'

class AstroNnDist(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    k_mag = FloatField(null=True)
    ebv = FloatField(null=True)
    l_fakemag = FloatField(column_name='L_fakemag', null=True)
    dist = FloatField(null=True)
    result_flags = BigIntegerField()

    class Meta:
        table_name = 'astro_nn_dist'

class BossCombinedSpectrum(AstraCommon):
    spectrum_pk_id = IntegerField(null=True, unique=True)
    source_pk = IntegerField(index=True, null=True)
    release = TextField(index=True)
    filetype = TextField()
    v_astra = TextField()
    healpix = IntegerField(null=True)
    sdss_id = BigIntegerField(index=True)
    run2d = TextField()
    telescope = TextField(index=True)
    min_mjd = IntegerField(null=True)
    max_mjd = IntegerField(null=True)
    n_visits = IntegerField(null=True)
    n_good_visits = IntegerField(null=True)
    n_good_rvs = IntegerField(null=True)
    v_rad = FloatField(null=True)
    e_v_rad = FloatField(null=True)
    std_v_rad = FloatField(null=True)
    median_e_v_rad = FloatField(null=True)
    xcsao_teff = FloatField(null=True)
    xcsao_e_teff = FloatField(null=True)
    xcsao_logg = FloatField(null=True)
    xcsao_e_logg = FloatField(null=True)
    xcsao_fe_h = FloatField(null=True)
    xcsao_e_fe_h = FloatField(null=True)
    xcsao_meanrxc = FloatField(null=True)
    snr = FloatField(null=True)
    gri_gaia_transform_flags = BigIntegerField()
    zwarning_flags = BigIntegerField()
    nmf_rchi2 = FloatField(null=True)
    nmf_flags = BigIntegerField()

    class Meta:
        table_name = 'boss_combined_spectrum'

class BossNet(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    fe_h = FloatField(null=True)
    e_fe_h = FloatField(null=True)
    result_flags = BigIntegerField()

    class Meta:
        table_name = 'boss_net'

class BossRestFrameVisitSpectrum(AstraCommon):
    spectrum_pk_id = IntegerField(null=True, unique=True)
    source_pk = IntegerField(index=True, null=True)
    drp_spectrum_pk_id = IntegerField(unique=True)
    release = TextField(index=True)
    filetype = TextField()
    v_astra = TextField()
    healpix = IntegerField(null=True)
    sdss_id = BigIntegerField(index=True)
    run2d = TextField()
    mjd = IntegerField()
    fieldid = IntegerField()
    catalogid = BigIntegerField()
    n_exp = IntegerField(null=True)
    exptime = FloatField(null=True)
    plateid = IntegerField(null=True)
    cartid = IntegerField(null=True)
    mapid = IntegerField(null=True)
    slitid = IntegerField(null=True)
    psfsky = IntegerField(null=True)
    preject = FloatField(null=True)
    n_std = IntegerField(null=True)
    n_gal = IntegerField(null=True)
    lowrej = IntegerField(null=True)
    highrej = IntegerField(null=True)
    scatpoly = IntegerField(null=True)
    proftype = IntegerField(null=True)
    nfitpoly = IntegerField(null=True)
    skychi2 = FloatField(null=True)
    schi2min = FloatField(null=True)
    schi2max = FloatField(null=True)
    alt = FloatField(null=True)
    az = FloatField(null=True)
    telescope = TextField(null=True)
    seeing = FloatField(null=True)
    airmass = FloatField(null=True)
    airtemp = FloatField(null=True)
    dewpoint = FloatField(null=True)
    humidity = FloatField(null=True)
    pressure = FloatField(null=True)
    dust_a = FloatField(null=True)
    dust_b = FloatField(null=True)
    gust_direction = FloatField(null=True)
    gust_speed = FloatField(null=True)
    wind_direction = FloatField(null=True)
    wind_speed = FloatField(null=True)
    moon_dist_mean = FloatField(null=True)
    moon_phase_mean = FloatField(null=True)
    n_guide = IntegerField(null=True)
    tai_beg = BigIntegerField(null=True)
    tai_end = BigIntegerField(null=True)
    fiber_offset = BooleanField(null=True)
    f_night_time = FloatField(null=True)
    delta_ra = ArrayField(index=True, null=True)  # ARRAY
    delta_dec = ArrayField(index=True, null=True)  # ARRAY
    snr = FloatField(null=True)
    in_stack = BooleanField()
    gri_gaia_transform_flags = BigIntegerField()
    zwarning_flags = BigIntegerField()
    xcsao_v_rad = FloatField(null=True)
    xcsao_e_v_rad = FloatField(null=True)
    xcsao_teff = FloatField(null=True)
    xcsao_e_teff = FloatField(null=True)
    xcsao_logg = FloatField(null=True)
    xcsao_e_logg = FloatField(null=True)
    xcsao_fe_h = FloatField(null=True)
    xcsao_e_fe_h = FloatField(null=True)
    xcsao_rxc = FloatField(null=True)
    nmf_rchi2 = FloatField(null=True)
    nmf_flags = BigIntegerField()

    class Meta:
        table_name = 'boss_rest_frame_visit_spectrum'

class BossVisitSpectrum(AstraCommon):
    pk = AutoField()
    source_pk = IntegerField(index=True, null=True)
    release = TextField()
    filetype = TextField()
    run2d = TextField()
    mjd = IntegerField()
    fieldid = IntegerField()
    healpix = IntegerField()
    n_exp = IntegerField(null=True)
    exptime = FloatField(null=True)
    plateid = IntegerField(null=True)
    cartid = IntegerField(null=True)
    mapid = IntegerField(null=True)
    slitid = IntegerField(null=True)
    psfsky = IntegerField(null=True)
    preject = FloatField(null=True)
    n_std = IntegerField(null=True)
    n_gal = IntegerField(null=True)
    lowrej = IntegerField(null=True)
    highrej = IntegerField(null=True)
    scatpoly = IntegerField(null=True)
    proftype = IntegerField(null=True)
    nfitpoly = IntegerField(null=True)
    skychi2 = FloatField(null=True)
    schi2min = FloatField(null=True)
    schi2max = FloatField(null=True)
    alt = FloatField(null=True)
    az = FloatField(null=True)
    telescope = TextField(null=True)
    seeing = FloatField(null=True)
    airmass = FloatField(null=True)
    airtemp = FloatField(null=True)
    dewpoint = FloatField(null=True)
    humidity = FloatField(null=True)
    pressure = FloatField(null=True)
    dust_a = FloatField(null=True)
    dust_b = FloatField(null=True)
    gust_direction = FloatField(null=True)
    gust_speed = FloatField(null=True)
    wind_direction = FloatField(null=True)
    wind_speed = FloatField(null=True)
    moon_dist_mean = FloatField(null=True)
    moon_phase_mean = FloatField(null=True)
    n_guide = IntegerField(null=True)
    tai_beg = BigIntegerField(null=True)
    tai_end = BigIntegerField(null=True)
    fiber_offset = BooleanField(null=True)
    f_night_time = FloatField(null=True)
    delta_ra = ArrayField(index=True, null=True)  # ARRAY
    delta_dec = ArrayField(index=True, null=True)  # ARRAY
    snr = FloatField(null=True)
    gri_gaia_transform_flags = BigIntegerField()
    zwarning_flags = BigIntegerField()
    xcsao_v_rad = FloatField(null=True)
    xcsao_e_v_rad = FloatField(null=True)
    xcsao_teff = FloatField(null=True)
    xcsao_e_teff = FloatField(null=True)
    xcsao_logg = FloatField(null=True)
    xcsao_e_logg = FloatField(null=True)
    xcsao_fe_h = FloatField(null=True)
    xcsao_e_fe_h = FloatField(null=True)
    xcsao_rxc = FloatField(null=True)

    class Meta:
        table_name = 'boss_visit_spectrum'

class Corv(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    v_rad = FloatField(null=True)
    e_v_rad = FloatField(null=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    initial_teff = FloatField(null=True)
    initial_logg = FloatField(null=True)
    initial_v_rad = FloatField(null=True)
    rchi2 = FloatField(null=True)

    class Meta:
        table_name = 'corv'

class LineForest(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    eqw_h_alpha = FloatField(null=True)
    abs_h_alpha = FloatField(null=True)
    detection_stat_h_alpha = FloatField(null=True)
    detection_raw_h_alpha = FloatField(null=True)
    eqw_h_beta = FloatField(null=True)
    abs_h_beta = FloatField(null=True)
    detection_stat_h_beta = FloatField(null=True)
    detection_raw_h_beta = FloatField(null=True)
    eqw_h_gamma = FloatField(null=True)
    abs_h_gamma = FloatField(null=True)
    detection_stat_h_gamma = FloatField(null=True)
    detection_raw_h_gamma = FloatField(null=True)
    eqw_h_delta = FloatField(null=True)
    abs_h_delta = FloatField(null=True)
    detection_stat_h_delta = FloatField(null=True)
    detection_raw_h_delta = FloatField(null=True)
    eqw_h_epsilon = FloatField(null=True)
    abs_h_epsilon = FloatField(null=True)
    detection_stat_h_epsilon = FloatField(null=True)
    detection_raw_h_epsilon = FloatField(null=True)
    eqw_h_8 = FloatField(null=True)
    abs_h_8 = FloatField(null=True)
    detection_stat_h_8 = FloatField(null=True)
    detection_raw_h_8 = FloatField(null=True)
    eqw_h_9 = FloatField(null=True)
    abs_h_9 = FloatField(null=True)
    detection_stat_h_9 = FloatField(null=True)
    detection_raw_h_9 = FloatField(null=True)
    eqw_h_10 = FloatField(null=True)
    abs_h_10 = FloatField(null=True)
    detection_stat_h_10 = FloatField(null=True)
    detection_raw_h_10 = FloatField(null=True)
    eqw_h_11 = FloatField(null=True)
    abs_h_11 = FloatField(null=True)
    detection_stat_h_11 = FloatField(null=True)
    detection_raw_h_11 = FloatField(null=True)
    eqw_h_12 = FloatField(null=True)
    abs_h_12 = FloatField(null=True)
    detection_stat_h_12 = FloatField(null=True)
    detection_raw_h_12 = FloatField(null=True)
    eqw_h_13 = FloatField(null=True)
    abs_h_13 = FloatField(null=True)
    detection_stat_h_13 = FloatField(null=True)
    detection_raw_h_13 = FloatField(null=True)
    eqw_h_14 = FloatField(null=True)
    abs_h_14 = FloatField(null=True)
    detection_stat_h_14 = FloatField(null=True)
    detection_raw_h_14 = FloatField(null=True)
    eqw_h_15 = FloatField(null=True)
    abs_h_15 = FloatField(null=True)
    detection_stat_h_15 = FloatField(null=True)
    detection_raw_h_15 = FloatField(null=True)
    eqw_h_16 = FloatField(null=True)
    abs_h_16 = FloatField(null=True)
    detection_stat_h_16 = FloatField(null=True)
    detection_raw_h_16 = FloatField(null=True)
    eqw_h_17 = FloatField(null=True)
    abs_h_17 = FloatField(null=True)
    detection_stat_h_17 = FloatField(null=True)
    detection_raw_h_17 = FloatField(null=True)
    eqw_pa_7 = FloatField(null=True)
    abs_pa_7 = FloatField(null=True)
    detection_stat_pa_7 = FloatField(null=True)
    detection_raw_pa_7 = FloatField(null=True)
    eqw_pa_8 = FloatField(null=True)
    abs_pa_8 = FloatField(null=True)
    detection_stat_pa_8 = FloatField(null=True)
    detection_raw_pa_8 = FloatField(null=True)
    eqw_pa_9 = FloatField(null=True)
    abs_pa_9 = FloatField(null=True)
    detection_stat_pa_9 = FloatField(null=True)
    detection_raw_pa_9 = FloatField(null=True)
    eqw_pa_10 = FloatField(null=True)
    abs_pa_10 = FloatField(null=True)
    detection_stat_pa_10 = FloatField(null=True)
    detection_raw_pa_10 = FloatField(null=True)
    eqw_pa_11 = FloatField(null=True)
    abs_pa_11 = FloatField(null=True)
    detection_stat_pa_11 = FloatField(null=True)
    detection_raw_pa_11 = FloatField(null=True)
    eqw_pa_12 = FloatField(null=True)
    abs_pa_12 = FloatField(null=True)
    detection_stat_pa_12 = FloatField(null=True)
    detection_raw_pa_12 = FloatField(null=True)
    eqw_pa_13 = FloatField(null=True)
    abs_pa_13 = FloatField(null=True)
    detection_stat_pa_13 = FloatField(null=True)
    detection_raw_pa_13 = FloatField(null=True)
    eqw_pa_14 = FloatField(null=True)
    abs_pa_14 = FloatField(null=True)
    detection_stat_pa_14 = FloatField(null=True)
    detection_raw_pa_14 = FloatField(null=True)
    eqw_pa_15 = FloatField(null=True)
    abs_pa_15 = FloatField(null=True)
    detection_stat_pa_15 = FloatField(null=True)
    detection_raw_pa_15 = FloatField(null=True)
    eqw_pa_16 = FloatField(null=True)
    abs_pa_16 = FloatField(null=True)
    detection_stat_pa_16 = FloatField(null=True)
    detection_raw_pa_16 = FloatField(null=True)
    eqw_pa_17 = FloatField(null=True)
    abs_pa_17 = FloatField(null=True)
    detection_stat_pa_17 = FloatField(null=True)
    detection_raw_pa_17 = FloatField(null=True)
    eqw_ca_ii_8662 = FloatField(null=True)
    abs_ca_ii_8662 = FloatField(null=True)
    detection_stat_ca_ii_8662 = FloatField(null=True)
    detection_raw_ca_ii_8662 = FloatField(null=True)
    eqw_ca_ii_8542 = FloatField(null=True)
    abs_ca_ii_8542 = FloatField(null=True)
    detection_stat_ca_ii_8542 = FloatField(null=True)
    detection_raw_ca_ii_8542 = FloatField(null=True)
    eqw_ca_ii_8498 = FloatField(null=True)
    abs_ca_ii_8498 = FloatField(null=True)
    detection_stat_ca_ii_8498 = FloatField(null=True)
    detection_raw_ca_ii_8498 = FloatField(null=True)
    eqw_ca_k_3933 = FloatField(null=True)
    abs_ca_k_3933 = FloatField(null=True)
    detection_stat_ca_k_3933 = FloatField(null=True)
    detection_raw_ca_k_3933 = FloatField(null=True)
    eqw_ca_h_3968 = FloatField(null=True)
    abs_ca_h_3968 = FloatField(null=True)
    detection_stat_ca_h_3968 = FloatField(null=True)
    detection_raw_ca_h_3968 = FloatField(null=True)
    eqw_he_i_6678 = FloatField(null=True)
    abs_he_i_6678 = FloatField(null=True)
    detection_stat_he_i_6678 = FloatField(null=True)
    detection_raw_he_i_6678 = FloatField(null=True)
    eqw_he_i_5875 = FloatField(null=True)
    abs_he_i_5875 = FloatField(null=True)
    detection_stat_he_i_5875 = FloatField(null=True)
    detection_raw_he_i_5875 = FloatField(null=True)
    eqw_he_i_5015 = FloatField(null=True)
    abs_he_i_5015 = FloatField(null=True)
    detection_stat_he_i_5015 = FloatField(null=True)
    detection_raw_he_i_5015 = FloatField(null=True)
    eqw_he_i_4471 = FloatField(null=True)
    abs_he_i_4471 = FloatField(null=True)
    detection_stat_he_i_4471 = FloatField(null=True)
    detection_raw_he_i_4471 = FloatField(null=True)
    eqw_he_ii_4685 = FloatField(null=True)
    abs_he_ii_4685 = FloatField(null=True)
    detection_stat_he_ii_4685 = FloatField(null=True)
    detection_raw_he_ii_4685 = FloatField(null=True)
    eqw_n_ii_6583 = FloatField(null=True)
    abs_n_ii_6583 = FloatField(null=True)
    detection_stat_n_ii_6583 = FloatField(null=True)
    detection_raw_n_ii_6583 = FloatField(null=True)
    eqw_n_ii_6548 = FloatField(null=True)
    abs_n_ii_6548 = FloatField(null=True)
    detection_stat_n_ii_6548 = FloatField(null=True)
    detection_raw_n_ii_6548 = FloatField(null=True)
    eqw_s_ii_6716 = FloatField(null=True)
    abs_s_ii_6716 = FloatField(null=True)
    detection_stat_s_ii_6716 = FloatField(null=True)
    detection_raw_s_ii_6716 = FloatField(null=True)
    eqw_s_ii_6730 = FloatField(null=True)
    abs_s_ii_6730 = FloatField(null=True)
    detection_stat_s_ii_6730 = FloatField(null=True)
    detection_raw_s_ii_6730 = FloatField(null=True)
    eqw_fe_ii_5018 = FloatField(null=True)
    abs_fe_ii_5018 = FloatField(null=True)
    detection_stat_fe_ii_5018 = FloatField(null=True)
    detection_raw_fe_ii_5018 = FloatField(null=True)
    eqw_fe_ii_5169 = FloatField(null=True)
    abs_fe_ii_5169 = FloatField(null=True)
    detection_stat_fe_ii_5169 = FloatField(null=True)
    detection_raw_fe_ii_5169 = FloatField(null=True)
    eqw_fe_ii_5197 = FloatField(null=True)
    abs_fe_ii_5197 = FloatField(null=True)
    detection_stat_fe_ii_5197 = FloatField(null=True)
    detection_raw_fe_ii_5197 = FloatField(null=True)
    eqw_fe_ii_6432 = FloatField(null=True)
    abs_fe_ii_6432 = FloatField(null=True)
    detection_stat_fe_ii_6432 = FloatField(null=True)
    detection_raw_fe_ii_6432 = FloatField(null=True)
    eqw_o_i_5577 = FloatField(null=True)
    abs_o_i_5577 = FloatField(null=True)
    detection_stat_o_i_5577 = FloatField(null=True)
    detection_raw_o_i_5577 = FloatField(null=True)
    eqw_o_i_6300 = FloatField(null=True)
    abs_o_i_6300 = FloatField(null=True)
    detection_stat_o_i_6300 = FloatField(null=True)
    detection_raw_o_i_6300 = FloatField(null=True)
    eqw_o_i_6363 = FloatField(null=True)
    abs_o_i_6363 = FloatField(null=True)
    detection_stat_o_i_6363 = FloatField(null=True)
    detection_raw_o_i_6363 = FloatField(null=True)
    eqw_o_ii_3727 = FloatField(null=True)
    abs_o_ii_3727 = FloatField(null=True)
    detection_stat_o_ii_3727 = FloatField(null=True)
    detection_raw_o_ii_3727 = FloatField(null=True)
    eqw_o_iii_4959 = FloatField(null=True)
    abs_o_iii_4959 = FloatField(null=True)
    detection_stat_o_iii_4959 = FloatField(null=True)
    detection_raw_o_iii_4959 = FloatField(null=True)
    eqw_o_iii_5006 = FloatField(null=True)
    abs_o_iii_5006 = FloatField(null=True)
    detection_stat_o_iii_5006 = FloatField(null=True)
    detection_raw_o_iii_5006 = FloatField(null=True)
    eqw_o_iii_4363 = FloatField(null=True)
    abs_o_iii_4363 = FloatField(null=True)
    detection_stat_o_iii_4363 = FloatField(null=True)
    detection_raw_o_iii_4363 = FloatField(null=True)
    eqw_li_i = FloatField(null=True)
    abs_li_i = FloatField(null=True)
    detection_stat_li_i = FloatField(null=True)
    detection_raw_li_i = FloatField(null=True)

    class Meta:
        table_name = 'line_forest'

class MDwarfType(AstraCommon):
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    continuum = FloatField(null=True)
    result_flags = BigIntegerField()

    class Meta:
        table_name = 'm_dwarf_type'

class Slam(AstraCommon):
    task_pk = AutoField()
    v_astra = TextField()
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    fe_h = FloatField(null=True)
    e_fe_h = FloatField(null=True)
    rho_teff_logg = FloatField(null=True)
    rho_teff_fe_h = FloatField(null=True)
    rho_logg_fe_h = FloatField(null=True)
    initial_teff = FloatField(null=True)
    initial_logg = FloatField(null=True)
    initial_fe_h = FloatField(null=True)
    success = BooleanField()
    status = IntegerField()
    optimality = BooleanField()
    result_flags = BigIntegerField()
    chi2 = FloatField()
    rchi2 = FloatField()
    fe_h_niu = DoubleField(null=True)
    e_fe_h_niu = DoubleField(null=True)
    alpha_fe = DoubleField(null=True)
    e_alpha_fe = DoubleField(null=True)
    initial_alpha_fe = DoubleField(null=True)
    initial_fe_h_niu = DoubleField(null=True)
    rho_teff_fe_h_niu = DoubleField(null=True)
    rho_teff_alpha_fe = DoubleField(null=True)
    rho_logg_alpha_fe = DoubleField(null=True)
    rho_logg_fe_h_niu = DoubleField(null=True)
    rho_fe_h_fe_h_niu = DoubleField(null=True)
    rho_fe_h_alpha_fe = DoubleField(null=True)

    class Meta:
        table_name = 'slam'
        primary_key = False

class SnowWhite(AstraCommon):
    task_pk = AutoField()
    created = DateTimeField()
    t_elapsed = FloatField(null=True)
    t_overhead = FloatField(null=True)
    tag = TextField(index=True)
    classification = TextField(null=True)
    p_cv = FloatField(null=True)
    p_da = FloatField(null=True)
    p_dab = FloatField(null=True)
    p_dabz = FloatField(null=True)
    p_dah = FloatField(null=True)
    p_dahe = FloatField(null=True)
    p_dao = FloatField(null=True)
    p_daz = FloatField(null=True)
    p_da_ms = FloatField(null=True)
    p_db = FloatField(null=True)
    p_dba = FloatField(null=True)
    p_dbaz = FloatField(null=True)
    p_dbh = FloatField(null=True)
    p_dbz = FloatField(null=True)
    p_db_ms = FloatField(null=True)
    p_dc = FloatField(null=True)
    p_dc_ms = FloatField(null=True)
    p_do = FloatField(null=True)
    p_dq = FloatField(null=True)
    p_dqz = FloatField(null=True)
    p_dqpec = FloatField(null=True)
    p_dz = FloatField(null=True)
    p_dza = FloatField(null=True)
    p_dzb = FloatField(null=True)
    p_dzba = FloatField(null=True)
    p_mwd = FloatField(null=True)
    p_hotdq = FloatField(null=True)
    teff = FloatField(null=True)
    e_teff = FloatField(null=True)
    logg = FloatField(null=True)
    e_logg = FloatField(null=True)
    v_rel = FloatField(null=True)
    result_flags = BigIntegerField()

    class Meta:
        table_name = 'snow_white'

class Source(AstraCommon):
    pk = AutoField()
    sdss_id = BigIntegerField(null=True, unique=True)
    sdss4_apogee_id = TextField(null=True, unique=True)
    tic_v8_id = BigIntegerField(null=True)
    healpix = IntegerField(null=True)
    lead = TextField(null=True)
    version_id = IntegerField(null=True)
    n_associated = IntegerField(null=True)
    n_neighborhood = IntegerField()
    sdss5_target_flags = BigBitField(null=True)
    sdss4_apogee_target1_flags = BigIntegerField()
    sdss4_apogee_target2_flags = BigIntegerField()
    sdss4_apogee2_target1_flags = BigIntegerField()
    sdss4_apogee2_target2_flags = BigIntegerField()
    sdss4_apogee2_target3_flags = BigIntegerField()
    sdss4_apogee_member_flags = BigIntegerField()
    sdss4_apogee_extra_target_flags = BigIntegerField()
    ra = FloatField(null=True)
    dec = FloatField(null=True)
    plx = FloatField(null=True)
    e_plx = FloatField(null=True)
    pmra = FloatField(null=True)
    e_pmra = FloatField(null=True)
    pmde = FloatField(null=True)
    e_pmde = FloatField(null=True)
    gaia_v_rad = FloatField(null=True)
    gaia_e_v_rad = FloatField(null=True)
    g_mag = FloatField(null=True)
    bp_mag = FloatField(null=True)
    rp_mag = FloatField(null=True)
    j_mag = FloatField(null=True)
    e_j_mag = FloatField(null=True)
    h_mag = FloatField(null=True)
    e_h_mag = FloatField(null=True)
    k_mag = FloatField(null=True)
    e_k_mag = FloatField(null=True)
    ph_qual = TextField(null=True)
    bl_flg = TextField(null=True)
    cc_flg = TextField(null=True)
    w1_flux = FloatField(null=True)
    w1_dflux = FloatField(null=True)
    w1_frac = FloatField(null=True)
    w2_flux = FloatField(null=True)
    w2_dflux = FloatField(null=True)
    w2_frac = FloatField(null=True)
    w1uflags = BigIntegerField(null=True)
    w2uflags = BigIntegerField(null=True)
    w1aflags = BigIntegerField(null=True)
    w2aflags = BigIntegerField(null=True)
    mag4_5 = FloatField(null=True)
    d4_5m = FloatField(null=True)
    rms_f4_5 = FloatField(null=True)
    sqf_4_5 = BigIntegerField()
    mf4_5 = BigIntegerField()
    csf = BigIntegerField()
    zgr_teff = FloatField(null=True)
    zgr_e_teff = FloatField(null=True)
    zgr_logg = FloatField(null=True)
    zgr_e_logg = FloatField(null=True)
    zgr_fe_h = FloatField(null=True)
    zgr_e_fe_h = FloatField(null=True)
    zgr_e = FloatField(null=True)
    zgr_e_e = FloatField(null=True)
    zgr_plx = FloatField(null=True)
    zgr_e_plx = FloatField(null=True)
    zgr_teff_confidence = FloatField(null=True)
    zgr_logg_confidence = FloatField(null=True)
    zgr_fe_h_confidence = FloatField(null=True)
    zgr_ln_prior = FloatField(null=True)
    zgr_chi2 = FloatField(null=True)
    zgr_quality_flags = BigIntegerField()
    r_med_geo = FloatField(null=True)
    r_lo_geo = FloatField(null=True)
    r_hi_geo = FloatField(null=True)
    r_med_photogeo = FloatField(null=True)
    r_lo_photogeo = FloatField(null=True)
    r_hi_photogeo = FloatField(null=True)
    bailer_jones_flags = TextField(null=True)
    ebv = FloatField(null=True)
    e_ebv = FloatField(null=True)
    ebv_flags = BigIntegerField()
    ebv_zhang_2023 = FloatField(null=True)
    e_ebv_zhang_2023 = FloatField(null=True)
    ebv_sfd = FloatField(null=True)
    e_ebv_sfd = FloatField(null=True)
    ebv_rjce_glimpse = FloatField(null=True)
    e_ebv_rjce_glimpse = FloatField(null=True)
    ebv_rjce_allwise = FloatField(null=True)
    e_ebv_rjce_allwise = FloatField(null=True)
    ebv_bayestar_2019 = FloatField(null=True)
    e_ebv_bayestar_2019 = FloatField(null=True)
    ebv_edenhofer_2023 = FloatField(null=True)
    e_ebv_edenhofer_2023 = FloatField(null=True)
    u_jkc_mag_flag = IntegerField(null=True)
    b_jkc_mag_flag = IntegerField(null=True)
    v_jkc_mag_flag = IntegerField(null=True)
    r_jkc_mag_flag = IntegerField(null=True)
    i_jkc_mag_flag = IntegerField(null=True)
    u_sdss_mag_flag = IntegerField(null=True)
    g_sdss_mag_flag = IntegerField(null=True)
    r_sdss_mag_flag = IntegerField(null=True)
    i_sdss_mag_flag = IntegerField(null=True)
    z_sdss_mag_flag = IntegerField(null=True)
    y_ps1_mag_flag = IntegerField(null=True)
    n_boss_visits = IntegerField(null=True)
    boss_min_mjd = IntegerField(null=True)
    boss_max_mjd = IntegerField(null=True)
    n_apogee_visits = IntegerField(null=True)
    apogee_min_mjd = IntegerField(null=True)
    apogee_max_mjd = IntegerField(null=True)

    class Meta:
        table_name = 'source'

    @hybrid_method
    def is_sdss5_target_bit_set(self, bit):
        """
        An expression to evaluate whether this source is assigned to the carton with the given bit position.

        :param bit:
            The carton bit position.
        """
        return (fn.length(self.sdss5_target_flags) > int(bit / 8)) & (
            fn.get_bit(self.sdss5_target_flags, int(bit)) > 0
        )

    @hybrid_method
    def is_sdss5_target_any_bit_set(self, bits):
        """
        An expression to evaluate whether this source is assigned to any of the cartons with the given bit positions.

        :param bits:
            A list of carton bit positions.
        """
        conditions = [
            (fn.length(self.sdss5_target_flags) > int(bit / 8))
            & (fn.get_bit(self.sdss5_target_flags, int(bit)) > 0)
            for bit in bits
        ]
        return reduce(operator.or_, conditions)

class Spectrum(AstraCommon):
    pk = AutoField()

    class Meta:
        table_name = 'spectrum'
