-- The below create table statement is based on 
-- catalogs/marvels/dr11/dr11_marvelsVelocityCurveCCF_ndelee.fit

create table catalogdb.marvels_dr11_velocitycurve_ccf(
STARNAME varchar,  -- format = '64A'
FCJD double precision,  -- format = '1D'
RV double precision,  -- format = '1D'
RVERR double precision,  -- format = '1D'
VIS double precision,  -- format = '1D'
TOTALPHOTONS bigint,  -- format = '1K'; null = -9223372036854775808
BARYCENTRICVEL double precision,  -- format = '1D'
SPECNO smallint,  -- format = '1I'; null = -32768
EPOCHFILE varchar,  -- format = '256A'
TEMPLATE varchar,  -- format = '256A'
TWOMASS_NAME varchar,  -- format = '64A'
OBJECT varchar,  -- format = '32A'
EXPTYPE varchar,  -- format = '32A'
PLATEID varchar,  -- format = '32A'
RADECID varchar,  -- format = '32A'
CARTID integer,  -- format = '1J'; null = -2147483648
EXPTIME integer,  -- format = '1J'; null = -2147483648
DATE_OBS varchar,  -- format = '64A'
TIME varchar,  -- format = '64A'
UTC_OBS varchar,  -- format = '32A'
LST_OBS varchar,  -- format = '32A'
JD real,  -- format = '1E'
FCJD_IMG real,  -- format = '1E'
MJD real,  -- format = '1E'
RA double precision,  -- format = '1D'
DEC double precision,  -- format = '1D'
EPOCH integer,  -- format = '1J'; null = -2147483648
ALT real,  -- format = '1E'
AZ real,  -- format = '1E'
PMTAVG real,  -- format = '1E'
PMTRMS real,  -- format = '1E'
PMTMIN real,  -- format = '1E'
PMTMAX real,  -- format = '1E'
OBSFLAG varchar,  -- format = '16A'
IMGAVG real,  -- format = '1E'
IMGMAX real,  -- format = '1E'
IMGMIN real,  -- format = '1E'
SNRMAX real,  -- format = '1E'
SNRMEDN real,  -- format = '1E'
SNRMIN real,  -- format = '1E'
SNRAVG real,  -- format = '1E'
SNRSTDEV real,  -- format = '1E'
SEEING real,  -- format = '1E'
CCDTEMP real,  -- format = '1E'
CCDPRES real,  -- format = '1E'
P1 real,  -- format = '1E'
P1RMS real,  -- format = '1E'
P2 real,  -- format = '1E'
P2RMS real,  -- format = '1E'
P3 real,  -- format = '1E'
P3RMS real,  -- format = '1E'
T1 real,  -- format = '1E'
T1RMS real,  -- format = '1E'
T2 real,  -- format = '1E'
T2RMS real,  -- format = '1E'
T3 real,  -- format = '1E'
T3RMS real,  -- format = '1E'
T4 real,  -- format = '1E'
T4RMS real,  -- format = '1E'
T5 real,  -- format = '1E'
T5RMS real,  -- format = '1E'
T6 real,  -- format = '1E'
T6RMS real,  -- format = '1E'
T7 real,  -- format = '1E'
T7RMS real,  -- format = '1E'
T8 real,  -- format = '1E'
T8RMS real,  -- format = '1E'
T9 real,  -- format = '1E'
T9RMS real,  -- format = '1E'
T10 real,  -- format = '1E'
T10RMS real,  -- format = '1E'
T11 real,  -- format = '1E'
T11RMS real,  -- format = '1E'
T12 real,  -- format = '1E'
T12RMS real,  -- format = '1E'
T13 real,  -- format = '1E'
T13RMS real,  -- format = '1E'
T14 real,  -- format = '1E'
T14RMS real,  -- format = '1E'
T15 real,  -- format = '1E'
T15RMS real,  -- format = '1E'
T16 real,  -- format = '1E'
T16RMS real,  -- format = '1E'
BEAM smallint,  -- format = '1B'; null = 128
SURVEY varchar  -- format = '16A'
);
