-- The below create table statement is based on 
-- catalogs/marvels/dr11/dr11_marvelsStar_ndelee.fit

create table catalogdb.marvels_dr11_star(
STARNAME varchar,  -- format = '64A'
TWOMASS_NAME varchar,  -- format = '64A'
Plate varchar,  -- format = '32A'
GSC_Name varchar,  -- format = '64A'
TYC_Name varchar,  -- format = '64A'
HIP_Name varchar,  -- format = '62A'
RA_Final double precision,  -- format = '1D'
DEC_Final double precision,  -- format = '1D'
GSC_B double precision,  -- format = '1D'
GSC_V double precision,  -- format = '1D'
TWOMASS_J real,  -- format = '1E'
TWOMASS_H real,  -- format = '1E'
TWOMASS_K real,  -- format = '1E'
SP1 varchar,  -- format = '16A'
SP2 varchar,  -- format = '16A'
RPM_LOG_g varchar,  -- format = '32A'
Teff real,  -- format = '1E'
log_g real,  -- format = '1E'
FeH real,  -- format = '1E'
GSC_B_E real,  -- format = '1E'
GSC_V_E real,  -- format = '1E'
TWOMASS_J_E real,  -- format = '1E'
TWOMASS_H_E real,  -- format = '1E'
TWOMASS_K_E real,  -- format = '1E'
Teff_E real,  -- format = '1E'
log_g_E real,  -- format = '1E'
FeH_E real,  -- format = '1E'
Epoch_0 real,  -- format = '1E'
RA_0 double precision,  -- format = '1D'
DEC_0 double precision,  -- format = '1D'
RA_TWOMASS double precision,  -- format = '1D'
DEC_TWOMASS double precision,  -- format = '1D'
GSC_PM_RA double precision,  -- format = '1D'
GSC_PM_DEC double precision,  -- format = '1D'
GSC_PM_RA_E double precision,  -- format = '1D'
GSC_PM_DEC_E double precision,  -- format = '1D'
TYC_B real,  -- format = '1E'
TYC_B_E real,  -- format = '1E'
TYC_V real,  -- format = '1E'
TYC_V_E real,  -- format = '1E'
HIP_PLX real,  -- format = '1E'
HIP_PLX_E real,  -- format = '1E'
HIP_SPTYPE varchar  -- format = '32A'
);
