-- The create table statement is based on the information
-- in the allStarMergeTargOnly-dr17-synspec.fits file. 

create table catalogdb.sdss_dr17_apogee_allstarmerge(
    APOGEE_ID text,  -- format = '19A'
    NVISITS smallint,  -- format = 'I'
    NENTRIES integer,  -- format = 'J'
    RA double precision,  -- format = 'D'
    DEC double precision,  -- format = 'D'
    GLON double precision,  -- format = 'D'
    GLAT double precision,  -- format = 'D'
    PMRA real,  -- format = 'E'
    PMDEC real,  -- format = 'E'
    PM_SRC text,  -- format = '8A'
    J real,  -- format = 'E'
    J_ERR real,  -- format = 'E'
    H real,  -- format = 'E'
    H_ERR real,  -- format = 'E'
    K real,  -- format = 'E'
    K_ERR real,  -- format = 'E'
    AK real,  -- format = 'E'
    VHELIO_AVG real,  -- format = 'E'
    VHELIO_ERR real,  -- format = 'E'
    VSCATTER real,  -- format = 'E'
    SIG_RVVAR real,  -- format = 'E'
    BASELINE real,  -- format = 'E'
    MEAN_FIBER real,  -- format = 'E'
    SIG_FIBER real,  -- format = 'E'
    STARS_PK text,  -- format = '125A'
    NVISITS_ENTRY text,  -- format = '35A'
    SNR_ENTRY text,  -- format = '143A'
    TELESCOPES text,  -- format = '125A'
    FIELDS text,  -- format = '197A'
    TARGFLAGS text,  -- format = '294A'
    STARFLAGS text,  -- format = '130A'
    ASPCAPFLAGS text,  -- format = '175A'
    MEMBER text,  -- format = '9A'
    GAIA_SOURCE_ID bigint,  -- format = 'K'
    DIST real,  -- format = 'E'
    DIST_ERR real,  -- format = 'E'
    DIST_SRC text,  -- format = '8A'
    TEFF_AVG real,  -- format = 'E'
    TEFF_AVG_ERR real,  -- format = 'E'
    LOGG_AVG real,  -- format = 'E'
    LOGG_AVG_ERR real,  -- format = 'E'
    M_H_AVG real,  -- format = 'E'
    M_H_AVG_ERR real,  -- format = 'E'
    VISITS_PK text  -- format = '775A'
);
