-- The create table statement is based on the information in the below link:
-- https://gea.esac.esa.int/archive/documentation/GEDR3/Gaia_archive/chap_datamodel/sec_dm_main_tables/ssec_dm_gaia_source.html

create table catalogdb.gaia_edr3_source (
solution_id bigint, -- Solution Identifier (long)
designation varchar, -- Unique source designation (unique across all Data Releases) (string)
source_id bigint primary key, -- Unique source identifier (unique within a particular Data Release) (long)
random_index bigint, -- Random index used to select subsets (long)
ref_epoch double precision, -- Reference epoch (double, Time[Julian Years])
ra double precision, -- Right ascension (double, Angle[deg])
ra_error real, -- Standard error of right ascension (float, Angle[mas])
dec double precision, -- Declination (double, Angle[deg])
dec_error real, -- Standard error of declination (float, Angle[mas])
parallax double precision, -- Parallax (double, Angle[mas] )
parallax_error real, -- Standard error of parallax (float, Angle[mas] )
parallax_over_error real, -- Parallax divided by its standard error (float)
pm real, -- Total proper motion (float, Angular Velocity[mas/year])
pmra double precision, -- Proper motion in right ascension direction (double, Angular Velocity[mas/year])
pmra_error real, -- Standard error of proper motion in right ascension direction (float, Angular Velocity[mas/year] )
pmdec double precision -- Proper motion in declination direction (double, Angular Velocity[mas/year] )
pmdec_error real, -- Standard error of proper motion in declination direction (float, Angular Velocity[mas/year] )
ra_dec_corr real, -- Correlation between right ascension and declination (float, Dimensionless[see description])
ra_parallax_corr real, -- Correlation between right ascension and parallax (float, Dimensionless[see description])
ra_pmra_corr real, -- Correlation between right ascension and proper motion in right ascension (float, Dimensionless[see description])
ra_pmdec_corr real, -- Correlation between right ascension and proper motion in declination (float, Dimensionless[see description])
dec_parallax_corr real, -- Correlation between declination and parallax (float, Dimensionless[see description])
dec_pmra_corr real, -- Correlation between declination and proper motion in right ascension (float, Dimensionless[see description])
dec_pmdec_corr real, -- Correlation between declination and proper motion in declination (float, Dimensionless[see description])
parallax_pmra_corr real, -- Correlation between parallax and proper motion in right ascension (float, Dimensionless[see description])
parallax_pmdec_corr real, -- Correlation between parallax and proper motion in declination (float, Dimensionless[see description])
pmra_pmdec_corr real, -- Correlation between proper motion in right ascension and proper motion in declination (float, Dimensionless[see description])
astrometric_n_obs_al smallint, -- Total number of observations AL (short)
astrometric_n_obs_ac smallint, -- Total number of observations AC (short)
astrometric_n_good_obs_al smallint, -- Number of good observations AL (short)
astrometric_n_bad_obs_al smallint, -- Number of bad observations AL (short)
astrometric_gof_al real, -- Goodness of fit statistic of model wrt along-scan observations (float)
astrometric_chi2_al real, -- AL chi-square value (float)
astrometric_excess_noise real, -- Excess noise of the source (float, Angle[mas])
astrometric_excess_noise_sig real, -- Significance of excess noise (float)
astrometric_params_solved smallint, -- Which parameters have been solved for? (byte)
astrometric_primary_flag boolean, -- Primary or seconday (boolean)
nu_eff_used_in_astrometry real, -- Effective wavenumber of the source used in the astrometric solution (float, Misc[μm−1
pseudocolour real, -- Astrometrically estimated pseudocolour of the source (float, Misc[μm−1
pseudocolour_error real, -- Standard error of the pseudocolour of the source (float, Misc[μm−1
ra_pseudocolour_corr real, -- Correlation between right ascension and pseudocolour (float, Dimensionless[see description])
dec_pseudocolour_corr real, -- Correlation between declination and pseudocolour (float, Dimensionless[see description])
parallax_pseudocolour_corr real, -- Correlation between parallax and pseudocolour (float, Dimensionless[see description])
pmra_pseudocolour_corr real, -- Correlation between proper motion in right asension and pseudocolour (float, Dimensionless[see description])
pmdec_pseudocolour_corr real, -- Correlation between proper motion in declination and pseudocolour (float, Dimensionless[see description])
astrometric_matched_transits smallint, -- Matched FOV transits used in the AGIS solution (short)
visibility_periods_used smallint, -- Number of visibility periods used in Astrometric solution (short)
astrometric_sigma5d_max real, -- The longest semi-major axis of the 5-d error ellipsoid (float, Angle[mas])
matched_transits smallint, -- The number of transits matched to this source (short)
new_matched_transits smallint, -- The number of transits newly incorporated into an existing source in the current cycle (short)
matched_transits_removed smallint, -- The number of transits removed from an existing source in the current cycle (short)
ipd_gof_harmonic_amplitude real, -- Amplitude of the IPD GoF versus position angle of scan (float, Dimensionless[see description])
ipd_gof_harmonic_phase real, -- Phase of the IPD GoF versus position angle of scan (float, Angle[deg])
ipd_frac_multi_peak smallint, -- Percent of successful-IPD windows with more than one peak (byte)
ipd_frac_odd_win smallint, -- Percent of transits with truncated windows or multiple gate (byte)
ruwe real, -- Renormalised unit weight error (float)
scan_direction_strength_k1 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k2 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k3 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_strength_k4 real, -- Degree of concentration of scan directions across the source (float)
scan_direction_mean_k1 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k2 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k3 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
scan_direction_mean_k4 real, -- Mean position angle of scan directions across the source (float, Angle[deg])
duplicated_source boolean, -- Source with multiple source identifiers (boolean)
phot_g_n_obs smallint, -- Number of observations contributing to G photometry (short)
phot_g_mean_flux double precision, -- G-band mean flux (double, Flux[e-/s])
phot_g_mean_flux_error real, -- Error on G-band mean flux (float, Flux[e-/s])
phot_g_mean_flux_over_error real, -- G-band mean flux divided by its error (float)
phot_g_mean_mag real, -- G-band mean magnitude (float, Magnitude[mag])
phot_bp_n_obs smallint, -- Number of observations contributing to BP photometry (short)
phot_bp_mean_flux double precision, -- Integrated BP mean flux (double, Flux[e-/s])
phot_bp_mean_flux_error real, -- Error on the integrated BP mean flux (float, Flux[e-/s])
phot_bp_mean_flux_over_error real, -- Integrated BP mean flux divided by its error (float)
phot_bp_mean_mag real, -- Integrated BP mean magnitude (float, Magnitude[mag])
phot_rp_n_obs smallint, -- Number of observations contributing to RP photometry (short)
phot_rp_mean_flux double precision, -- Integrated RP mean flux (double, Flux[e-/s])
phot_rp_mean_flux_error real, -- Error on the integrated RP mean flux (float, Flux[e-/s])
phot_rp_mean_flux_over_error real, -- Integrated RP mean flux divided by its error (float)
phot_rp_mean_mag real, -- Integrated RP mean magnitude (float, Magnitude[mag])
phot_bp_n_contaminated_transits smallint, -- Number of BP contaminated transits (short)
phot_bp_n_blended_transits smallint, -- Number of BP blended transits (short)
phot_rp_n_contaminated_transits smallint, -- Number of RP contaminated transits (short)
phot_rp_n_blended_transits smallint, -- Number of RP blended transits (short)
phot_proc_mode smallint -- Photometry processing mode (byte)
phot_bp_rp_excess_factor real, -- BP/RP excess factor (float)
bp_rp real, -- BP - RP colour (float, Magnitude[mag])
bp_g real, -- BP - G colour (float, Magnitude[mag])
g_rp real, -- G - RP colour (float, Magnitude[mag])
dr2_radial_velocity real, -- Radial velocity from Gaia DR2 (float, Velocity[km/s] )
dr2_radial_velocity_error real, -- Radial velocity error from Gaia DR2 (float, Velocity[km/s] )
dr2_rv_nb_transits smallint, -- Number of transits used to compute radial velocity in Gaia DR2 (short)
dr2_rv_template_teff real, -- Teff of the template used to compute radial velocity in Gaia DR2 (float, Temperature[K])
dr2_rv_template_logg real, -- logg of the template used to compute radial velocity in Gaia DR2 (float, GravitySurface[log cgs])
dr2_rv_template_fe_h real, -- Fe/H of the template used to compute radial velocity in Gaia DR2 (float, Abundances[dex])
l double precision, -- Galactic longitude (double, Angle[deg])
b double precision, -- Galactic latitude (double, Angle[deg])
ecl_lon double precision, -- Ecliptic longitude (double, Angle[deg])
ecl_lat double precision -- Ecliptic latitude (double, Angle[deg])
);